/*
 * xHarbour build 0.99.70 Intl. (SimpLex)
 * Generated C source code from <ftp_conx.Prg>
 * Command: C:\xHarbour997\bin\harbour.exe C:\HELIO\siachb\ftp_conx.Prg /q /oC:\helio\siachb\ftp_conx.c /M /N -DxHB -DXHB_0990 -DXHB_0991 -DXHB_0992 -DXHB_0993 -DXHB_0994 -DXHB_09941 -DXHB_09950 -DXHB_09951a -DXHB_09951 -DXHB_09951b -DXHB_0996 -DXHB_09960 -DXHB_09961 -DXHB_09961B -DXHB_0997 -DXHB_09970 
 * Created: 2022.06.08 11:23:16 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "ftp_conx.Prg"

HB_FUNC( DOWNLOADS_FTP );
HB_FUNC( COMANDER );
HB_FUNC( DFTP );
HB_FUNC( UFTP );
HB_FUNC( FTP_MAIN );
HB_FUNC( TESTE_FTP );
HB_FUNC_EXTERN( __MVPUBLIC );
HB_FUNC_EXTERN( OP_TELA );
HB_FUNC_EXTERN( SPACE );
HB_FUNC_EXTERN( DEVPOS );
HB_FUNC_EXTERN( DEVOUT );
HB_FUNC_EXTERN( SETPOS );
HB_FUNC_EXTERN( ROW );
HB_FUNC_EXTERN( COL );
HB_FUNC_EXTERN( AADD );
HB_FUNC_EXTERN( __GET );
HB_FUNC_EXTERN( READMODAL );
HB_FUNC_EXTERN( LOWER );
HB_FUNC_EXTERN( ALLTRIM );
HB_FUNC_EXTERN( SUBSTR );
HB_FUNC_EXTERN( FECHA_TELA );
HB_FUNC_EXTERN( ATENCAO );
HB_FUNC_EXTERN( SR_SHOWVECTOR );
HB_FUNC_EXTERN( LEN );
HB_FUNC_EXTERN( MENSAGEM );
HB_FUNC_EXTERN( TURL );
HB_FUNC_EXTERN( TIPCLIENTFTP );
HB_FUNC_EXTERN( AT );
HB_FUNC_EXTERN( INETERRORCODE );
HB_FUNC_EXTERN( INETERRORDESC );
HB_FUNC_EXTERN( DIRECTORY );
HB_FUNC_EXTERN( QOUT );
HB_FUNC_EXTERN( ALERT );
HB_FUNC_EXTERN( EMPTY );
HB_FUNC_EXTERN( __QUIT );
HB_FUNC_EXTERN( VALTYPE );
HB_FUNC_EXTERN( FERASE );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 7

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_FTP_CONX )
{ "DOWNLOADS_FTP", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( DOWNLOADS_FTP )}, NULL },
{ "CSERVER", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CUSER", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CPASSWORD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "C", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__MVPUBLIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPUBLIC )}, NULL },
{ "OP_TELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_TELA )}, NULL },
{ "COMANDER", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( COMANDER )}, NULL },
{ "SPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPACE )}, NULL },
{ "DEVPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVPOS )}, NULL },
{ "DEVOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUT )}, NULL },
{ "SETPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETPOS )}, NULL },
{ "ROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( ROW )}, NULL },
{ "COL", {HB_FS_PUBLIC}, {HB_FUNCNAME( COL )}, NULL },
{ "AADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADD )}, NULL },
{ "GETLIST", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__GET", {HB_FS_PUBLIC}, {HB_FUNCNAME( __GET )}, NULL },
{ "DISPLAY", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "READMODAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READMODAL )}, NULL },
{ "LOWER", {HB_FS_PUBLIC}, {HB_FUNCNAME( LOWER )}, NULL },
{ "ALLTRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( ALLTRIM )}, NULL },
{ "SUBSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SUBSTR )}, NULL },
{ "DFTP", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DFTP )}, NULL },
{ "UFTP", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( UFTP )}, NULL },
{ "FECHA_TELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( FECHA_TELA )}, NULL },
{ "ATENCAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATENCAO )}, NULL },
{ "SR_SHOWVECTOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SHOWVECTOR )}, NULL },
{ "LEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( LEN )}, NULL },
{ "MENSAGEM", {HB_FS_PUBLIC}, {HB_FUNCNAME( MENSAGEM )}, NULL },
{ "NEW", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "TURL", {HB_FS_PUBLIC}, {HB_FUNCNAME( TURL )}, NULL },
{ "TIPCLIENTFTP", {HB_FS_PUBLIC}, {HB_FUNCNAME( TIPCLIENTFTP )}, NULL },
{ "_NCONNTIMEOUT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "_BUSEPASV", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "AT", {HB_FS_PUBLIC}, {HB_FUNCNAME( AT )}, NULL },
{ "_CSERVER", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OURL", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "_CUSERID", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "_CPASSWORD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OPEN", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DOWNLOADFILE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CLOSE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SOCKETCON", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "INETERRORCODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETERRORCODE )}, NULL },
{ "CREPLY", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "INETERRORDESC", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETERRORDESC )}, NULL },
{ "DIRECTORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( DIRECTORY )}, NULL },
{ "QOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( QOUT )}, NULL },
{ "UPLOADFILE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "FTP_MAIN", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( FTP_MAIN )}, NULL },
{ "CURL", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CFILE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ALERT", {HB_FS_PUBLIC}, {HB_FUNCNAME( ALERT )}, NULL },
{ "EMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EMPTY )}, NULL },
{ "__QUIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( __QUIT )}, NULL },
{ "OFTP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "VALTYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALTYPE )}, NULL },
{ "CWD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "TESTE_FTP", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( TESTE_FTP )}, NULL },
{ "LASTERRORMESSAGE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "WRETORNO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "FERASE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FERASE )}, NULL },
{ "VARQCLIZIP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DELE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_FTP_CONX )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_FTP_CONX
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_FTP_CONX = hb_vm_SymbolInit_FTP_CONX;
   #pragma data_seg()
#endif

HB_FUNC( DOWNLOADS_FTP )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 3, 0,	/* 3 */
	HB_P_ONE,
	HB_P_PUSHSYMNEAR, 5,	/* __MVPUBLIC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 1,	/* CSERVER */
	HB_P_PUSHSYMNEAR, 2,	/* CUSER */
	HB_P_PUSHSYMNEAR, 3,	/* CPASSWORD */
	HB_P_PUSHSYMNEAR, 4,	/* C */
	HB_P_DOSHORT, 4,
	HB_P_POPVARIABLE, 4, 0,	/* C */
/* 00020 */ HB_P_LINEOFFSET, 2,	/* 5 */
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'h', 't', 'i', 's', 'i', 's', 't', 'e', 'm', 'a', 's', '.', 'c', 'o', 'm', 0, 
	HB_P_POPVARIABLE, 1, 0,	/* CSERVER */
/* 00043 */ HB_P_LINEOFFSET, 3,	/* 6 */
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'h', 't', 'i', 's', 'i', 's', 't', 'e', 'm', 'a', 's', '.', 'c', 'o', 'm', 0, 
	HB_P_POPVARIABLE, 2, 0,	/* CUSER */
/* 00066 */ HB_P_LINEOFFSET, 4,	/* 7 */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'h', 't', 'i', '6', '8', '2', '1', '1', '0', 0, 
	HB_P_POPVARIABLE, 3, 0,	/* CPASSWORD */
/* 00083 */ HB_P_LINEOFFSET, 5,	/* 8 */
	HB_P_PUSHSYMNEAR, 6,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ONE,
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 7,
/* 00099 */ HB_P_LINEOFFSET, 6,	/* 9 */
	HB_P_PUSHSYMNEAR, 7,	/* COMANDER */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00106 */ HB_P_LINEOFFSET, 7,	/* 10 */
	HB_P_ENDPROC
/* 00109 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( COMANDER )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 15, 0,	/* 15 */
	HB_P_PUSHSYMNEAR, 8,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 77,	/* 77 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 1,	/* COM */
/* 00015 */ HB_P_LINEOFFSET, 1,	/* 16 */
	HB_P_LOCALNEARSETSTR, 2, 12, 0,	/* ARQ 12*/
	'l', 'e', 'i', 'a', '-', 'm', 'e', '.', 't', 'x', 't', 0, 
/* 00033 */ HB_P_LINEOFFSET, 2,	/* 17 */
	HB_P_PUSHSYMNEAR, 8,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 73,	/* 73 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 3,	/* PAS */
/* 00044 */ HB_P_LINEOFFSET, 4,	/* 19 */
	HB_P_PUSHVARIABLE, 4, 0,	/* C */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_POPVARIABLE, 4, 0,	/* C */
/* 00055 */ HB_P_LINEOFFSET, 5,	/* 20 */
	HB_P_PUSHSYMNEAR, 9,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 4, 0,	/* C */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 10,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'f', 't', 'p', ':', ' ', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 11,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 12,	/* ROW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 13,	/* COL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 14,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 15, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 16,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	1, 0,	/* COM */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00127) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00132) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'o', 'm', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 17, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 15, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00158 */ HB_P_LINEOFFSET, 6,	/* 21 */
	HB_P_PUSHSYMNEAR, 18,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 15, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 15, 0,	/* GETLIST */
/* 00180 */ HB_P_LINEOFFSET, 7,	/* 22 */
	HB_P_PUSHVARIABLE, 4, 0,	/* C */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_POPVARIABLE, 4, 0,	/* C */
/* 00191 */ HB_P_LINEOFFSET, 8,	/* 23 */
	HB_P_PUSHSYMNEAR, 19,	/* LOWER */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* COM */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'l', 'o', 'g', 'a', 'r', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 98, 1,	/* 354 (abs: 00563) */
/* 00212 */ HB_P_LINEOFFSET, 9,	/* 24 */
	HB_P_PUSHSYMNEAR, 9,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 4, 0,	/* C */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 10,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	's', 'e', 'r', 'v', 'i', 'd', 'o', 'r', ':', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 11,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 12,	/* ROW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 13,	/* COL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 14,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 15, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 16,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'c', 's', 'e', 'r', 'v', 'e', 'r', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 17, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 15, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00299 */ HB_P_LINEOFFSET, 10,	/* 25 */
	HB_P_PUSHVARIABLE, 4, 0,	/* C */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_POPVARIABLE, 4, 0,	/* C */
/* 00310 */ HB_P_LINEOFFSET, 11,	/* 26 */
	HB_P_PUSHSYMNEAR, 9,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 4, 0,	/* C */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 10,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'u', 'a', 'r', 'i', 'o', ':', ' ', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 11,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 12,	/* ROW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 13,	/* COL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 14,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 15, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 16,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'c', 'u', 's', 'e', 'r', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 17, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 15, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00395 */ HB_P_LINEOFFSET, 12,	/* 27 */
	HB_P_PUSHVARIABLE, 4, 0,	/* C */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_POPVARIABLE, 4, 0,	/* C */
/* 00406 */ HB_P_LINEOFFSET, 13,	/* 28 */
	HB_P_PUSHSYMNEAR, 9,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 4, 0,	/* C */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 10,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	's', 'e', 'n', 'h', 'a', ':', ' ', ' ', ' ', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 11,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 12,	/* ROW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 13,	/* COL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 14,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 15, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 16,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'c', 'p', 'a', 's', 's', 'w', 'o', 'r', 'd', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 17, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 15, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00495 */ HB_P_LINEOFFSET, 14,	/* 29 */
	HB_P_PUSHSYMNEAR, 18,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 15, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 15, 0,	/* GETLIST */
/* 00517 */ HB_P_LINEOFFSET, 15,	/* 30 */
	HB_P_PUSHSYMNEAR, 20,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* CSERVER */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 1, 0,	/* CSERVER */
/* 00530 */ HB_P_LINEOFFSET, 16,	/* 31 */
	HB_P_PUSHSYMNEAR, 20,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 2, 0,	/* CUSER */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 2, 0,	/* CUSER */
/* 00543 */ HB_P_LINEOFFSET, 17,	/* 32 */
	HB_P_PUSHSYMNEAR, 20,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 3, 0,	/* CPASSWORD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 3, 0,	/* CPASSWORD */
/* 00556 */ HB_P_LINEOFFSET, 18,	/* 33 */
	HB_P_PUSHSYMNEAR, 7,	/* COMANDER */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00563 */ HB_P_LINEOFFSET, 20,	/* 35 */
	HB_P_PUSHSYMNEAR, 20,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* COM */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 1,	/* COM */
/* 00574 */ HB_P_LINEOFFSET, 21,	/* 36 */
	HB_P_PUSHSYMNEAR, 19,	/* LOWER */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* COM */
	HB_P_ZERO,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'b', 'a', 'i', 'x', 'a', 'r', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 39, 1,	/* 295 (abs: 00896) */
/* 00604 */ HB_P_LINEOFFSET, 22,	/* 37 */
	HB_P_PUSHVARIABLE, 4, 0,	/* C */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_POPVARIABLE, 4, 0,	/* C */
/* 00615 */ HB_P_LINEOFFSET, 23,	/* 38 */
	HB_P_PUSHSYMNEAR, 9,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 4, 0,	/* C */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 10,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'A', 'r', 'q', 'u', 'i', 'v', 'o', ':', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 11,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 12,	/* ROW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 13,	/* COL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 14,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 15, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 16,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	2, 0,	/* ARQ */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00690) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00695) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'a', 'r', 'q', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 17, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 15, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00721 */ HB_P_LINEOFFSET, 24,	/* 39 */
	HB_P_PUSHVARIABLE, 4, 0,	/* C */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_POPVARIABLE, 4, 0,	/* C */
/* 00732 */ HB_P_LINEOFFSET, 25,	/* 40 */
	HB_P_PUSHSYMNEAR, 9,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 4, 0,	/* C */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 10,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'P', 'a', 's', 't', 'a', ':', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 11,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 12,	/* ROW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 13,	/* COL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 14,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 15, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 16,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	3, 0,	/* PAS */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00805) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00810) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'p', 'a', 's', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 17, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 15, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00836 */ HB_P_LINEOFFSET, 26,	/* 41 */
	HB_P_PUSHSYMNEAR, 18,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 15, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 15, 0,	/* GETLIST */
/* 00858 */ HB_P_LINEOFFSET, 27,	/* 42 */
	HB_P_PUSHSYMNEAR, 22,	/* DFTP */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 19,	/* LOWER */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 20,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* ARQ */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSYMNEAR, 19,	/* LOWER */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 20,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* PAS */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 2,
/* 00889 */ HB_P_LINEOFFSET, 28,	/* 43 */
	HB_P_PUSHSYMNEAR, 7,	/* COMANDER */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00896 */ HB_P_LINEOFFSET, 31,	/* 46 */
	HB_P_PUSHSYMNEAR, 19,	/* LOWER */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* COM */
	HB_P_ZERO,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'e', 'n', 'v', 'i', 'a', 'r', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 35,	/* 35 (abs: 00958) */
/* 00925 */ HB_P_LINEOFFSET, 32,	/* 47 */
	HB_P_PUSHSYMNEAR, 23,	/* UFTP */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 19,	/* LOWER */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 20,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* COM */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
/* 00951 */ HB_P_LINEOFFSET, 33,	/* 48 */
	HB_P_PUSHSYMNEAR, 7,	/* COMANDER */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00958 */ HB_P_LINEOFFSET, 36,	/* 51 */
	HB_P_PUSHSYMNEAR, 19,	/* LOWER */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* COM */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	's', 'a', 'i', 'r', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 37,	/* 37 (abs: 01012) */
/* 00977 */ HB_P_LINEOFFSET, 37,	/* 52 */
	HB_P_PUSHSYMNEAR, 8,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 2, 0,	/* CUSER */
/* 00989 */ HB_P_LINEOFFSET, 38,	/* 53 */
	HB_P_PUSHVARIABLE, 2, 0,	/* CUSER */
	HB_P_POPVARIABLE, 1, 0,	/* CSERVER */
/* 00997 */ HB_P_LINEOFFSET, 39,	/* 54 */
	HB_P_PUSHVARIABLE, 2, 0,	/* CUSER */
	HB_P_POPVARIABLE, 3, 0,	/* CPASSWORD */
/* 01005 */ HB_P_LINEOFFSET, 40,	/* 55 */
	HB_P_PUSHSYMNEAR, 7,	/* COMANDER */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01012 */ HB_P_LINEOFFSET, 42,	/* 57 */
	HB_P_PUSHSYMNEAR, 19,	/* LOWER */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* COM */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'f', 'e', 'c', 'h', 'a', 'r', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 12,	/* 12 (abs: 01043) */
/* 01033 */ HB_P_LINEOFFSET, 43,	/* 58 */
	HB_P_PUSHSYMNEAR, 24,	/* FECHA_TELA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01040 */ HB_P_LINEOFFSET, 44,	/* 59 */
	HB_P_ENDPROC,
	HB_P_ENDPROC
/* 01044 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( DFTP )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 7, 2,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 68, 0,	/* 68 */
	HB_P_TRUE,
	HB_P_POPLOCALNEAR, 6,	/* LRETORNO */
/* 00009 */ HB_P_LINEOFFSET, 3,	/* 71 */
	HB_P_LOCALNEARSETSTR, 9, 1, 0,	/* CFILE 1*/
	0, 
/* 00016 */ HB_P_LINEOFFSET, 20,	/* 88 */
	HB_P_PUSHSYMNEAR, 20,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'f', 't', 'p', ':', '/', '/', 0, 
	HB_P_PUSHSYMNEAR, 20,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 2, 0,	/* CUSER */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	':', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 20,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 3, 0,	/* CPASSWORD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'@', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 20,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* CSERVER */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'/', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 20,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* CPASTA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 4,	/* CURL */
/* 00084 */ HB_P_LINEOFFSET, 26,	/* 94 */
	HB_P_PUSHLOCALNEAR, 1,	/* CCARPETA */
	HB_P_ONE,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYGEN, 4, 0,	/* 4 */
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_POPLOCALNEAR, 3,	/* AFILES */
/* 00101 */ HB_P_LINEOFFSET, 29,	/* 97 */
	HB_P_PUSHSYMNEAR, 25,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 26,	/* SR_SHOWVECTOR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* AFILES */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
/* 00115 */ HB_P_LINEOFFSET, 31,	/* 99 */
	HB_P_PUSHSYMNEAR, 27,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* AFILES */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSE, 44, 2,	/* 556 (abs: 00682) */
/* 00129 */ HB_P_LINEOFFSET, 32,	/* 100 */
	HB_P_PUSHSYMNEAR, 28,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 29,	/* 29 */
	'C', 'o', 'n', 'e', 'c', 't', 'a', 'n', 'd', 'o', ' ', 'c', 'o', 'm', ' ', 'o', ' ', 's', 'e', 'r', 'v', 'i', 'd', 'o', 'r', '.', '.', '.', 0, 
	HB_P_DOSHORT, 1,
/* 00167 */ HB_P_LINEOFFSET, 33,	/* 101 */
	HB_P_MESSAGE, 29, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 30,	/* TURL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 4,	/* CURL */
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 7,	/* OURL */
/* 00183 */ HB_P_LINEOFFSET, 35,	/* 103 */
	HB_P_MESSAGE, 29, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 31,	/* TIPCLIENTFTP */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 7,	/* OURL */
	HB_P_TRUE,
	HB_P_SENDSHORT, 2,
	HB_P_POPLOCALNEAR, 8,	/* OFTP */
/* 00200 */ HB_P_LINEOFFSET, 37,	/* 105 */
	HB_P_MESSAGE, 32, 0,	/* _NCONNTIMEOUT */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_PUSHINT, 32, 78,	/* 20000 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00213 */ HB_P_LINEOFFSET, 38,	/* 106 */
	HB_P_MESSAGE, 33, 0,	/* _BUSEPASV */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_TRUE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00224 */ HB_P_LINEOFFSET, 41,	/* 109 */
	HB_P_PUSHSYMNEAR, 28,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'V', 'e', 'r', 'i', 'f', 'i', 'c', 'a', 'n', 'd', 'o', ' ', 's', 'e', ' ', 'o', ' ', 'u', 's', 'u', 'a', 'r', 'i', 'o', ' ', 't', 'e', 'm', ' ', 'a', 'c', 'e', 's', 's', 'o', '.', '.', '.', 0, 
	HB_P_DOSHORT, 1,
/* 00272 */ HB_P_LINEOFFSET, 42,	/* 110 */
	HB_P_PUSHSYMNEAR, 34,	/* AT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'@', 0, 
	HB_P_PUSHVARIABLE, 2, 0,	/* CUSER */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 56,	/* 56 (abs: 00344) */
/* 00290 */ HB_P_LINEOFFSET, 43,	/* 111 */
	HB_P_MESSAGE, 35, 0,	/* _CSERVER */
	HB_P_MESSAGE, 36, 0,	/* OURL */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHVARIABLE, 1, 0,	/* CSERVER */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00308 */ HB_P_LINEOFFSET, 44,	/* 112 */
	HB_P_MESSAGE, 37, 0,	/* _CUSERID */
	HB_P_MESSAGE, 36, 0,	/* OURL */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHVARIABLE, 2, 0,	/* CUSER */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00326 */ HB_P_LINEOFFSET, 45,	/* 113 */
	HB_P_MESSAGE, 38, 0,	/* _CPASSWORD */
	HB_P_MESSAGE, 36, 0,	/* OURL */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHVARIABLE, 3, 0,	/* CPASSWORD */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00344 */ HB_P_LINEOFFSET, 48,	/* 116 */
	HB_P_MESSAGE, 39, 0,	/* OPEN */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_PUSHLOCALNEAR, 4,	/* CURL */
	HB_P_SENDSHORT, 1,
	HB_P_JUMPFALSENEAR, 102,	/* 102 (abs: 00457) */
/* 00357 */ HB_P_LINEOFFSET, 49,	/* 117 */
	HB_P_PUSHSYMNEAR, 28,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 30,	/* 30 */
	'F', 'a', 'z', 'e', 'n', 'd', 'o', ' ', 'D', 'O', 'W', 'N', 'L', 'O', 'A', 'D', 'S', ' ', 'n', 'o', ' ', 'a', 'r', 'q', 'u', 'i', 'v', 'o', ':', 0, 
	HB_P_PUSHLOCALNEAR, 9,	/* CFILE */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
/* 00401 */ HB_P_LINEOFFSET, 50,	/* 118 */
	HB_P_PUSHLOCALREF, 9, 0,	/* CFILE */
	HB_P_PUSHLOCALNEAR, 3,	/* AFILES */
	HB_P_FOREACH,
	HB_P_ENUMERATE,
	HB_P_JUMPFALSENEAR, 33,	/* 33 (abs: 00443) */
/* 00412 */ HB_P_LINEOFFSET, 51,	/* 119 */
	HB_P_MESSAGE, 40, 0,	/* DOWNLOADFILE */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_PUSHLOCALNEAR, 9,	/* CFILE */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_JUMPTRUENEAR, 9,	/* 9 (abs: 00434) */
/* 00427 */ HB_P_LINEOFFSET, 52,	/* 120 */
	HB_P_FALSE,
	HB_P_POPLOCALNEAR, 6,	/* LRETORNO */
	HB_P_JUMPNEAR, 11,	/* 11 (abs: 00443) */
/* 00434 */ HB_P_LINEOFFSET, 55,	/* 123 */
	HB_P_TRUE,
	HB_P_POPLOCALNEAR, 6,	/* LRETORNO */
/* 00439 */ HB_P_LINEOFFSET, 57,	/* 125 */
	HB_P_JUMPNEAR, 224,	/* -32 (abs: 00409) */
	HB_P_ENDENUMERATE,
/* 00444 */ HB_P_LINEOFFSET, 58,	/* 126 */
	HB_P_MESSAGE, 41, 0,	/* CLOSE */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMP, 228, 0,	/* 228 (abs: 00682) */
/* 00457 */ HB_P_LINEOFFSET, 60,	/* 128 */
	HB_P_PUSHSTRSHORT, 41,	/* 41 */
	'N', 'a', 'o', ' ', 's', 'e', ' ', 'p', 'o', 'd', 'e', ' ', 'c', 'o', 'n', 'e', 'c', 't', 'a', 'r', ' ', 'c', 'o', 'm', ' ', 'o', ' ', 's', 'e', 'r', 'v', 'i', 'd', 'o', 'r', ' ', 'F', 'T', 'P', ' ', 0, 
	HB_P_MESSAGE, 1, 0,	/* CSERVER */
	HB_P_PUSHLOCALNEAR, 7,	/* OURL */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 5,	/* CSTR */
/* 00512 */ HB_P_LINEOFFSET, 61,	/* 129 */
	HB_P_MESSAGE, 42, 0,	/* SOCKETCON */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 40,	/* 40 (abs: 00563) */
/* 00525 */ HB_P_LINEOFFSET, 62,	/* 130 */
	HB_P_PUSHLOCALNEAR, 5,	/* CSTR */
	HB_P_PUSHSTRSHORT, 27,	/* 27 */
	13, 10, 'C', 'o', 'n', 'e', 'x', 'a', 'o', ' ', 'n', 'a', 'o', ' ', 'i', 'n', 'i', 'c', 'i', 'a', 'l', 'i', 'z', 'a', 'd', 'a', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 5,	/* CSTR */
	HB_P_JUMPNEAR, 107,	/* 107 (abs: 00668) */
/* 00563 */ HB_P_LINEOFFSET, 63,	/* 131 */
	HB_P_PUSHSYMNEAR, 43,	/* INETERRORCODE */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 42, 0,	/* SOCKETCON */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 46,	/* 46 (abs: 00625) */
/* 00581 */ HB_P_LINEOFFSET, 64,	/* 132 */
	HB_P_PUSHLOCALNEAR, 5,	/* CSTR */
	HB_P_PUSHSTRSHORT, 25,	/* 25 */
	13, 10, 'R', 'e', 's', 'p', 'o', 's', 't', 'a', ' ', 'd', 'o', ' ', 's', 'e', 'r', 'v', 'i', 'd', 'o', 'r', ':', ' ', 0, 
	HB_P_MESSAGE, 44, 0,	/* CREPLY */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 5,	/* CSTR */
	HB_P_JUMPNEAR, 45,	/* 45 (abs: 00668) */
/* 00625 */ HB_P_LINEOFFSET, 66,	/* 134 */
	HB_P_PUSHLOCALNEAR, 5,	/* CSTR */
	HB_P_PUSHSTRSHORT, 21,	/* 21 */
	13, 10, 'E', 'r', 'r', 'o', 'r', ' ', 'n', 'a', ' ', 'c', 'o', 'n', 'e', 'x', 'a', 'o', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 45,	/* INETERRORDESC */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 42, 0,	/* SOCKETCON */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 5,	/* CSTR */
/* 00668 */ HB_P_LINEOFFSET, 68,	/* 136 */
	HB_P_PUSHSYMNEAR, 25,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* CSTR */
	HB_P_DOSHORT, 1,
/* 00677 */ HB_P_LINEOFFSET, 69,	/* 137 */
	HB_P_FALSE,
	HB_P_POPLOCALNEAR, 6,	/* LRETORNO */
/* 00682 */ HB_P_LINEOFFSET, 72,	/* 140 */
	HB_P_PUSHLOCALNEAR, 6,	/* LRETORNO */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00688 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( UFTP )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 7, 2,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 147, 0,	/* 147 */
	HB_P_TRUE,
	HB_P_POPLOCALNEAR, 6,	/* LRETORNO */
/* 00009 */ HB_P_LINEOFFSET, 3,	/* 150 */
	HB_P_LOCALNEARSETSTR, 9, 1, 0,	/* CFILE 1*/
	0, 
/* 00016 */ HB_P_LINEOFFSET, 5,	/* 152 */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'f', 't', 'p', ':', '/', '/', 0, 
	HB_P_PUSHVARIABLE, 2, 0,	/* CUSER */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	':', 0, 
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 3, 0,	/* CPASSWORD */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'@', 0, 
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 1, 0,	/* CSERVER */
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 4,	/* CURL */
/* 00051 */ HB_P_LINEOFFSET, 8,	/* 155 */
	HB_P_PUSHSYMNEAR, 46,	/* DIRECTORY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* CCARPETA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 3,	/* AFILES */
/* 00062 */ HB_P_LINEOFFSET, 10,	/* 157 */
	HB_P_PUSHSYMNEAR, 27,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* AFILES */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSE, 206, 1,	/* 462 (abs: 00535) */
/* 00076 */ HB_P_LINEOFFSET, 12,	/* 159 */
	HB_P_MESSAGE, 29, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 30,	/* TURL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 4,	/* CURL */
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 7,	/* OURL */
/* 00092 */ HB_P_LINEOFFSET, 13,	/* 160 */
	HB_P_MESSAGE, 29, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 31,	/* TIPCLIENTFTP */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 7,	/* OURL */
	HB_P_TRUE,
	HB_P_SENDSHORT, 2,
	HB_P_POPLOCALNEAR, 8,	/* OFTP */
/* 00109 */ HB_P_LINEOFFSET, 14,	/* 161 */
	HB_P_MESSAGE, 32, 0,	/* _NCONNTIMEOUT */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_PUSHINT, 32, 78,	/* 20000 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00122 */ HB_P_LINEOFFSET, 15,	/* 162 */
	HB_P_MESSAGE, 33, 0,	/* _BUSEPASV */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_TRUE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00133 */ HB_P_LINEOFFSET, 18,	/* 165 */
	HB_P_PUSHSYMNEAR, 34,	/* AT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'@', 0, 
	HB_P_PUSHVARIABLE, 2, 0,	/* CUSER */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 56,	/* 56 (abs: 00205) */
/* 00151 */ HB_P_LINEOFFSET, 19,	/* 166 */
	HB_P_MESSAGE, 35, 0,	/* _CSERVER */
	HB_P_MESSAGE, 36, 0,	/* OURL */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHVARIABLE, 1, 0,	/* CSERVER */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00169 */ HB_P_LINEOFFSET, 20,	/* 167 */
	HB_P_MESSAGE, 37, 0,	/* _CUSERID */
	HB_P_MESSAGE, 36, 0,	/* OURL */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHVARIABLE, 2, 0,	/* CUSER */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00187 */ HB_P_LINEOFFSET, 21,	/* 168 */
	HB_P_MESSAGE, 38, 0,	/* _CPASSWORD */
	HB_P_MESSAGE, 36, 0,	/* OURL */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHVARIABLE, 3, 0,	/* CPASSWORD */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00205 */ HB_P_LINEOFFSET, 24,	/* 171 */
	HB_P_MESSAGE, 39, 0,	/* OPEN */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_PUSHLOCALNEAR, 4,	/* CURL */
	HB_P_SENDSHORT, 1,
	HB_P_JUMPFALSENEAR, 83,	/* 83 (abs: 00299) */
/* 00218 */ HB_P_LINEOFFSET, 25,	/* 172 */
	HB_P_PUSHLOCALREF, 9, 0,	/* CFILE */
	HB_P_PUSHLOCALNEAR, 3,	/* AFILES */
	HB_P_FOREACH,
	HB_P_ENUMERATE,
	HB_P_JUMPFALSENEAR, 58,	/* 58 (abs: 00285) */
/* 00229 */ HB_P_LINEOFFSET, 26,	/* 173 */
	HB_P_PUSHSYMNEAR, 47,	/* QOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'a', 'r', 'q', 'u', 'i', 'v', 'o', ' ', ':', ' ', 0, 
	HB_P_PUSHLOCALNEAR, 9,	/* CFILE */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
/* 00254 */ HB_P_LINEOFFSET, 27,	/* 174 */
	HB_P_MESSAGE, 48, 0,	/* UPLOADFILE */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_PUSHLOCALNEAR, 9,	/* CFILE */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_JUMPTRUENEAR, 9,	/* 9 (abs: 00276) */
/* 00269 */ HB_P_LINEOFFSET, 28,	/* 175 */
	HB_P_FALSE,
	HB_P_POPLOCALNEAR, 6,	/* LRETORNO */
	HB_P_JUMPNEAR, 11,	/* 11 (abs: 00285) */
/* 00276 */ HB_P_LINEOFFSET, 31,	/* 178 */
	HB_P_TRUE,
	HB_P_POPLOCALNEAR, 6,	/* LRETORNO */
/* 00281 */ HB_P_LINEOFFSET, 34,	/* 181 */
	HB_P_JUMPNEAR, 199,	/* -57 (abs: 00226) */
	HB_P_ENDENUMERATE,
/* 00286 */ HB_P_LINEOFFSET, 35,	/* 182 */
	HB_P_MESSAGE, 41, 0,	/* CLOSE */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMP, 239, 0,	/* 239 (abs: 00535) */
/* 00299 */ HB_P_LINEOFFSET, 37,	/* 184 */
	HB_P_PUSHSTRSHORT, 46,	/* 46 */
	'N', 'o', ' ', 's', 'e', ' ', 'h', 'a', ' ', 'p', 'o', 'd', 'i', 'd', 'o', ' ', 'c', 'o', 'n', 'e', 'c', 't', 'a', 'r', ' ', 'c', 'o', 'n', ' ', 'e', 'l', ' ', 's', 'e', 'r', 'v', 'i', 'd', 'o', 'r', ' ', 'F', 'T', 'P', ' ', 0, 
	HB_P_MESSAGE, 1, 0,	/* CSERVER */
	HB_P_PUSHLOCALNEAR, 7,	/* OURL */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 5,	/* CSTR */
/* 00359 */ HB_P_LINEOFFSET, 38,	/* 185 */
	HB_P_MESSAGE, 42, 0,	/* SOCKETCON */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 40,	/* 40 (abs: 00410) */
/* 00372 */ HB_P_LINEOFFSET, 39,	/* 186 */
	HB_P_PUSHLOCALNEAR, 5,	/* CSTR */
	HB_P_PUSHSTRSHORT, 27,	/* 27 */
	13, 10, 'C', 'o', 'n', 'e', 'x', 'i', 243, 'n', ' ', 'n', 'o', ' ', 'i', 'n', 'i', 'c', 'i', 'a', 'l', 'i', 'z', 'a', 'd', 'a', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 5,	/* CSTR */
	HB_P_JUMPNEAR, 113,	/* 113 (abs: 00521) */
/* 00410 */ HB_P_LINEOFFSET, 40,	/* 187 */
	HB_P_PUSHSYMNEAR, 43,	/* INETERRORCODE */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 42, 0,	/* SOCKETCON */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 48,	/* 48 (abs: 00474) */
/* 00428 */ HB_P_LINEOFFSET, 41,	/* 188 */
	HB_P_PUSHLOCALNEAR, 5,	/* CSTR */
	HB_P_PUSHSTRSHORT, 27,	/* 27 */
	13, 10, 'R', 'e', 's', 'p', 'u', 'e', 's', 't', 'a', ' ', 'd', 'e', 'l', ' ', 's', 'e', 'r', 'v', 'i', 'd', 'o', 'r', ':', ' ', 0, 
	HB_P_MESSAGE, 44, 0,	/* CREPLY */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 5,	/* CSTR */
	HB_P_JUMPNEAR, 49,	/* 49 (abs: 00521) */
/* 00474 */ HB_P_LINEOFFSET, 43,	/* 190 */
	HB_P_PUSHLOCALNEAR, 5,	/* CSTR */
	HB_P_PUSHSTRSHORT, 25,	/* 25 */
	13, 10, 'E', 'r', 'r', 'o', 'r', ' ', 'e', 'n', ' ', 'l', 'a', ' ', 'c', 'o', 'n', 'e', 'x', 'i', 243, 'n', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 45,	/* INETERRORDESC */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 42, 0,	/* SOCKETCON */
	HB_P_PUSHLOCALNEAR, 8,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 5,	/* CSTR */
/* 00521 */ HB_P_LINEOFFSET, 45,	/* 192 */
	HB_P_PUSHSYMNEAR, 47,	/* QOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* CSTR */
	HB_P_DOSHORT, 1,
/* 00530 */ HB_P_LINEOFFSET, 46,	/* 193 */
	HB_P_FALSE,
	HB_P_POPLOCALNEAR, 6,	/* LRETORNO */
/* 00535 */ HB_P_LINEOFFSET, 49,	/* 196 */
	HB_P_PUSHLOCALNEAR, 6,	/* LRETORNO */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00541 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( FTP_MAIN )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 210, 0,	/* 210 */
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'H', 'T', 'I', 's', 'i', 's', 't', 'e', 'm', 'a', 's', '.', 'c', 'o', 'm', '.', 'b', 'r', 0, 
	HB_P_POPVARIABLE, 1, 0,	/* CSERVER */
/* 00027 */ HB_P_LINEOFFSET, 1,	/* 211 */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'H', 'T', 'I', 's', 'i', 's', 't', 'e', 'm', 'a', 0, 
	HB_P_POPVARIABLE, 2, 0,	/* CUSER */
/* 00045 */ HB_P_LINEOFFSET, 2,	/* 212 */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'H', 'T', 'I', '5', '9', '2', '3', 0, 
	HB_P_POPVARIABLE, 3, 0,	/* CPASSWORD */
/* 00060 */ HB_P_LINEOFFSET, 3,	/* 213 */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'f', 't', 'p', ':', '/', '/', 0, 
	HB_P_PUSHVARIABLE, 2, 0,	/* CUSER */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	':', 0, 
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 3, 0,	/* CPASSWORD */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'@', 0, 
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 1, 0,	/* CSERVER */
	HB_P_PLUS,
	HB_P_POPVARIABLE, 50, 0,	/* CURL */
/* 00096 */ HB_P_LINEOFFSET, 4,	/* 214 */
	HB_P_MESSAGE, 29, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 30,	/* TURL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHVARIABLE, 50, 0,	/* CURL */
	HB_P_SENDSHORT, 1,
	HB_P_POPVARIABLE, 36, 0,	/* OURL */
/* 00114 */ HB_P_LINEOFFSET, 5,	/* 215 */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	's', 'a', 'c', 'c', 'f', 'g', '.', 'i', 'n', 'i', 0, 
	HB_P_POPVARIABLE, 51, 0,	/* CFILE */
/* 00132 */ HB_P_LINEOFFSET, 7,	/* 217 */
	HB_P_PUSHSYMNEAR, 52,	/* ALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 31,	/* 31 */
	'V', 'a', 'i', ' ', 't', 'e', 'n', 't', 'a', 'r', ' ', 'c', 'o', 'n', 'e', 'c', 't', 'a', 'r', ' ', 'c', 'o', 'm', ' ', 'F', 'T', 'P', '.', '.', '.', 0, 
	HB_P_DOSHORT, 1,
/* 00172 */ HB_P_LINEOFFSET, 8,	/* 218 */
	HB_P_PUSHSYMNEAR, 53,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 36, 0,	/* OURL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 63,	/* 63 (abs: 00245) */
/* 00184 */ HB_P_LINEOFFSET, 9,	/* 219 */
	HB_P_PUSHSYMNEAR, 52,	/* ALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 41,	/* 41 */
	'E', 'r', 'r', 'o', ' ', 'n', 'a', ' ', 'c', 'o', 'm', 'u', 'n', 'i', 'c', 'a', 'c', 'a', 'o', ' ', 'c', 'o', 'm', ' ', 'o', ' ', 's', 'e', 'r', 'v', 'i', 'd', 'o', 'r', ' ', 'F', 'T', 'P', ':', ' ', 0, 
	HB_P_PUSHVARIABLE, 50, 0,	/* CURL */
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
/* 00238 */ HB_P_LINEOFFSET, 10,	/* 220 */
	HB_P_PUSHSYMNEAR, 54,	/* __QUIT */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00245 */ HB_P_LINEOFFSET, 13,	/* 223 */
	HB_P_MESSAGE, 29, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 31,	/* TIPCLIENTFTP */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHVARIABLE, 36, 0,	/* OURL */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_SENDSHORT, 3,
	HB_P_POPVARIABLE, 55, 0,	/* OFTP */
/* 00265 */ HB_P_LINEOFFSET, 14,	/* 224 */
	HB_P_MESSAGE, 32, 0,	/* _NCONNTIMEOUT */
	HB_P_PUSHVARIABLE, 55, 0,	/* OFTP */
	HB_P_PUSHINT, 32, 78,	/* 20000 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00279 */ HB_P_LINEOFFSET, 16,	/* 226 */
	HB_P_PUSHSYMNEAR, 52,	/* ALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 21,	/* 21 */
	'I', 'n', 'i', 'c', 'i', 'a', 'l', 'i', 'z', 'a', 'n', 'd', 'o', ' ', 'F', 'T', 'P', '.', '.', '.', 0, 
	HB_P_DOSHORT, 1,
/* 00309 */ HB_P_LINEOFFSET, 17,	/* 227 */
	HB_P_PUSHSYMNEAR, 53,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 55, 0,	/* OFTP */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 16,	/* 16 (abs: 00336) */
	HB_P_PUSHSYMNEAR, 56,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 55, 0,	/* OFTP */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'U', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 8,	/* 8 (abs: 00345) */
	HB_P_PUSHVARIABLE, 55, 0,	/* OFTP */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 47,	/* 47 (abs: 00392) */
/* 00347 */ HB_P_LINEOFFSET, 18,	/* 228 */
	HB_P_PUSHSYMNEAR, 52,	/* ALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 29,	/* 29 */
	'E', 'r', 'r', 'o', ' ', 'n', 'a', ' ', 'i', 'n', 'i', 'c', 'i', 'a', 'l', 'i', 'z', 'a', 'c', 'a', 'o', ' ', 'd', 'o', ' ', 'F', 'T', 'P', 0, 
	HB_P_DOSHORT, 1,
/* 00385 */ HB_P_LINEOFFSET, 19,	/* 229 */
	HB_P_PUSHSYMNEAR, 54,	/* __QUIT */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00392 */ HB_P_LINEOFFSET, 22,	/* 232 */
	HB_P_PUSHSYMNEAR, 52,	/* ALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 41,	/* 41 */
	'T', 'e', 'n', 't', 'a', 'r', ' ', 'a', 'b', 'r', 'i', 'r', ' ', 'p', 'a', 'r', 'a', ' ', 'd', 'o', 'w', 'n', 'l', 'o', 'a', 'd', ' ', 'd', 'e', ' ', 'a', 'r', 'q', 'u', 'i', 'v', 'o', '.', '.', '.', 0, 
	HB_P_DOSHORT, 1,
/* 00442 */ HB_P_LINEOFFSET, 23,	/* 233 */
	HB_P_MESSAGE, 39, 0,	/* OPEN */
	HB_P_PUSHVARIABLE, 55, 0,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPFALSE, 172, 0,	/* 172 (abs: 00624) */
/* 00455 */ HB_P_LINEOFFSET, 24,	/* 234 */
	HB_P_MESSAGE, 57, 0,	/* CWD */
	HB_P_PUSHVARIABLE, 55, 0,	/* OFTP */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'v', 'e', 'r', 's', 'o', 'e', 's', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_JUMPTRUENEAR, 54,	/* 54 (abs: 00529) */
/* 00477 */ HB_P_LINEOFFSET, 25,	/* 235 */
	HB_P_PUSHSYMNEAR, 52,	/* ALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 36,	/* 36 */
	'E', 'r', 'r', 'o', ' ', 'n', 'a', ' ', 'm', 'u', 'd', 'a', 'n', 'c', 'a', ' ', 'd', 'e', ' ', 'd', 'i', 'r', 'e', 't', 'o', 'r', 'i', 'o', ' ', 'd', 'o', ' ', 'F', 'T', 'P', 0, 
	HB_P_DOSHORT, 1,
/* 00522 */ HB_P_LINEOFFSET, 26,	/* 236 */
	HB_P_PUSHSYMNEAR, 54,	/* __QUIT */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00529 */ HB_P_LINEOFFSET, 29,	/* 239 */
	HB_P_MESSAGE, 40, 0,	/* DOWNLOADFILE */
	HB_P_PUSHVARIABLE, 55, 0,	/* OFTP */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'p', 'a', 's', 't', 'a', '_', 'l', 'o', 'c', 'a', 'l', 0, 
	HB_P_PUSHVARIABLE, 51, 0,	/* CFILE */
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 51, 0,	/* CFILE */
	HB_P_SENDSHORT, 2,
	HB_P_JUMPTRUENEAR, 51,	/* 51 (abs: 00611) */
/* 00562 */ HB_P_LINEOFFSET, 30,	/* 240 */
	HB_P_PUSHSYMNEAR, 52,	/* ALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 18,	/* 18 */
	'E', 'r', 'r', 'o', ' ', 'n', 'o', ' ', 'd', 'o', 'w', 'n', 'l', 'o', 'a', 'd', ' ', 0, 
	HB_P_PUSHVARIABLE, 51, 0,	/* CFILE */
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
/* 00593 */ HB_P_LINEOFFSET, 31,	/* 241 */
	HB_P_MESSAGE, 41, 0,	/* CLOSE */
	HB_P_PUSHVARIABLE, 55, 0,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00604 */ HB_P_LINEOFFSET, 32,	/* 242 */
	HB_P_PUSHSYMNEAR, 54,	/* __QUIT */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00611 */ HB_P_LINEOFFSET, 34,	/* 244 */
	HB_P_MESSAGE, 41, 0,	/* CLOSE */
	HB_P_PUSHVARIABLE, 55, 0,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMPNEAR, 38,	/* 38 (abs: 00660) */
/* 00624 */ HB_P_LINEOFFSET, 36,	/* 246 */
	HB_P_PUSHSYMNEAR, 52,	/* ALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 20,	/* 20 */
	'E', 'r', 'r', 'o', ' ', 'p', 'a', 'r', 'a', ' ', 'a', 'b', 'r', 'i', 'r', ' ', 'F', 'T', 'P', 0, 
	HB_P_DOSHORT, 1,
/* 00653 */ HB_P_LINEOFFSET, 37,	/* 247 */
	HB_P_PUSHSYMNEAR, 54,	/* __QUIT */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00660 */ HB_P_LINEOFFSET, 39,	/* 249 */
	HB_P_PUSHSYMNEAR, 52,	/* ALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'D', 'o', 'w', 'n', 'l', 'o', 'a', 'd', ' ', 'O', 'K', 0, 
	HB_P_DOSHORT, 1,
/* 00681 */ HB_P_LINEOFFSET, 40,	/* 250 */
	HB_P_ENDPROC
/* 00684 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( TESTE_FTP )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 0, 1,	/* 256 */
	HB_P_LOCALNEARSETSTR, 3, 48, 0,	/* CUSBSTICK 48*/
	'f', 't', 'p', ':', '/', '/', 'H', 'T', 'I', 's', 'i', 's', 't', 'e', 'm', 'a', ':', 'H', 'T', 'I', '5', '9', '2', '3', '@', 'f', 't', 'p', '.', 'H', 'T', 'I', 's', 'i', 's', 't', 'e', 'm', 'a', 's', '.', 'c', 'o', 'm', '.', 'b', 'r', 0, 
/* 00058 */ HB_P_LINEOFFSET, 2,	/* 258 */
	HB_P_MESSAGE, 29, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 31,	/* TIPCLIENTFTP */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 3,	/* CUSBSTICK */
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 1,	/* OFTP */
/* 00074 */ HB_P_LINEOFFSET, 4,	/* 260 */
	HB_P_MESSAGE, 39, 0,	/* OPEN */
	HB_P_PUSHLOCALNEAR, 1,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPTRUENEAR, 69,	/* 69 (abs: 00152) */
/* 00085 */ HB_P_LINEOFFSET, 5,	/* 261 */
	HB_P_PUSHSYMNEAR, 25,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 47,	/* 47 */
	'E', 'r', 'r', 'o', ' ', 'd', 'e', ' ', 'C', 'o', 'n', 'e', 'x', 227, 'o', ' ', 'F', 'T', 'P', '!', ' ', 'V', 'e', 'r', 'i', 'f', 'i', 'q', 'u', 'e', ' ', 's', 'u', 'a', ' ', 'i', 'n', 't', 'e', 'r', 'n', 'e', 't', '!', '!', '!', 0, 
	HB_P_MESSAGE, 59, 0,	/* LASTERRORMESSAGE */
	HB_P_PUSHLOCALNEAR, 1,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
/* 00149 */ HB_P_LINEOFFSET, 6,	/* 262 */
	HB_P_ENDPROC,
/* 00152 */ HB_P_LINEOFFSET, 10,	/* 266 */
	HB_P_MESSAGE, 40, 0,	/* DOWNLOADFILE */
	HB_P_PUSHLOCALNEAR, 1,	/* OFTP */
	HB_P_PUSHSTRSHORT, 26,	/* 26 */
	'/', 'w', 'e', 'b', '/', 'd', 'o', 'w', 'n', 'l', 'o', 'a', 'd', 's', '/', 's', 'a', 'c', 'c', 'f', 'g', '.', 'i', 'n', 'i', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00190 */ HB_P_LINEOFFSET, 11,	/* 267 */
	HB_P_MESSAGE, 44, 0,	/* CREPLY */
	HB_P_PUSHLOCALNEAR, 1,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_POPVARIABLE, 60, 0,	/* WRETORNO */
/* 00202 */ HB_P_LINEOFFSET, 12,	/* 268 */
	HB_P_PUSHSYMNEAR, 56,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 60, 0,	/* WRETORNO */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'U', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 71,	/* 71 (abs: 00288) */
/* 00219 */ HB_P_LINEOFFSET, 13,	/* 269 */
	HB_P_PUSHSYMNEAR, 61,	/* FERASE */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 62, 0,	/* VARQCLIZIP */
	HB_P_DOSHORT, 1,
/* 00229 */ HB_P_LINEOFFSET, 14,	/* 270 */
	HB_P_PUSHSYMNEAR, 25,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 48,	/* 48 */
	'I', 'm', 'p', 'o', 's', 's', 'i', 'b', 'i', 'l', 'i', 'd', 'a', 'd', 'e', ' ', 'd', 'e', ' ', 'c', 'o', 'n', 't', 'i', 'n', 'u', 'a', 'r', ',', ' ', 'c', 'o', 'n', 'e', 'x', 227, 'o', ' ', 'f', 'a', 'l', 'h', 'o', 'u', '!', '!', '!', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 108,	/* 108 (abs: 00394) */
/* 00288 */ HB_P_LINEOFFSET, 17,	/* 273 */
	HB_P_PUSHSYMNEAR, 21,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 60, 0,	/* WRETORNO */
	HB_P_ONE,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'2', '2', '6', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 42,	/* 42 (abs: 00350) */
/* 00310 */ HB_P_LINEOFFSET, 18,	/* 274 */
	HB_P_MESSAGE, 63, 0,	/* DELE */
	HB_P_PUSHLOCALNEAR, 1,	/* OFTP */
	HB_P_PUSHSTRSHORT, 26,	/* 26 */
	'/', 'w', 'e', 'b', '/', 'd', 'o', 'w', 'n', 'l', 'o', 'a', 'd', 's', '/', 's', 'a', 'c', 'c', 'f', 'g', '.', 'i', 'n', 'i', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 46,	/* 46 (abs: 00394) */
/* 00350 */ HB_P_LINEOFFSET, 20,	/* 276 */
	HB_P_PUSHSYMNEAR, 21,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 60, 0,	/* WRETORNO */
	HB_P_ONE,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'5', '5', '0', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 4,	/* 4 (abs: 00374) */
	HB_P_JUMPNEAR, 22,	/* 22 (abs: 00394) */
/* 00374 */ HB_P_LINEOFFSET, 23,	/* 279 */
	HB_P_PUSHSYMNEAR, 25,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'E', 'r', 'r', 'o', '-', '>', 0, 
	HB_P_PUSHVARIABLE, 60, 0,	/* WRETORNO */
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
/* 00394 */ HB_P_LINEOFFSET, 27,	/* 283 */
	HB_P_MESSAGE, 41, 0,	/* CLOSE */
	HB_P_PUSHLOCALNEAR, 1,	/* OFTP */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_ENDPROC
/* 00405 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

