/*
 * xHarbour build 0.99.70 Intl. (SimpLex)
 * Generated C source code from <SACEXP2.PRG>
 * Command: C:\xHarbour997\bin\harbour.exe C:\hti\SISCOM\SACEXP2.PRG /q /oC:\hti\SISCOM\SACEXP2.c /M /N -DxHB -DXHB_0990 -DXHB_0991 -DXHB_0992 -DXHB_0993 -DXHB_0994 -DXHB_09941 -DXHB_09950 -DXHB_09951a -DXHB_09951 -DXHB_09951b -DXHB_0996 -DXHB_09960 -DXHB_09961 -DXHB_09961B -DXHB_0997 -DXHB_09970 
 * Created: 2023.09.29 11:53:10 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "SACEXP2.PRG"

HB_FUNC( SACEXP2 );
HB_FUNC_EXTERN( __MVPRIVATE );
HB_FUNC_EXTERN( VER_NIVEL );
HB_FUNC_EXTERN( SAVESCREEN );
HB_FUNC_EXTERN( ABRIARQ );
HB_FUNC_EXTERN( SPACE );
HB_FUNC_EXTERN( READKILL );
HB_FUNC_EXTERN( OP_TELA );
HB_FUNC_EXTERN( EXIBI_PRG );
HB_FUNC_EXTERN( DISPBOX );
HB_FUNC_EXTERN( DEVPOS );
HB_FUNC_EXTERN( DEVOUT );
HB_FUNC_EXTERN( SETPOS );
HB_FUNC_EXTERN( AADD );
HB_FUNC_EXTERN( __GET );
HB_FUNC_EXTERN( VER_EMP );
HB_FUNC_EXTERN( READMODAL );
HB_FUNC_EXTERN( DBSELECTAREA );
HB_FUNC_EXTERN( ORDSETFOCUS );
HB_FUNC_EXTERN( DBGOTOP );
HB_FUNC_EXTERN( DBSEEK );
HB_FUNC_EXTERN( ATENCAO );
HB_FUNC_EXTERN( RESTSCREEN );
HB_FUNC_EXTERN( WVW_LCLOSEWINDOW );
HB_FUNC_EXTERN( MENSAGEM );
HB_FUNC_EXTERN( ASIZE );
HB_FUNC_EXTERN( EOF );
HB_FUNC_EXTERN( EMPTY );
HB_FUNC_EXTERN( DBSKIP );
HB_FUNC_EXTERN( RECNO );
HB_FUNC_EXTERN( DTOC );
HB_FUNC_EXTERN( TRANSFORM );
HB_FUNC_EXTERN( LEN );
HB_FUNC_EXTERN( LASTKEY );
HB_FUNC_EXTERN( SETCOR );
HB_FUNC_EXTERN( ACHOICE );
HB_FUNC_EXTERN( DBGOTO );
HB_FUNC_EXTERN( VAL );
HB_FUNC_EXTERN( MENSAGEM1 );
HB_FUNC_EXTERN( ASC );
HB_FUNC_EXTERN( SAC5PED1 );
HB_FUNC_EXTERN( SAC23PD1 );
HB_FUNC_EXTERN( STRZERO );
HB_FUNC_EXTERN( BLOQREG );
HB_FUNC_EXTERN( DBUNLOCKALL );
HB_FUNC_EXTERN( DBCOMMITALL );
HB_FUNC_EXTERN( CTOD );
HB_FUNC_EXTERN( DBUNLOCK );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 7

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_SACEXP2 )
{ "SACEXP2", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( SACEXP2 )}, NULL },
{ "MCOD_CLI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MNUM_PED", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "M_POSICAO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "POINT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTOT_PED", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MALI_PED", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MALI_CON", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__MVPRIVATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPRIVATE )}, NULL },
{ "VER_NIVEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( VER_NIVEL )}, NULL },
{ "NIVEL_ACESS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SAVESCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAVESCREEN )}, NULL },
{ "ABRIARQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( ABRIARQ )}, NULL },
{ "SPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPACE )}, NULL },
{ "READKILL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READKILL )}, NULL },
{ "GETLIST", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OP_TELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_TELA )}, NULL },
{ "EXIBI_PRG", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXIBI_PRG )}, NULL },
{ "DISPBOX", {HB_FS_PUBLIC}, {HB_FUNCNAME( DISPBOX )}, NULL },
{ "DEVPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVPOS )}, NULL },
{ "DEVOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUT )}, NULL },
{ "MMULT_EMP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MCODEMPRESA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SETPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETPOS )}, NULL },
{ "AADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADD )}, NULL },
{ "__GET", {HB_FS_PUBLIC}, {HB_FUNCNAME( __GET )}, NULL },
{ "VER_EMP", {HB_FS_PUBLIC}, {HB_FUNCNAME( VER_EMP )}, NULL },
{ "DISPLAY", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "READMODAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READMODAL )}, NULL },
{ "DBSELECTAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSELECTAREA )}, NULL },
{ "ORDSETFOCUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ORDSETFOCUS )}, NULL },
{ "DBGOTOP", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBGOTOP )}, NULL },
{ "DBSEEK", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSEEK )}, NULL },
{ "ATENCAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATENCAO )}, NULL },
{ "RESTSCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( RESTSCREEN )}, NULL },
{ "WVW_LCLOSEWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_LCLOSEWINDOW )}, NULL },
{ "MENSAGEM", {HB_FS_PUBLIC}, {HB_FUNCNAME( MENSAGEM )}, NULL },
{ "ASIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ASIZE )}, NULL },
{ "EOF", {HB_FS_PUBLIC}, {HB_FUNCNAME( EOF )}, NULL },
{ "PPAG", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "EMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EMPTY )}, NULL },
{ "PEMPRESA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PLIB_POR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PEXP_POR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PEXP_DAT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DBSKIP", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSKIP )}, NULL },
{ "PNUM_PED", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PCOD_VEND", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PLIB_DAT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PDAT_PED", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PHORA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PTP_VEND", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "RECNO", {HB_FS_PUBLIC}, {HB_FUNCNAME( RECNO )}, NULL },
{ "PCOD_CLI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PQUANTD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PVLR_FAT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DTOC", {HB_FS_PUBLIC}, {HB_FUNCNAME( DTOC )}, NULL },
{ "TRANSFORM", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRANSFORM )}, NULL },
{ "LEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( LEN )}, NULL },
{ "LASTKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( LASTKEY )}, NULL },
{ "SETCOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETCOR )}, NULL },
{ "ACHOICE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ACHOICE )}, NULL },
{ "DBGOTO", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBGOTO )}, NULL },
{ "VAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( VAL )}, NULL },
{ "MENSAGEM1", {HB_FS_PUBLIC}, {HB_FUNCNAME( MENSAGEM1 )}, NULL },
{ "ASC", {HB_FS_PUBLIC}, {HB_FUNCNAME( ASC )}, NULL },
{ "SAC5PED1", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAC5PED1 )}, NULL },
{ "SAC23PD1", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAC23PD1 )}, NULL },
{ "STRZERO", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRZERO )}, NULL },
{ "BLOQREG", {HB_FS_PUBLIC}, {HB_FUNCNAME( BLOQREG )}, NULL },
{ "PEXPEDI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "COD_OPERADO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MDATA_SIS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DBUNLOCKALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBUNLOCKALL )}, NULL },
{ "DBCOMMITALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCOMMITALL )}, NULL },
{ "CTOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTOD )}, NULL },
{ "EXPEDI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "EXP_POR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "EXP_DAT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LIB_POR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LIB_DAT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LIB_VLR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DBUNLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBUNLOCK )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_SACEXP2 )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_SACEXP2
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_SACEXP2 = hb_vm_SymbolInit_SACEXP2;
   #pragma data_seg()
#endif

HB_FUNC( SACEXP2 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 23, 2,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 9, 0,	/* 9 */
	HB_P_LOCALNEARSETSTR, 3, 8, 0,	/* MPRG 8*/
	'S', 'A', 'C', 'E', 'X', 'P', '2', 0, 
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 14,	/* M_CODIGO */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 25,	/* M_PEDIDO */
/* 00028 */ HB_P_LINEOFFSET, 2,	/* 11 */
	HB_P_ZERO,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_ZERO,
	HB_P_PUSHSYMNEAR, 8,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 1,	/* MCOD_CLI */
	HB_P_PUSHSYMNEAR, 2,	/* MNUM_PED */
	HB_P_PUSHSYMNEAR, 3,	/* M_POSICAO */
	HB_P_PUSHSYMNEAR, 4,	/* POINT */
	HB_P_PUSHSYMNEAR, 5,	/* MTOT_PED */
	HB_P_PUSHSYMNEAR, 6,	/* MALI_PED */
	HB_P_PUSHSYMNEAR, 7,	/* MALI_CON */
	HB_P_DOSHORT, 7,
	HB_P_POPVARIABLE, 5, 0,	/* MTOT_PED */
	HB_P_POPVARIABLE, 3, 0,	/* M_POSICAO */
	HB_P_POPVARIABLE, 2, 0,	/* MNUM_PED */
/* 00063 */ HB_P_LINEOFFSET, 4,	/* 13 */
	HB_P_PUSHLOCALNEAR, 1,	/* MTP */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 93,	/* 93 (abs: 00162) */
/* 00071 */ HB_P_LINEOFFSET, 5,	/* 14 */
	HB_P_LOCALNEARSETSTR, 4, 21, 0,	/* MTITULO 21*/
	'E', 'X', 'P', 'E', 'D', 'I', 'C', 'A', 'O', ' ', 'D', 'E', ' ', 'P', 'E', 'D', 'I', 'D', 'O', 'S', 0, 
/* 00098 */ HB_P_LINEOFFSET, 6,	/* 15 */
	HB_P_PUSHSYMNEAR, 9,	/* VER_NIVEL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MPRG */
	HB_P_PUSHLOCALNEAR, 4,	/* MTITULO */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'1', '5', 0, 
	HB_P_PUSHVARIABLE, 10, 0,	/* NIVEL_ACESS */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'A', 'M', 'B', 'I', 'E', 0, 
	HB_P_FUNCTIONSHORT, 6,
	HB_P_JUMPTRUENEAR, 7,	/* 7 (abs: 00133) */
/* 00128 */ HB_P_LINEOFFSET, 7,	/* 16 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00133 */ HB_P_LINEOFFSET, 9,	/* 18 */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'p', 'e', 'd', '_', 's', 0, 
	HB_P_POPVARIABLE, 6, 0,	/* MALI_PED */
/* 00146 */ HB_P_LINEOFFSET, 10,	/* 19 */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'p', 'e', 'd', '_', 'c', 0, 
	HB_P_POPVARIABLE, 7, 0,	/* MALI_CON */
	HB_P_JUMP, 233, 0,	/* 233 (abs: 00392) */
/* 00162 */ HB_P_LINEOFFSET, 12,	/* 21 */
	HB_P_PUSHLOCALNEAR, 2,	/* MPED_ORC */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'P', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 111,	/* 111 (abs: 00282) */
/* 00173 */ HB_P_LINEOFFSET, 13,	/* 22 */
	HB_P_LOCALNEARSETSTR, 4, 29, 0,	/* MTITULO 29*/
	'E', 'S', 'T', 'O', 'R', 'N', 'O', ' ', 'D', 'E', ' ', 'P', 'E', 'D', 'I', 'D', 'O', 'S', ' ', 'L', 'I', 'B', 'E', 'R', 'A', 'D', 'O', 'S', 0, 
/* 00208 */ HB_P_LINEOFFSET, 14,	/* 23 */
	HB_P_PUSHLOCALNEAR, 3,	/* MPRG */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'E', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 3,	/* MPRG */
/* 00219 */ HB_P_LINEOFFSET, 15,	/* 24 */
	HB_P_PUSHSYMNEAR, 9,	/* VER_NIVEL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MPRG */
	HB_P_PUSHLOCALNEAR, 4,	/* MTITULO */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'1', '5', 0, 
	HB_P_PUSHVARIABLE, 10, 0,	/* NIVEL_ACESS */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'A', 'M', 'B', 'I', 'E', 0, 
	HB_P_FUNCTIONSHORT, 6,
	HB_P_JUMPTRUENEAR, 7,	/* 7 (abs: 00254) */
/* 00249 */ HB_P_LINEOFFSET, 16,	/* 25 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00254 */ HB_P_LINEOFFSET, 18,	/* 27 */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'p', 'e', 'd', '_', 's', 0, 
	HB_P_POPVARIABLE, 6, 0,	/* MALI_PED */
/* 00267 */ HB_P_LINEOFFSET, 19,	/* 28 */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'p', 'e', 'd', '_', 'c', 0, 
	HB_P_POPVARIABLE, 7, 0,	/* MALI_CON */
	HB_P_JUMPNEAR, 112,	/* 112 (abs: 00392) */
/* 00282 */ HB_P_LINEOFFSET, 21,	/* 30 */
	HB_P_LOCALNEARSETSTR, 4, 31, 0,	/* MTITULO 31*/
	'E', 'S', 'T', 'O', 'R', 'N', 'O', ' ', 'D', 'E', ' ', 'O', 'R', 'C', 'A', 'M', 'E', 'N', 'T', 'O', ' ', 'L', 'I', 'B', 'E', 'R', 'A', 'D', 'O', 'S', 0, 
/* 00319 */ HB_P_LINEOFFSET, 22,	/* 31 */
	HB_P_PUSHLOCALNEAR, 3,	/* MPRG */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'E', 'O', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 3,	/* MPRG */
/* 00331 */ HB_P_LINEOFFSET, 23,	/* 32 */
	HB_P_PUSHSYMNEAR, 9,	/* VER_NIVEL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MPRG */
	HB_P_PUSHLOCALNEAR, 4,	/* MTITULO */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'1', '5', 0, 
	HB_P_PUSHVARIABLE, 10, 0,	/* NIVEL_ACESS */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'A', 'M', 'B', 'I', 'E', 0, 
	HB_P_FUNCTIONSHORT, 6,
	HB_P_JUMPTRUENEAR, 7,	/* 7 (abs: 00366) */
/* 00361 */ HB_P_LINEOFFSET, 24,	/* 33 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00366 */ HB_P_LINEOFFSET, 26,	/* 35 */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'o', 'r', 'c', 'a', 'm', 0, 
	HB_P_POPVARIABLE, 6, 0,	/* MALI_PED */
/* 00379 */ HB_P_LINEOFFSET, 27,	/* 36 */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'o', 'r', 'c', '_', 'c', 0, 
	HB_P_POPVARIABLE, 7, 0,	/* MALI_CON */
/* 00392 */ HB_P_LINEOFFSET, 31,	/* 40 */
	HB_P_LOCALNEARSETINT, 8, 0, 0,	/* CCI 0*/
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_POPLOCALNEAR, 7,	/* LCI */
/* 00402 */ HB_P_LINEOFFSET, 32,	/* 41 */
	HB_P_LOCALNEARSETINT, 9, 22, 0,	/* LBA 22*/
/* 00408 */ HB_P_LINEOFFSET, 33,	/* 42 */
	HB_P_LOCALNEARSETINT, 10, 77, 0,	/* CBA 77*/
/* 00414 */ HB_P_LINEOFFSET, 35,	/* 44 */
	HB_P_PUSHSYMNEAR, 11,	/* SAVESCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 5,	/* TELA */
/* 00429 */ HB_P_LINEOFFSET, 37,	/* 46 */
	HB_P_PUSHSYMNEAR, 12,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	's', 'a', 'c', 'p', 'e', 'd', '_', 's', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'p', 'e', 'd', '_', 's', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 00460) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00460 */ HB_P_LINEOFFSET, 38,	/* 47 */
	HB_P_PUSHSYMNEAR, 12,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	's', 'a', 'c', 'p', 'e', 'd', '_', 'c', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'p', 'e', 'd', '_', 'c', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 00491) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00491 */ HB_P_LINEOFFSET, 39,	/* 48 */
	HB_P_PUSHSYMNEAR, 12,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	's', 'a', 'c', 'o', 'r', 'c', 'a', 'm', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'o', 'r', 'c', 'a', 'm', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 00522) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00522 */ HB_P_LINEOFFSET, 40,	/* 49 */
	HB_P_PUSHSYMNEAR, 12,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	's', 'a', 'c', 'o', 'r', 'c', '_', 'c', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'o', 'r', 'c', '_', 'c', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 00553) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00553 */ HB_P_LINEOFFSET, 41,	/* 50 */
	HB_P_PUSHSYMNEAR, 12,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	's', 'a', 'c', 'm', 'e', 'r', 'c', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'm', 'e', 'r', 'c', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 00582) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00582 */ HB_P_LINEOFFSET, 42,	/* 51 */
	HB_P_PUSHSYMNEAR, 12,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	's', 'a', 'c', 'c', 'a', 'i', 'x', 'a', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'c', 'a', 'i', 'x', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 00612) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00612 */ HB_P_LINEOFFSET, 44,	/* 53 */
	HB_P_PUSHSYMNEAR, 13,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 12,	/* MNUM_PEDIDO */
/* 00623 */ HB_P_LINEOFFSET, 45,	/* 54 */
	HB_P_PUSHSYMNEAR, 14,	/* READKILL */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_DOSHORT, 1,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 15, 0,	/* GETLIST */
/* 00637 */ HB_P_LINEOFFSET, 46,	/* 55 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 4, 0,	/* POINT */
/* 00643 */ HB_P_LINEOFFSET, 47,	/* 56 */
	HB_P_PUSHLOCALNEAR, 2,	/* MPED_ORC */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'P', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 83,	/* 83 (abs: 00735) */
/* 00654 */ HB_P_LINEOFFSET, 48,	/* 57 */
	HB_P_PUSHSYMNEAR, 16,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_PUSHLOCALNEAR, 1,	/* MTP */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 29,	/* 29 (abs: 00698) */
	HB_P_PUSHSTRSHORT, 23,	/* 23 */
	' ', 'E', 'X', 'P', 'E', 'D', 'I', 'C', 'A', 'O', ' ', 'D', 'E', ' ', 'P', 'E', 'D', 'I', 'D', 'O', 'S', ' ', 0, 
	HB_P_JUMPNEAR, 35,	/* 35 (abs: 00731) */
	HB_P_PUSHSTRSHORT, 31,	/* 31 */
	' ', 'E', 'S', 'T', 'O', 'R', 'N', 'O', ' ', 'D', 'E', ' ', 'P', 'E', 'D', 'I', 'D', 'O', 'S', ' ', 'L', 'I', 'B', 'E', 'R', 'A', 'D', 'O', 'S', ' ', 0, 
	HB_P_DOSHORT, 5,
	HB_P_JUMPNEAR, 84,	/* 84 (abs: 00817) */
/* 00735 */ HB_P_LINEOFFSET, 50,	/* 59 */
	HB_P_PUSHSYMNEAR, 16,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_PUSHLOCALNEAR, 1,	/* MTP */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 29,	/* 29 (abs: 00779) */
	HB_P_PUSHSTRSHORT, 23,	/* 23 */
	' ', 'E', 'X', 'P', 'E', 'D', 'I', 'C', 'A', 'O', ' ', 'D', 'E', ' ', 'P', 'E', 'D', 'I', 'D', 'O', 'S', ' ', 0, 
	HB_P_JUMPNEAR, 38,	/* 38 (abs: 00815) */
	HB_P_PUSHSTRSHORT, 34,	/* 34 */
	' ', 'E', 'S', 'T', 'O', 'R', 'N', 'O', ' ', 'D', 'E', ' ', 'O', 'R', 'C', 'A', 'M', 'E', 'N', 'T', 'O', 'S', ' ', 'L', 'I', 'B', 'E', 'R', 'A', 'D', 'O', 'S', ' ', 0, 
	HB_P_DOSHORT, 5,
/* 00817 */ HB_P_LINEOFFSET, 53,	/* 62 */
	HB_P_PUSHSYMNEAR, 17,	/* EXIBI_PRG */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MPRG */
	HB_P_DOSHORT, 1,
/* 00826 */ HB_P_LINEOFFSET, 54,	/* 63 */
	HB_P_LOCALNEARSETSTR, 24, 4, 0,	/* MCODEMP 4*/
	' ', ' ', ' ', 0, 
/* 00836 */ HB_P_LINEOFFSET, 55,	/* 64 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 5, 0,	/* MTOT_PED */
/* 00842 */ HB_P_LINEOFFSET, 56,	/* 65 */
	HB_P_PUSHSYMNEAR, 18,	/* DISPBOX */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 10,	/* CBA */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_ONE,
	HB_P_DOSHORT, 5,
/* 00870 */ HB_P_LINEOFFSET, 57,	/* 66 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	' ', 'N', 'o', '.', 'P', 'e', 'd', ' ', 0, 
	HB_P_DOSHORT, 1,
/* 00903 */ HB_P_LINEOFFSET, 58,	/* 67 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_ADDINT, 10, 0,	/* 10*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'C', 'd', '.', 'C', 'l', 'i', ' ', 0, 
	HB_P_DOSHORT, 1,
/* 00935 */ HB_P_LINEOFFSET, 59,	/* 68 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_ADDINT, 17, 0,	/* 17*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'V', 'e', 'n', 'd', ' ', 0, 
	HB_P_DOSHORT, 1,
/* 00965 */ HB_P_LINEOFFSET, 60,	/* 69 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_ADDINT, 21, 0,	/* 21*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	' ', ' ', ' ', 'D', 'a', 't', 'a', ' ', ' ', ' ', 0, 
	HB_P_DOSHORT, 1,
/* 01000 */ HB_P_LINEOFFSET, 61,	/* 70 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_ADDINT, 32, 0,	/* 32*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', ' ', ' ', ' ', 'V', 'a', 'l', 'o', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 01034 */ HB_P_LINEOFFSET, 62,	/* 71 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_ADDINT, 47, 0,	/* 47*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'T', 'p', 0, 
	HB_P_DOSHORT, 1,
/* 01061 */ HB_P_LINEOFFSET, 63,	/* 72 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_ADDINT, 51, 0,	/* 51*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'L', 'i', 'b', '.', 0, 
	HB_P_DOSHORT, 1,
/* 01090 */ HB_P_LINEOFFSET, 64,	/* 73 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_ADDINT, 55, 0,	/* 55*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	' ', 'D', 'a', 't', 'a', ' ', 'L', 'i', 'b', '.', 0, 
	HB_P_DOSHORT, 1,
/* 01125 */ HB_P_LINEOFFSET, 65,	/* 74 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_ADDINT, 67, 0,	/* 67*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'E', 'm', 'p', '.', 0, 
	HB_P_DOSHORT, 1,
/* 01154 */ HB_P_LINEOFFSET, 66,	/* 75 */
	HB_P_PUSHVARIABLE, 21, 0,	/* MMULT_EMP */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 167, 0,	/* 167 (abs: 01331) */
/* 01167 */ HB_P_LINEOFFSET, 67,	/* 76 */
	HB_P_PUSHVARIABLE, 22, 0,	/* MCODEMPRESA */
	HB_P_POPLOCALNEAR, 24,	/* MCODEMP */
/* 01174 */ HB_P_LINEOFFSET, 68,	/* 77 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'E', 'm', 'p', 'r', 'e', 's', 'a', ':', 0, 
	HB_P_DOSHORT, 1,
/* 01204 */ HB_P_LINEOFFSET, 69,	/* 78 */
	HB_P_PUSHSYMNEAR, 23,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_ADDINT, 10, 0,	/* 10*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 24,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 15, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 25,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	24, 0,	/* MCODEMP */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 01246) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 01251) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'm', 'c', 'o', 'd', 'e', 'm', 'p', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'9', '9', '9', 0, 
	HB_P_PUSHBLOCK, 24, 0,	/* 24 */
	0, 0,	/* number of local parameters (0) */
	1, 0,	/* number of local variables (1) */
	24, 0,	/* MCODEMP */
	HB_P_PUSHSYMNEAR, 26,	/* VER_EMP */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_FUNCTIONSHORT, 5,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 27, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 15, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 01309 */ HB_P_LINEOFFSET, 70,	/* 79 */
	HB_P_PUSHSYMNEAR, 28,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 15, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 15, 0,	/* GETLIST */
/* 01331 */ HB_P_LINEOFFSET, 73,	/* 82 */
	HB_P_PUSHSYMNEAR, 29,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 30,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 01348 */ HB_P_LINEOFFSET, 74,	/* 83 */
	HB_P_PUSHSYMNEAR, 31,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01355 */ HB_P_LINEOFFSET, 76,	/* 85 */
	HB_P_PUSHALIAS,
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 32,	/* DBSEEK */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_SWAPALIAS,
	HB_P_JUMPTRUENEAR, 78,	/* 78 (abs: 01450) */
/* 01374 */ HB_P_LINEOFFSET, 77,	/* 86 */
	HB_P_PUSHSYMNEAR, 33,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 40,	/* 40 */
	'N', 'a', 'o', ' ', 'e', 'x', 'i', 's', 't', 'e', ' ', 'n', 'e', 'n', 'h', 'u', 'm', 'a', ' ', 'P', 'e', 'd', 'i', 'd', 'o', ' ', 'p', '/', 'L', 'i', 'b', 'e', 'r', 'a', 'r', ' ', '!', '!', '!', 0, 
	HB_P_DOSHORT, 1,
/* 01423 */ HB_P_LINEOFFSET, 78,	/* 87 */
	HB_P_PUSHSYMNEAR, 34,	/* RESTSCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_PUSHLOCALNEAR, 5,	/* TELA */
	HB_P_DOSHORT, 5,
/* 01438 */ HB_P_LINEOFFSET, 79,	/* 88 */
	HB_P_PUSHSYMNEAR, 35,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01445 */ HB_P_LINEOFFSET, 80,	/* 89 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 01450 */ HB_P_LINEOFFSET, 82,	/* 91 */
	HB_P_PUSHSYMNEAR, 36,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 26,	/* 26 */
	'A', 'g', 'u', 'a', 'r', 'd', 'e', ' ', 'u', 'm', ' ', 'm', 'o', 'm', 'e', 'n', 't', 'o', ' ', 'O', 'K', ' ', '!', '!', '!', 0, 
	HB_P_DOSHORT, 1,
/* 01485 */ HB_P_LINEOFFSET, 83,	/* 92 */
	HB_P_PUSHSYMNEAR, 37,	/* ASIZE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 25,	/* M_PEDIDO */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
/* 01495 */ HB_P_LINEOFFSET, 84,	/* 93 */
	HB_P_PUSHSYMNEAR, 37,	/* ASIZE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 14,	/* M_CODIGO */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
/* 01505 */ HB_P_LINEOFFSET, 85,	/* 94 */
	HB_P_PUSHSYMNEAR, 37,	/* ASIZE */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 3, 0,	/* M_POSICAO */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
/* 01516 */ HB_P_LINEOFFSET, 86,	/* 95 */
	HB_P_FALSE,
	HB_P_PUSHSYMNEAR, 38,	/* EOF */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPTRUENEAR, 14,	/* 14 (abs: 01538) */
	HB_P_POP,
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 39, 0,	/* PPAG */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 138, 1,	/* 394 (abs: 01932) */
/* 01541 */ HB_P_LINEOFFSET, 90,	/* 99 */
	HB_P_FALSE,
	HB_P_PUSHSYMNEAR, 40,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 24,	/* MCODEMP */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 12,	/* 12 (abs: 01563) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 24,	/* MCODEMP */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 41, 0,	/* PEMPRESA */
	HB_P_NOTEQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 14,	/* 14 (abs: 01578) */
	HB_P_PUSHSYMNEAR, 40,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 42, 0,	/* PLIB_POR */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 15,	/* 15 (abs: 01594) */
	HB_P_PUSHSYMNEAR, 40,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 43, 0,	/* PEXP_POR */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 15,	/* 15 (abs: 01610) */
	HB_P_PUSHSYMNEAR, 40,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 44, 0,	/* PEXP_DAT */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 12,	/* 12 (abs: 01622) */
/* 01612 */ HB_P_LINEOFFSET, 91,	/* 100 */
	HB_P_PUSHSYMNEAR, 45,	/* DBSKIP */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 152,	/* -104 (abs: 01516) */
/* 01622 */ HB_P_LINEOFFSET, 94,	/* 103 */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 46, 0,	/* PNUM_PED */
	HB_P_POPLOCALNEAR, 12,	/* MNUM_PEDIDO */
/* 01632 */ HB_P_LINEOFFSET, 95,	/* 104 */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 47, 0,	/* PCOD_VEND */
	HB_P_POPLOCALNEAR, 16,	/* MCOD_VEND */
/* 01642 */ HB_P_LINEOFFSET, 96,	/* 105 */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 42, 0,	/* PLIB_POR */
	HB_P_POPLOCALNEAR, 22,	/* MCOD_OP */
/* 01652 */ HB_P_LINEOFFSET, 97,	/* 106 */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 48, 0,	/* PLIB_DAT */
	HB_P_POPLOCALNEAR, 19,	/* MDATA_LIB */
/* 01662 */ HB_P_LINEOFFSET, 98,	/* 107 */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 49, 0,	/* PDAT_PED */
	HB_P_POPLOCALNEAR, 17,	/* MDATA_PED */
/* 01672 */ HB_P_LINEOFFSET, 99,	/* 108 */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 50, 0,	/* PHORA */
	HB_P_POPLOCALNEAR, 20,	/* MHORA */
/* 01682 */ HB_P_LINEOFFSET, 100,	/* 109 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 5, 0,	/* MTOT_PED */
/* 01688 */ HB_P_LINEOFFSET, 101,	/* 110 */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 51, 0,	/* PTP_VEND */
	HB_P_POPLOCALNEAR, 21,	/* MTIPO_VENDA */
/* 01698 */ HB_P_LINEOFFSET, 102,	/* 111 */
	HB_P_PUSHSYMNEAR, 52,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_POPLOCALNEAR, 18,	/* MPOSICAO */
/* 01707 */ HB_P_LINEOFFSET, 103,	/* 112 */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 53, 0,	/* PCOD_CLI */
	HB_P_POPVARIABLE, 1, 0,	/* MCOD_CLI */
/* 01718 */ HB_P_LINEOFFSET, 104,	/* 113 */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 41, 0,	/* PEMPRESA */
	HB_P_POPLOCALNEAR, 23,	/* MCOD_EMP */
/* 01728 */ HB_P_LINEOFFSET, 105,	/* 114 */
	HB_P_FALSE,
	HB_P_PUSHLOCALNEAR, 12,	/* MNUM_PEDIDO */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 46, 0,	/* PNUM_PED */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 01749) */
	HB_P_POP,
	HB_P_PUSHSYMNEAR, 38,	/* EOF */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 34,	/* 34 (abs: 01783) */
/* 01751 */ HB_P_LINEOFFSET, 106,	/* 115 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MTOT_PED */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 54, 0,	/* PQUANTD */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 55, 0,	/* PVLR_FAT */
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_POPVARIABLE, 5, 0,	/* MTOT_PED */
/* 01773 */ HB_P_LINEOFFSET, 107,	/* 116 */
	HB_P_PUSHSYMNEAR, 45,	/* DBSKIP */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 203,	/* -53 (abs: 01728) */
/* 01783 */ HB_P_LINEOFFSET, 109,	/* 118 */
	HB_P_PUSHSYMNEAR, 24,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 25,	/* M_PEDIDO */
	HB_P_PUSHVARIABLE, 5, 0,	/* MTOT_PED */
	HB_P_DOSHORT, 2,
/* 01795 */ HB_P_LINEOFFSET, 110,	/* 119 */
	HB_P_PUSHSYMNEAR, 24,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 14,	/* M_CODIGO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PUSHLOCALNEAR, 12,	/* MNUM_PEDIDO */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	' ', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 1, 0,	/* MCOD_CLI */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	' ', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 16,	/* MCOD_VEND */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	' ', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 56,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 17,	/* MDATA_PED */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	' ', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 57,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 5, 0,	/* MTOT_PED */
	HB_P_PUSHSTRSHORT, 14,	/* 14 */
	'9', '9', ',', '9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	' ', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 21,	/* MTIPO_VENDA */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	' ', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 22,	/* MCOD_OP */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	' ', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 56,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 19,	/* MDATA_LIB */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', ' ', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 23,	/* MCOD_EMP */
	HB_P_PLUS,
	HB_P_DOSHORT, 2,
/* 01917 */ HB_P_LINEOFFSET, 111,	/* 120 */
	HB_P_PUSHSYMNEAR, 24,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 3, 0,	/* M_POSICAO */
	HB_P_PUSHLOCALNEAR, 18,	/* MPOSICAO */
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 99, 254,	/* -413 (abs: 01516) */
/* 01932 */ HB_P_LINEOFFSET, 114,	/* 123 */
	HB_P_PUSHSYMNEAR, 58,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 14,	/* M_CODIGO */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ZERO,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 98,	/* 98 (abs: 02041) */
/* 01945 */ HB_P_LINEOFFSET, 115,	/* 124 */
	HB_P_PUSHSYMNEAR, 33,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 47,	/* 47 */
	'N', 'e', 'n', 'h', 'u', 'm', ' ', 'P', 'e', 'd', 'i', 'd', 'o', ' ', 'p', '/', 'E', 'X', 'P', 'E', 'D', 'I', 'C', 'A', 'O', ' ', '!', '!', '!', ' ', ' ', '-', ' ', ' ', '<', 'E', 'S', 'C', '>', ' ', 'p', '/', 'S', 'a', 'i', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 02001 */ HB_P_LINEOFFSET, 116,	/* 125 */
	HB_P_PUSHSYMNEAR, 59,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 190, 4,	/* 1214 (abs: 03225) */
/* 02014 */ HB_P_LINEOFFSET, 117,	/* 126 */
	HB_P_PUSHSYMNEAR, 34,	/* RESTSCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_PUSHLOCALNEAR, 5,	/* TELA */
	HB_P_DOSHORT, 5,
/* 02029 */ HB_P_LINEOFFSET, 118,	/* 127 */
	HB_P_PUSHSYMNEAR, 35,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02036 */ HB_P_LINEOFFSET, 119,	/* 128 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 02041 */ HB_P_LINEOFFSET, 124,	/* 133 */
	HB_P_PUSHSYMNEAR, 36,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 70,	/* 70 */
	'<', 25, 24, '>', ' ', 'C', 'o', 'n', 's', 'u', 'l', 't', 'a', ' ', '-', ' ', '<', 27, 'o', 'u', 26, '>', 'p', '/', 'A', 't', 'u', 'a', 'l', 'i', 'z', 'a', 'r', ' ', '-', ' ', '<', 'E', 'N', 'T', 'E', 'R', '>', 'p', '/', 'C', 'o', 'n', 'f', 'i', 'r', 'm', 'a', ' ', '-', ' ', '<', 'E', 'S', 'C', '>', ' ', 'R', 'e', 't', 'o', 'r', 'n', 'a', 0, 
	HB_P_DOSHORT, 1,
/* 02120 */ HB_P_LINEOFFSET, 125,	/* 134 */
	HB_P_PUSHSYMNEAR, 60,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 61,	/* ACHOICE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* LCI */
	HB_P_ADDINT, 3, 0,	/* 3*/
	HB_P_PUSHLOCALNEAR, 8,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 9,	/* LBA */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 10,	/* CBA */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 14,	/* M_CODIGO */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 4, 0,	/* POINT */
	HB_P_FUNCTIONSHORT, 8,
	HB_P_POPVARIABLE, 4, 0,	/* POINT */
	HB_P_PUSHSYMNEAR, 60,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 02170 */ HB_P_LINEOFFSET, 127,	/* 136 */
	HB_P_PUSHSYMNEAR, 59,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 29,	/* 29 (abs: 02209) */
/* 02182 */ HB_P_LINEOFFSET, 128,	/* 137 */
	HB_P_PUSHSYMNEAR, 34,	/* RESTSCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_PUSHLOCALNEAR, 5,	/* TELA */
	HB_P_DOSHORT, 5,
/* 02197 */ HB_P_LINEOFFSET, 129,	/* 138 */
	HB_P_PUSHSYMNEAR, 35,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02204 */ HB_P_LINEOFFSET, 130,	/* 139 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 02209 */ HB_P_LINEOFFSET, 132,	/* 141 */
	HB_P_PUSHSYMNEAR, 59,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 11,	/* 11 (abs: 02231) */
	HB_P_PUSHSYMNEAR, 59,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 19,	/* 19 */
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 12,	/* 12 (abs: 02244) */
	HB_P_PUSHSYMNEAR, 59,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 30, 1,	/* 286 */
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 02249) */
	HB_P_JUMP, 107, 250,	/* -1429 (abs: 00817) */
/* 02249 */ HB_P_LINEOFFSET, 135,	/* 144 */
	HB_P_PUSHSYMNEAR, 59,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 38, 255,	/* -218 (abs: 02041) */
/* 02262 */ HB_P_LINEOFFSET, 136,	/* 145 */
	HB_P_PUSHSYMNEAR, 62,	/* DBGOTO */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 3, 0,	/* M_POSICAO */
	HB_P_PUSHVARIABLE, 4, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_DOSHORT, 1,
/* 02276 */ HB_P_LINEOFFSET, 137,	/* 146 */
	HB_P_PUSHLOCALNEAR, 1,	/* MTP */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 180, 1,	/* 436 (abs: 02718) */
/* 02285 */ HB_P_LINEOFFSET, 138,	/* 147 */
	HB_P_PUSHSYMNEAR, 63,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 46, 0,	/* PNUM_PED */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 2, 0,	/* MNUM_PED */
/* 02301 */ HB_P_LINEOFFSET, 139,	/* 148 */
	HB_P_PUSHSYMNEAR, 63,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 53, 0,	/* PCOD_CLI */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 1, 0,	/* MCOD_CLI */
/* 02317 */ HB_P_LINEOFFSET, 140,	/* 149 */
	HB_P_PUSHLOCALNEAR, 25,	/* M_PEDIDO */
	HB_P_PUSHVARIABLE, 4, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_POPVARIABLE, 5, 0,	/* MTOT_PED */
/* 02328 */ HB_P_LINEOFFSET, 141,	/* 150 */
	HB_P_PUSHSYMNEAR, 64,	/* MENSAGEM1 */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 61,	/* 61 */
	'D', 'e', 's', 'e', 'j', 'a', ':', ' ', '[', 'A', ']', 'l', 't', 'e', 'r', 'a', 'c', 'a', 'o', ' ', 'd', 'e', ' ', 'P', 'e', 'd', 'i', 'd', 'o', ' ', '-', ' ', '[', 'E', ']', ' ', 'p', '/', 'E', 'x', 'p', 'e', 'd', 'i', 'c', 'a', 'o', ' ', '-', ' ', '[', 'I', ']', 'm', 'p', 'r', 'i', 'm', 'i', 'r', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'A', ',', 'E', ',', 'I', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPLOCALNEAR, 11,	/* OPCAO */
/* 02412 */ HB_P_LINEOFFSET, 142,	/* 151 */
	HB_P_PUSHSYMNEAR, 59,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 02427) */
	HB_P_JUMP, 185, 249,	/* -1607 (abs: 00817) */
/* 02427 */ HB_P_LINEOFFSET, 145,	/* 154 */
	HB_P_PUSHSYMNEAR, 59,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 65,	/* ASC */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'i', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 18,	/* 18 (abs: 02463) */
	HB_P_PUSHSYMNEAR, 59,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 65,	/* ASC */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'I', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 35,	/* 35 (abs: 02498) */
/* 02465 */ HB_P_LINEOFFSET, 146,	/* 155 */
	HB_P_PUSHSYMNEAR, 66,	/* SAC5PED1 */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 46, 0,	/* PNUM_PED */
	HB_P_DOSHORT, 1,
/* 02478 */ HB_P_LINEOFFSET, 148,	/* 157 */
	HB_P_PUSHSYMNEAR, 29,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 30,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 215, 2,	/* 727 (abs: 03222) */
/* 02498 */ HB_P_LINEOFFSET, 150,	/* 159 */
	HB_P_PUSHLOCALNEAR, 11,	/* OPCAO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'A', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 20,	/* 20 (abs: 02527) */
/* 02509 */ HB_P_LINEOFFSET, 151,	/* 160 */
	HB_P_PUSHSYMNEAR, 67,	/* SAC23PD1 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 2, 0,	/* MNUM_PED */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_DOSHORT, 3,
	HB_P_JUMP, 186, 2,	/* 698 (abs: 03222) */
/* 02527 */ HB_P_LINEOFFSET, 154,	/* 163 */
	HB_P_PUSHSYMNEAR, 36,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 33,	/* 33 */
	'E', 'x', 'p', 'e', 'd', 'i', 'c', 'a', 'o', ' ', 'd', 'o', ' ', 'P', 'E', 'D', 'I', 'D', 'O', 'S', ',', ' ', 'A', 'g', 'u', 'a', 'r', 'd', 'e', '.', '.', '.', 0, 
	HB_P_DOSHORT, 1,
/* 02569 */ HB_P_LINEOFFSET, 155,	/* 164 */
	HB_P_FALSE,
	HB_P_PUSHSYMNEAR, 68,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 2, 0,	/* MNUM_PED */
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHVARIABLE, 46, 0,	/* PNUM_PED */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 02595) */
	HB_P_POP,
	HB_P_PUSHSYMNEAR, 38,	/* EOF */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 106,	/* 106 (abs: 02701) */
/* 02597 */ HB_P_LINEOFFSET, 156,	/* 165 */
	HB_P_PUSHSYMNEAR, 69,	/* BLOQREG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPTRUENEAR, 52,	/* 52 (abs: 02656) */
/* 02606 */ HB_P_LINEOFFSET, 157,	/* 166 */
	HB_P_PUSHSYMNEAR, 33,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'N', 'a', 'o', ' ', 'f', 'o', 'i', ' ', 'p', 'o', 's', 's', 'i', 'v', 'e', 'l', ' ', 'a', 'c', 'e', 's', 's', 'a', 'r', ' ', 'o', ' ', 'a', 'r', 'q', 'u', 'i', 'v', 'o', ' ', '!', '!', '!', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 171,	/* -85 (abs: 02569) */
/* 02656 */ HB_P_LINEOFFSET, 160,	/* 169 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_POPALIASEDVAR, 70, 0,	/* PEXPEDI */
/* 02668 */ HB_P_LINEOFFSET, 161,	/* 170 */
	HB_P_PUSHVARIABLE, 71, 0,	/* COD_OPERADO */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_POPALIASEDVAR, 43, 0,	/* PEXP_POR */
/* 02679 */ HB_P_LINEOFFSET, 162,	/* 171 */
	HB_P_PUSHVARIABLE, 72, 0,	/* MDATA_SIS */
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_POPALIASEDVAR, 44, 0,	/* PEXP_DAT */
/* 02690 */ HB_P_LINEOFFSET, 163,	/* 172 */
	HB_P_PUSHSYMNEAR, 45,	/* DBSKIP */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 127, 255,	/* -129 (abs: 02569) */
/* 02701 */ HB_P_LINEOFFSET, 165,	/* 174 */
	HB_P_PUSHSYMNEAR, 73,	/* DBUNLOCKALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02708 */ HB_P_LINEOFFSET, 166,	/* 175 */
	HB_P_PUSHSYMNEAR, 74,	/* DBCOMMITALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMP, 254, 1,	/* 510 (abs: 03225) */
/* 02718 */ HB_P_LINEOFFSET, 169,	/* 178 */
	HB_P_PUSHSYMNEAR, 63,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_PUSHALIASEDVAR, 46, 0,	/* PNUM_PED */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 2, 0,	/* MNUM_PED */
/* 02734 */ HB_P_LINEOFFSET, 170,	/* 179 */
	HB_P_PUSHSYMNEAR, 64,	/* MENSAGEM1 */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'C', 'o', 'n', 'f', 'i', 'r', 'm', 'a', ' ', 'o', ' ', 'E', 's', 't', 'o', 'r', 'n', 'o', ' ', 'd', 'o', ' ', 'P', 'E', 'D', 'I', 'D', 'O', ' ', 'L', 'I', 'B', 'E', 'R', 'A', 'D', 'O', ':', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'N', ',', 'S', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPLOCALNEAR, 11,	/* OPCAO */
/* 02794 */ HB_P_LINEOFFSET, 171,	/* 180 */
	HB_P_PUSHSYMNEAR, 59,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 10,	/* 10 (abs: 02815) */
	HB_P_PUSHLOCALNEAR, 11,	/* OPCAO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 02820) */
	HB_P_JUMP, 48, 248,	/* -2000 (abs: 00817) */
/* 02820 */ HB_P_LINEOFFSET, 174,	/* 183 */
	HB_P_PUSHSYMNEAR, 36,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 33,	/* 33 */
	'E', 's', 't', 'o', 'r', 'n', 'a', 'n', 'd', 'o', ' ', 'd', 'o', ' ', 'P', 'E', 'D', 'I', 'D', 'O', ',', ' ', 'A', 'g', 'u', 'a', 'r', 'd', 'e', '.', '.', '.', 0, 
	HB_P_DOSHORT, 1,
/* 02862 */ HB_P_LINEOFFSET, 175,	/* 184 */
	HB_P_FALSE,
	HB_P_PUSHSYMNEAR, 68,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 2, 0,	/* MNUM_PED */
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHVARIABLE, 46, 0,	/* PNUM_PED */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 02888) */
	HB_P_POP,
	HB_P_PUSHSYMNEAR, 38,	/* EOF */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_NOT,
	HB_P_JUMPFALSE, 161, 0,	/* 161 (abs: 03049) */
/* 02891 */ HB_P_LINEOFFSET, 176,	/* 185 */
	HB_P_PUSHSYMNEAR, 69,	/* BLOQREG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPTRUENEAR, 52,	/* 52 (abs: 02950) */
/* 02900 */ HB_P_LINEOFFSET, 177,	/* 186 */
	HB_P_PUSHSYMNEAR, 33,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'N', 'a', 'o', ' ', 'f', 'o', 'i', ' ', 'p', 'o', 's', 's', 'i', 'v', 'e', 'l', ' ', 'a', 'c', 'e', 's', 's', 'a', 'r', ' ', 'o', ' ', 'a', 'r', 'q', 'u', 'i', 'v', 'o', ' ', '!', '!', '!', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 170,	/* -86 (abs: 02862) */
/* 02950 */ HB_P_LINEOFFSET, 180,	/* 189 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_POPALIASEDVAR, 70, 0,	/* PEXPEDI */
/* 02962 */ HB_P_LINEOFFSET, 181,	/* 190 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', ' ', ' ', 0, 
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_POPALIASEDVAR, 43, 0,	/* PEXP_POR */
/* 02976 */ HB_P_LINEOFFSET, 182,	/* 191 */
	HB_P_PUSHSYMNEAR, 75,	/* CTOD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	' ', ' ', '/', ' ', ' ', '/', ' ', ' ', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_POPALIASEDVAR, 44, 0,	/* PEXP_DAT */
/* 03000 */ HB_P_LINEOFFSET, 183,	/* 192 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', ' ', ' ', 0, 
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_POPALIASEDVAR, 42, 0,	/* PLIB_POR */
/* 03014 */ HB_P_LINEOFFSET, 184,	/* 193 */
	HB_P_PUSHSYMNEAR, 75,	/* CTOD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	' ', ' ', '/', ' ', ' ', '/', ' ', ' ', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHVARIABLE, 6, 0,	/* MALI_PED */
	HB_P_POPALIASEDVAR, 48, 0,	/* PLIB_DAT */
/* 03038 */ HB_P_LINEOFFSET, 185,	/* 194 */
	HB_P_PUSHSYMNEAR, 45,	/* DBSKIP */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 72, 255,	/* -184 (abs: 02862) */
/* 03049 */ HB_P_LINEOFFSET, 187,	/* 196 */
	HB_P_PUSHSYMNEAR, 73,	/* DBUNLOCKALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 03056 */ HB_P_LINEOFFSET, 189,	/* 198 */
	HB_P_PUSHSYMNEAR, 29,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 7, 0,	/* MALI_CON */
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 30,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 03072 */ HB_P_LINEOFFSET, 190,	/* 199 */
	HB_P_PUSHSYMNEAR, 31,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 03079 */ HB_P_LINEOFFSET, 192,	/* 201 */
	HB_P_PUSHALIAS,
	HB_P_PUSHVARIABLE, 7, 0,	/* MALI_CON */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 32,	/* DBSEEK */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 68,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 2, 0,	/* MNUM_PED */
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_SWAPALIAS,
	HB_P_JUMPFALSENEAR, 113,	/* 113 (abs: 03215) */
/* 03104 */ HB_P_LINEOFFSET, 193,	/* 202 */
	HB_P_PUSHSYMNEAR, 69,	/* BLOQREG */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 03111 */ HB_P_LINEOFFSET, 194,	/* 203 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PUSHVARIABLE, 7, 0,	/* MALI_CON */
	HB_P_POPALIASEDVAR, 76, 0,	/* EXPEDI */
/* 03123 */ HB_P_LINEOFFSET, 195,	/* 204 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', ' ', ' ', 0, 
	HB_P_PUSHVARIABLE, 7, 0,	/* MALI_CON */
	HB_P_POPALIASEDVAR, 77, 0,	/* EXP_POR */
/* 03137 */ HB_P_LINEOFFSET, 196,	/* 205 */
	HB_P_PUSHSYMNEAR, 75,	/* CTOD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	' ', ' ', '/', ' ', ' ', '/', ' ', ' ', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHVARIABLE, 7, 0,	/* MALI_CON */
	HB_P_POPALIASEDVAR, 78, 0,	/* EXP_DAT */
/* 03161 */ HB_P_LINEOFFSET, 197,	/* 206 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', ' ', ' ', 0, 
	HB_P_PUSHVARIABLE, 7, 0,	/* MALI_CON */
	HB_P_POPALIASEDVAR, 79, 0,	/* LIB_POR */
/* 03175 */ HB_P_LINEOFFSET, 198,	/* 207 */
	HB_P_PUSHSYMNEAR, 75,	/* CTOD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	' ', ' ', '/', ' ', ' ', '/', ' ', ' ', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHVARIABLE, 7, 0,	/* MALI_CON */
	HB_P_POPALIASEDVAR, 80, 0,	/* LIB_DAT */
/* 03199 */ HB_P_LINEOFFSET, 199,	/* 208 */
	HB_P_ZERO,
	HB_P_PUSHVARIABLE, 7, 0,	/* MALI_CON */
	HB_P_POPALIASEDVAR, 81, 0,	/* LIB_VLR */
/* 03208 */ HB_P_LINEOFFSET, 200,	/* 209 */
	HB_P_PUSHSYMNEAR, 82,	/* DBUNLOCK */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 03215 */ HB_P_LINEOFFSET, 202,	/* 211 */
	HB_P_PUSHSYMNEAR, 74,	/* DBCOMMITALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMP, 155, 246,	/* -2405 (abs: 00817) */
	HB_P_JUMP, 152, 246,	/* -2408 (abs: 00817) */
	HB_P_ENDPROC
/* 03229 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

