/*
 * xHarbour build 0.99.70 Intl. (SimpLex)
 * Generated C source code from <SACNOTA.PRG>
 * Command: C:\xHarbour997\bin\harbour.exe C:\HTI\SISCOM\SACNOTA.PRG /q /oC:\hti\SISCOM\SACNOTA.c /M /N -DxHB -DXHB_0990 -DXHB_0991 -DXHB_0992 -DXHB_0993 -DXHB_0994 -DXHB_09941 -DXHB_09950 -DXHB_09951a -DXHB_09951 -DXHB_09951b -DXHB_0996 -DXHB_09960 -DXHB_09961 -DXHB_09961B -DXHB_0997 -DXHB_09970 
 * Created: 2023.09.20 11:15:12 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "SACNOTA.PRG"

HB_FUNC( NOTA );
HB_FUNC_EXTERN( __MVPRIVATE );
HB_FUNC_EXTERN( READKILL );
HB_FUNC_EXTERN( SPACE );
HB_FUNC_EXTERN( REPLICATE );
HB_FUNC_EXTERN( OP_TELA );
HB_FUNC_EXTERN( LEN );
HB_FUNC_EXTERN( EMPTY );
HB_FUNC_EXTERN( IAT );
HB_FUNC_EXTERN( AADD );
HB_FUNC_EXTERN( TRANSFORM );
HB_FUNC_EXTERN( ATENCAO );
HB_FUNC_EXTERN( WVW_LCLOSEWINDOW );
HB_FUNC_EXTERN( MENSAGEM );
HB_FUNC_EXTERN( DEVPOS );
HB_FUNC_EXTERN( DEVOUT );
HB_FUNC_EXTERN( DISPBOX );
HB_FUNC_EXTERN( JANELA );
HB_FUNC_EXTERN( SETCOR );
HB_FUNC_EXTERN( DEVOUTPICT );
HB_FUNC_EXTERN( BOTAO1 );
HB_FUNC_EXTERN( __ATPROMPT );
HB_FUNC_EXTERN( SET );
HB_FUNC_EXTERN( __MENUTO );
HB_FUNC_EXTERN( PCOUNT );
HB_FUNC_EXTERN( LASTKEY );
HB_FUNC_EXTERN( ACHOICE );
HB_FUNC_EXTERN( SAVESCREEN );
HB_FUNC_EXTERN( SETPOS );
HB_FUNC_EXTERN( __GET );
HB_FUNC_EXTERN( READMODAL );
HB_FUNC_EXTERN( STRZERO );
HB_FUNC_EXTERN( SUBSTR );
HB_FUNC_EXTERN( SR_GETCONNECTION );
HB_FUNC_EXTERN( SR_CDBVALUE );
HB_FUNC_EXTERN( __GETA );
HB_FUNC_EXTERN( SACNF_E );
HB_FUNC_EXTERN( __MVXRELEASE );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 7

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_SACNOTA )
{ "NOTA", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( NOTA )}, NULL },
{ "MOPCAO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OPCAO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "I", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PODE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "F", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTRACO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MCODIGO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MDESCRICAO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "M_ACUCAR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MSALDO_ATU", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MEXTENSO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LIN1", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LIN2", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MLIN1", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MLIN2", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MLIN3", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MLIN4", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MLIN5", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MLIN6", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "M_ALTERA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "TELA2", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MPAG", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MDOC_AUX", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTOT_AUX", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MCOD_FAT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MLIN", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "M_POS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MPOS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVLR_ICMSUB", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MDESC_ICM", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MPR_FAT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MDIF_ICMS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTIP_CLI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MBASE_SUB", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MICM_SUB", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTOT_DESC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "POINT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MNUM_DUP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MNUM_DUP1", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MNUM_DUP2", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MNUM_DUP3", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MNUM_DUP4", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MNUM_DUP5", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVENCI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVENCI1", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVENCI2", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVENCI3", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVENCI4", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVENCI5", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVLR_DUP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVLR_DUP1", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVLR_DUP2", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVLR_DUP3", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVLR_DUP4", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVLR_DUP5", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MNOTA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTOT_PROD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MPIS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MCONFIS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MICMS_DESC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MPERCENT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CTOT_QUANTD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CBASE_ICM", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CTOT_ICM", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CBASE_ICMF", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CTOT_ICMF", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CTOT_IPI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CTOT_PROD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CTOT_NOTA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CTOT_PESO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CTOT_LIQ", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__MVPRIVATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPRIVATE )}, NULL },
{ "READKILL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READKILL )}, NULL },
{ "GETLIST", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPACE )}, NULL },
{ "REPLICATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( REPLICATE )}, NULL },
{ "OP_TELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_TELA )}, NULL },
{ "MBASE_ICMF", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MBASE_ICM", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTOT_IPI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTOT_ICMF", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTOT_LIQ", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTOT_PESO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTOT_QUANTD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTOT_NOTA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTOT_ICM", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MARCA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTIPO_NOTA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( LEN )}, NULL },
{ "M_NORMAL", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "EMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EMPTY )}, NULL },
{ "M_SET", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "IAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( IAT )}, NULL },
{ "AADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADD )}, NULL },
{ "TRANSFORM", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRANSFORM )}, NULL },
{ "MCOD_NAT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ATENCAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATENCAO )}, NULL },
{ "WVW_LCLOSEWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_LCLOSEWINDOW )}, NULL },
{ "MENSAGEM", {HB_FS_PUBLIC}, {HB_FUNCNAME( MENSAGEM )}, NULL },
{ "DEVPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVPOS )}, NULL },
{ "DEVOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUT )}, NULL },
{ "DISPBOX", {HB_FS_PUBLIC}, {HB_FUNCNAME( DISPBOX )}, NULL },
{ "JANELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( JANELA )}, NULL },
{ "SETCOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETCOR )}, NULL },
{ "DEVOUTPICT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUTPICT )}, NULL },
{ "MFRETE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MSEGURO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MENCARGO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "BOTAO1", {HB_FS_PUBLIC}, {HB_FUNCNAME( BOTAO1 )}, NULL },
{ "__ATPROMPT", {HB_FS_PUBLIC}, {HB_FUNCNAME( __ATPROMPT )}, NULL },
{ "SET", {HB_FS_PUBLIC}, {HB_FUNCNAME( SET )}, NULL },
{ "__MENUTO", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MENUTO )}, NULL },
{ "PCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PCOUNT )}, NULL },
{ "MOP_NOTA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LASTKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( LASTKEY )}, NULL },
{ "ACHOICE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ACHOICE )}, NULL },
{ "SAVESCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAVESCREEN )}, NULL },
{ "SETPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETPOS )}, NULL },
{ "__GET", {HB_FS_PUBLIC}, {HB_FUNCNAME( __GET )}, NULL },
{ "DISPLAY", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "READMODAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READMODAL )}, NULL },
{ "STRZERO", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRZERO )}, NULL },
{ "SUBSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SUBSTR )}, NULL },
{ "CONS_MERC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "EXEC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SR_GETCONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETCONNECTION )}, NULL },
{ "SR_CDBVALUE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_CDBVALUE )}, NULL },
{ "__GETA", {HB_FS_PUBLIC}, {HB_FUNCNAME( __GETA )}, NULL },
{ "TOTNT", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "VL_BASE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "VL_ICM", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "BASE_ICMSU", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "VL_ICMSU", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "IPI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "VL_PROD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "VL_NOTA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PESO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PESO_LIQ", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SACNF_E", {HB_FS_PUBLIC}, {HB_FUNCNAME( SACNF_E )}, NULL },
{ "__MVXRELEASE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVXRELEASE )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_SACNOTA )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_SACNOTA
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_SACNOTA = hb_vm_SymbolInit_SACNOTA;
   #pragma data_seg()
#endif

HB_FUNC( NOTA )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 7, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 7, 0,	/* 7 */
	HB_P_LOCALNEARSETINT, 4, 0, 0,	/* MCODIGO_AUX 0*/
	HB_P_LOCALNEARSETINT, 5, 0, 0,	/* MACHOU 0*/
	HB_P_LOCALNEARSETINT, 7, 0, 0,	/* MSOBRA 0*/
	HB_P_LOCALNEARSETINT, 8, 0, 0,	/* MPERC_QTD 0*/
/* 00022 */ HB_P_LINEOFFSET, 20,	/* 27 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHSYMNEAR, 72,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 1,	/* MOPCAO */
	HB_P_PUSHSYMNEAR, 2,	/* OPCAO */
	HB_P_PUSHSYMNEAR, 3,	/* I */
	HB_P_PUSHSYMNEAR, 4,	/* PODE */
	HB_P_PUSHSYMNEAR, 5,	/* F */
	HB_P_PUSHSYMNEAR, 6,	/* MTRACO */
	HB_P_PUSHSYMNEAR, 7,	/* MCODIGO */
	HB_P_PUSHSYMNEAR, 8,	/* MDESCRICAO */
	HB_P_PUSHSYMNEAR, 9,	/* M_ACUCAR */
	HB_P_PUSHSYMNEAR, 10,	/* MSALDO_ATU */
	HB_P_PUSHSYMNEAR, 11,	/* MEXTENSO */
	HB_P_PUSHSYMNEAR, 12,	/* LIN1 */
	HB_P_PUSHSYMNEAR, 13,	/* LIN2 */
	HB_P_PUSHSYMNEAR, 14,	/* MLIN1 */
	HB_P_PUSHSYMNEAR, 15,	/* MLIN2 */
	HB_P_PUSHSYMNEAR, 16,	/* MLIN3 */
	HB_P_PUSHSYMNEAR, 17,	/* MLIN4 */
	HB_P_PUSHSYMNEAR, 18,	/* MLIN5 */
	HB_P_PUSHSYMNEAR, 19,	/* MLIN6 */
	HB_P_PUSHSYMNEAR, 20,	/* M_ALTERA */
	HB_P_PUSHSYMNEAR, 21,	/* TELA2 */
	HB_P_PUSHSYMNEAR, 22,	/* MPAG */
	HB_P_PUSHSYMNEAR, 23,	/* MDOC_AUX */
	HB_P_PUSHSYMNEAR, 24,	/* MTOT_AUX */
	HB_P_PUSHSYMNEAR, 25,	/* MCOD_FAT */
	HB_P_PUSHSYMNEAR, 26,	/* MLIN */
	HB_P_PUSHSYMNEAR, 27,	/* M_POS */
	HB_P_PUSHSYMNEAR, 28,	/* MPOS */
	HB_P_PUSHSYMNEAR, 29,	/* MVLR_ICMSUB */
	HB_P_PUSHSYMNEAR, 30,	/* MDESC_ICM */
	HB_P_PUSHSYMNEAR, 31,	/* MPR_FAT */
	HB_P_PUSHSYMNEAR, 32,	/* MDIF_ICMS */
	HB_P_PUSHSYMNEAR, 33,	/* MTIP_CLI */
	HB_P_PUSHSYMNEAR, 34,	/* MBASE_SUB */
	HB_P_PUSHSYMNEAR, 35,	/* MICM_SUB */
	HB_P_PUSHSYMNEAR, 36,	/* MTOT_DESC */
	HB_P_PUSHSYMNEAR, 37,	/* POINT */
	HB_P_PUSHSYMNEAR, 38,	/* MNUM_DUP */
	HB_P_PUSHSYMNEAR, 39,	/* MNUM_DUP1 */
	HB_P_PUSHSYMNEAR, 40,	/* MNUM_DUP2 */
	HB_P_PUSHSYMNEAR, 41,	/* MNUM_DUP3 */
	HB_P_PUSHSYMNEAR, 42,	/* MNUM_DUP4 */
	HB_P_PUSHSYMNEAR, 43,	/* MNUM_DUP5 */
	HB_P_PUSHSYMNEAR, 44,	/* MVENCI */
	HB_P_PUSHSYMNEAR, 45,	/* MVENCI1 */
	HB_P_PUSHSYMNEAR, 46,	/* MVENCI2 */
	HB_P_PUSHSYMNEAR, 47,	/* MVENCI3 */
	HB_P_PUSHSYMNEAR, 48,	/* MVENCI4 */
	HB_P_PUSHSYMNEAR, 49,	/* MVENCI5 */
	HB_P_PUSHSYMNEAR, 50,	/* MVLR_DUP */
	HB_P_PUSHSYMNEAR, 51,	/* MVLR_DUP1 */
	HB_P_PUSHSYMNEAR, 52,	/* MVLR_DUP2 */
	HB_P_PUSHSYMNEAR, 53,	/* MVLR_DUP3 */
	HB_P_PUSHSYMNEAR, 54,	/* MVLR_DUP4 */
	HB_P_PUSHSYMNEAR, 55,	/* MVLR_DUP5 */
	HB_P_PUSHSYMNEAR, 56,	/* MNOTA */
	HB_P_PUSHSYMNEAR, 57,	/* MTOT_PROD */
	HB_P_PUSHSYMNEAR, 58,	/* MPIS */
	HB_P_PUSHSYMNEAR, 59,	/* MCONFIS */
	HB_P_PUSHSYMNEAR, 60,	/* MICMS_DESC */
	HB_P_PUSHSYMNEAR, 61,	/* MPERCENT */
	HB_P_PUSHSYMNEAR, 62,	/* CTOT_QUANTD */
	HB_P_PUSHSYMNEAR, 63,	/* CBASE_ICM */
	HB_P_PUSHSYMNEAR, 64,	/* CTOT_ICM */
	HB_P_PUSHSYMNEAR, 65,	/* CBASE_ICMF */
	HB_P_PUSHSYMNEAR, 66,	/* CTOT_ICMF */
	HB_P_PUSHSYMNEAR, 67,	/* CTOT_IPI */
	HB_P_PUSHSYMNEAR, 68,	/* CTOT_PROD */
	HB_P_PUSHSYMNEAR, 69,	/* CTOT_NOTA */
	HB_P_PUSHSYMNEAR, 70,	/* CTOT_PESO */
	HB_P_PUSHSYMNEAR, 71,	/* CTOT_LIQ */
	HB_P_DOSHORT, 71,
	HB_P_POPVARIABLE, 71, 0,	/* CTOT_LIQ */
	HB_P_POPVARIABLE, 70, 0,	/* CTOT_PESO */
	HB_P_POPVARIABLE, 69, 0,	/* CTOT_NOTA */
	HB_P_POPVARIABLE, 68, 0,	/* CTOT_PROD */
	HB_P_POPVARIABLE, 67, 0,	/* CTOT_IPI */
	HB_P_POPVARIABLE, 66, 0,	/* CTOT_ICMF */
	HB_P_POPVARIABLE, 65, 0,	/* CBASE_ICMF */
	HB_P_POPVARIABLE, 64, 0,	/* CTOT_ICM */
	HB_P_POPVARIABLE, 63, 0,	/* CBASE_ICM */
	HB_P_POPVARIABLE, 62, 0,	/* CTOT_QUANTD */
	HB_P_POPVARIABLE, 61, 0,	/* MPERCENT */
	HB_P_POPVARIABLE, 60, 0,	/* MICMS_DESC */
	HB_P_POPVARIABLE, 59, 0,	/* MCONFIS */
	HB_P_POPVARIABLE, 58, 0,	/* MPIS */
	HB_P_POPVARIABLE, 57, 0,	/* MTOT_PROD */
	HB_P_POPVARIABLE, 55, 0,	/* MVLR_DUP5 */
	HB_P_POPVARIABLE, 54, 0,	/* MVLR_DUP4 */
	HB_P_POPVARIABLE, 53, 0,	/* MVLR_DUP3 */
	HB_P_POPVARIABLE, 52, 0,	/* MVLR_DUP2 */
	HB_P_POPVARIABLE, 51, 0,	/* MVLR_DUP1 */
	HB_P_POPVARIABLE, 50, 0,	/* MVLR_DUP */
	HB_P_POPVARIABLE, 36, 0,	/* MTOT_DESC */
	HB_P_POPVARIABLE, 35, 0,	/* MICM_SUB */
	HB_P_POPVARIABLE, 34, 0,	/* MBASE_SUB */
	HB_P_POPVARIABLE, 33, 0,	/* MTIP_CLI */
	HB_P_POPVARIABLE, 32, 0,	/* MDIF_ICMS */
	HB_P_POPVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_POPVARIABLE, 30, 0,	/* MDESC_ICM */
	HB_P_POPVARIABLE, 29, 0,	/* MVLR_ICMSUB */
	HB_P_POPVARIABLE, 27, 0,	/* M_POS */
	HB_P_POPVARIABLE, 20, 0,	/* M_ALTERA */
	HB_P_POPVARIABLE, 9, 0,	/* M_ACUCAR */
/* 00308 */ HB_P_LINEOFFSET, 22,	/* 29 */
	HB_P_PUSHSYMNEAR, 73,	/* READKILL */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_DOSHORT, 1,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 74, 0,	/* GETLIST */
/* 00322 */ HB_P_LINEOFFSET, 23,	/* 30 */
	HB_P_PUSHSYMNEAR, 75,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 25, 0,	/* MCOD_FAT */
/* 00334 */ HB_P_LINEOFFSET, 24,	/* 31 */
	HB_P_PUSHSYMNEAR, 76,	/* REPLICATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'=', 0, 
	HB_P_PUSHBYTE, 80,	/* 80 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 6, 0,	/* MTRACO */
/* 00350 */ HB_P_LINEOFFSET, 25,	/* 32 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_POPVARIABLE, 26, 0,	/* MLIN */
/* 00357 */ HB_P_LINEOFFSET, 26,	/* 33 */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'0', '1', 0, 
	HB_P_POPVARIABLE, 25, 0,	/* MCOD_FAT */
/* 00367 */ HB_P_LINEOFFSET, 27,	/* 34 */
	HB_P_PUSHSYMNEAR, 77,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 42,	/* 42 */
	HB_P_PUSHBYTE, 35,	/* 35 */
	HB_P_PUSHBYTE, 118,	/* 118 */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	' ', 'A', 'l', 't', 'e', 'r', 'a', 'c', 'a', 'o', ' ', 'd', 'e', ' ', 'P', 'r', 'o', 'd', 'u', 't', 'o', 's', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_DOSHORT, 7,
/* 00413 */ HB_P_LINEOFFSET, 29,	/* 36 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 20, 0,	/* M_ALTERA */
/* 00421 */ HB_P_LINEOFFSET, 32,	/* 39 */
	HB_P_LOCALNEARSETINT, 7, 0, 0,	/* MSOBRA 0*/
	HB_P_PUSHLOCALNEAR, 7,	/* MSOBRA */
	HB_P_DUPLICATE,
	HB_P_POPMEMVAR, 78, 0,	/* MBASE_ICMF */
	HB_P_DUPLICATE,
	HB_P_POPMEMVAR, 79, 0,	/* MBASE_ICM */
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 5, 0,	/* F */
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 3, 0,	/* I */
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 30, 0,	/* MDESC_ICM */
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 29, 0,	/* MVLR_ICMSUB */
	HB_P_DUPLICATE,
	HB_P_POPMEMVAR, 80, 0,	/* MTOT_IPI */
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 24, 0,	/* MTOT_AUX */
	HB_P_DUPLICATE,
	HB_P_POPMEMVAR, 81, 0,	/* MTOT_ICMF */
	HB_P_DUPLICATE,
	HB_P_POPMEMVAR, 82, 0,	/* MTOT_LIQ */
	HB_P_DUPLICATE,
	HB_P_POPMEMVAR, 83, 0,	/* MTOT_PESO */
	HB_P_DUPLICATE,
	HB_P_POPMEMVAR, 84, 0,	/* MTOT_QUANTD */
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 36, 0,	/* MTOT_DESC */
	HB_P_DUPLICATE,
	HB_P_POPMEMVAR, 85, 0,	/* MTOT_NOTA */
	HB_P_POPMEMVAR, 86, 0,	/* MTOT_ICM */
/* 00488 */ HB_P_LINEOFFSET, 33,	/* 40 */
	HB_P_PUSHSYMNEAR, 75,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 13, 0,	/* LIN2 */
	HB_P_POPVARIABLE, 12, 0,	/* LIN1 */
/* 00504 */ HB_P_LINEOFFSET, 34,	/* 41 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 28, 0,	/* MPOS */
/* 00510 */ HB_P_LINEOFFSET, 35,	/* 42 */
	HB_P_PUSHSYMNEAR, 75,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPMEMVAR, 87, 0,	/* MARCA */
/* 00521 */ HB_P_LINEOFFSET, 36,	/* 43 */
	HB_P_PUSHMEMVAR, 88, 0,	/* MTIPO_NOTA */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 217, 3,	/* 985 (abs: 01516) */
/* 00534 */ HB_P_LINEOFFSET, 37,	/* 44 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 5, 0,	/* F */
/* 00540 */ HB_P_LINEOFFSET, 38,	/* 45 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 5, 0,	/* F */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_PUSHSYMNEAR, 89,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSE, 46, 3,	/* 814 (abs: 01372) */
/* 00561 */ HB_P_LINEOFFSET, 39,	/* 46 */
	HB_P_PUSHVARIABLE, 25, 0,	/* MCOD_FAT */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'0', '1', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 14,	/* 14 (abs: 00586) */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_ARRAYPUSH,
	HB_P_JUMPNEAR, 97,	/* 97 (abs: 00681) */
	HB_P_PUSHVARIABLE, 25, 0,	/* MCOD_FAT */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'0', '2', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 58,	/* 58 (abs: 00653) */
	HB_P_PUSHSYMNEAR, 91,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 14,	/* 14 (abs: 00626) */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_ARRAYPUSH,
	HB_P_JUMPNEAR, 57,	/* 57 (abs: 00681) */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHMEMVAR, 92, 0,	/* M_SET */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_MULT,
	HB_P_JUMPNEAR, 30,	/* 30 (abs: 00681) */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHVARIABLE, 61, 0,	/* MPERCENT */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_MULT,
	HB_P_MINUS,
	HB_P_POPVARIABLE, 31, 0,	/* MPR_FAT */
/* 00684 */ HB_P_LINEOFFSET, 40,	/* 47 */
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_ARRAYPOP,
/* 00699 */ HB_P_LINEOFFSET, 41,	/* 48 */
	HB_P_PUSHLOCALNEAR, 8,	/* MPERC_QTD */
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 36,	/* 36 (abs: 00741) */
/* 00707 */ HB_P_LINEOFFSET, 42,	/* 49 */
	HB_P_PUSHSYMNEAR, 93,	/* IAT */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHLOCALNEAR, 8,	/* MPERC_QTD */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_MULT,
	HB_P_ZERO,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPOP,
/* 00741 */ HB_P_LINEOFFSET, 44,	/* 51 */
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 20, 0,	/* M_ALTERA */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 95,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'9', '9', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 95,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'9', '9', '9', '9', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 95,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_DOSHORT, 2,
/* 00865 */ HB_P_LINEOFFSET, 45,	/* 52 */
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 27, 0,	/* M_POS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'm', 'n', 'o', 'r', 'm', 'a', 'l', 0, 
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_DOSHORT, 2,
/* 00891 */ HB_P_LINEOFFSET, 46,	/* 53 */
	HB_P_PUSHVARIABLE, 28, 0,	/* MPOS */
	HB_P_INC,
	HB_P_POPVARIABLE, 28, 0,	/* MPOS */
/* 00900 */ HB_P_LINEOFFSET, 47,	/* 54 */
	HB_P_PUSHVARIABLE, 24, 0,	/* MTOT_AUX */
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_POPVARIABLE, 24, 0,	/* MTOT_AUX */
/* 00923 */ HB_P_LINEOFFSET, 48,	/* 55 */
	HB_P_PUSHMEMVAR, 85, 0,	/* MTOT_NOTA */
	HB_P_PUSHSYMNEAR, 93,	/* IAT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_POPMEMVAR, 85, 0,	/* MTOT_NOTA */
/* 00953 */ HB_P_LINEOFFSET, 49,	/* 56 */
	HB_P_PUSHMEMVAR, 80, 0,	/* MTOT_IPI */
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_POPMEMVAR, 80, 0,	/* MTOT_IPI */
/* 00990 */ HB_P_LINEOFFSET, 50,	/* 57 */
	HB_P_PUSHVARIABLE, 36, 0,	/* MTOT_DESC */
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_POPVARIABLE, 36, 0,	/* MTOT_DESC */
/* 01027 */ HB_P_LINEOFFSET, 51,	/* 58 */
	HB_P_PUSHMEMVAR, 84, 0,	/* MTOT_QUANTD */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_POPMEMVAR, 84, 0,	/* MTOT_QUANTD */
/* 01046 */ HB_P_LINEOFFSET, 52,	/* 59 */
	HB_P_PUSHMEMVAR, 83, 0,	/* MTOT_PESO */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_POPMEMVAR, 83, 0,	/* MTOT_PESO */
/* 01076 */ HB_P_LINEOFFSET, 53,	/* 60 */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_ARRAYPUSH,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 44,	/* 44 (abs: 01134) */
/* 01092 */ HB_P_LINEOFFSET, 54,	/* 61 */
	HB_P_PUSHMEMVAR, 78, 0,	/* MBASE_ICMF */
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_POPMEMVAR, 78, 0,	/* MBASE_ICMF */
/* 01115 */ HB_P_LINEOFFSET, 55,	/* 62 */
	HB_P_PUSHMEMVAR, 81, 0,	/* MTOT_ICMF */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_POPMEMVAR, 81, 0,	/* MTOT_ICMF */
/* 01134 */ HB_P_LINEOFFSET, 57,	/* 64 */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 14,	/* 14 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 25,	/* 25 (abs: 01176) */
/* 01153 */ HB_P_LINEOFFSET, 58,	/* 65 */
	HB_P_PUSHMEMVAR, 79, 0,	/* MBASE_ICM */
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_POPMEMVAR, 79, 0,	/* MBASE_ICM */
/* 01176 */ HB_P_LINEOFFSET, 60,	/* 67 */
	HB_P_PUSHSYMNEAR, 91,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 22,	/* 22 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 113,	/* 113 (abs: 01306) */
/* 01195 */ HB_P_LINEOFFSET, 61,	/* 68 */
	HB_P_PUSHVARIABLE, 29, 0,	/* MVLR_ICMSUB */
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHMEMVAR, 92, 0,	/* M_SET */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_MULT,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 22,	/* 22 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_MULT,
	HB_P_PUSHMEMVAR, 92, 0,	/* M_SET */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHMEMVAR, 92, 0,	/* M_SET */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_MULT,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_MULT,
	HB_P_MINUS,
	HB_P_POPVARIABLE, 29, 0,	/* MVLR_ICMSUB */
/* 01306 */ HB_P_LINEOFFSET, 63,	/* 70 */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 37,	/* 37 (abs: 01360) */
/* 01325 */ HB_P_LINEOFFSET, 64,	/* 71 */
	HB_P_PUSHVARIABLE, 30, 0,	/* MDESC_ICM */
	HB_P_PUSHMEMVAR, 92, 0,	/* M_SET */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_POPVARIABLE, 30, 0,	/* MDESC_ICM */
/* 01360 */ HB_P_LINEOFFSET, 66,	/* 73 */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_INC,
	HB_P_POPVARIABLE, 5, 0,	/* F */
	HB_P_JUMP, 201, 252,	/* -823 (abs: 00546) */
/* 01372 */ HB_P_LINEOFFSET, 67,	/* 74 */
	HB_P_PUSHMEMVAR, 96, 0,	/* MCOD_NAT */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'6', '.', '1', '0', '9', 0, 
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 15,	/* 15 (abs: 01402) */
	HB_P_PUSHMEMVAR, 96, 0,	/* MCOD_NAT */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'6', '.', '1', '1', '0', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSE, 31, 2,	/* 543 (abs: 01945) */
/* 01405 */ HB_P_LINEOFFSET, 68,	/* 75 */
	HB_P_PUSHSYMNEAR, 93,	/* IAT */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 85, 0,	/* MTOT_NOTA */
	HB_P_PUSHDOUBLE, 76, 55, 137, 65, 96, 229, 144, 63, 10, 4,	/* 0.0165, 10, 4 */
	HB_P_MULT,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 58, 0,	/* MPIS */
/* 01432 */ HB_P_LINEOFFSET, 69,	/* 76 */
	HB_P_PUSHSYMNEAR, 93,	/* IAT */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 85, 0,	/* MTOT_NOTA */
	HB_P_PUSHDOUBLE, 219, 249, 126, 106, 188, 116, 179, 63, 10, 3,	/* 0.076, 10, 3 */
	HB_P_MULT,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 59, 0,	/* MCONFIS */
/* 01459 */ HB_P_LINEOFFSET, 70,	/* 77 */
	HB_P_PUSHSYMNEAR, 93,	/* IAT */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 85, 0,	/* MTOT_NOTA */
	HB_P_PUSHDOUBLE, 184, 30, 133, 235, 81, 184, 190, 63, 10, 2,	/* 0.12, 10, 2 */
	HB_P_MULT,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 60, 0,	/* MICMS_DESC */
/* 01486 */ HB_P_LINEOFFSET, 71,	/* 78 */
	HB_P_PUSHMEMVAR, 85, 0,	/* MTOT_NOTA */
	HB_P_PUSHSYMNEAR, 93,	/* IAT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 58, 0,	/* MPIS */
	HB_P_PUSHVARIABLE, 59, 0,	/* MCONFIS */
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 60, 0,	/* MICMS_DESC */
	HB_P_PLUS,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_MINUS,
	HB_P_POPMEMVAR, 85, 0,	/* MTOT_NOTA */
	HB_P_JUMP, 176, 1,	/* 432 (abs: 01945) */
/* 01516 */ HB_P_LINEOFFSET, 74,	/* 81 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 5, 0,	/* F */
/* 01522 */ HB_P_LINEOFFSET, 75,	/* 82 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 5, 0,	/* F */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_PUSHSYMNEAR, 89,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSE, 149, 1,	/* 405 (abs: 01945) */
/* 01543 */ HB_P_LINEOFFSET, 76,	/* 83 */
	HB_P_PUSHVARIABLE, 25, 0,	/* MCOD_FAT */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'0', '1', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 14,	/* 14 (abs: 01568) */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_ARRAYPUSH,
	HB_P_JUMPNEAR, 97,	/* 97 (abs: 01663) */
	HB_P_PUSHVARIABLE, 25, 0,	/* MCOD_FAT */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'0', '2', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 58,	/* 58 (abs: 01635) */
	HB_P_PUSHSYMNEAR, 91,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 14,	/* 14 (abs: 01608) */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_ARRAYPUSH,
	HB_P_JUMPNEAR, 57,	/* 57 (abs: 01663) */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHMEMVAR, 92, 0,	/* M_SET */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_MULT,
	HB_P_JUMPNEAR, 30,	/* 30 (abs: 01663) */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHVARIABLE, 61, 0,	/* MPERCENT */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_MULT,
	HB_P_MINUS,
	HB_P_POPVARIABLE, 31, 0,	/* MPR_FAT */
/* 01666 */ HB_P_LINEOFFSET, 77,	/* 84 */
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_ARRAYPOP,
/* 01681 */ HB_P_LINEOFFSET, 78,	/* 85 */
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 20, 0,	/* M_ALTERA */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 95,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'9', '9', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 95,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'9', '9', '9', '9', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 95,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_DOSHORT, 2,
/* 01805 */ HB_P_LINEOFFSET, 79,	/* 86 */
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 27, 0,	/* M_POS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'm', 'n', 'o', 'r', 'm', 'a', 'l', 0, 
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_DOSHORT, 2,
/* 01831 */ HB_P_LINEOFFSET, 80,	/* 87 */
	HB_P_PUSHVARIABLE, 28, 0,	/* MPOS */
	HB_P_INC,
	HB_P_POPVARIABLE, 28, 0,	/* MPOS */
/* 01840 */ HB_P_LINEOFFSET, 81,	/* 88 */
	HB_P_PUSHMEMVAR, 85, 0,	/* MTOT_NOTA */
	HB_P_PUSHSYMNEAR, 93,	/* IAT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_POPMEMVAR, 85, 0,	/* MTOT_NOTA */
/* 01870 */ HB_P_LINEOFFSET, 82,	/* 89 */
	HB_P_PUSHMEMVAR, 80, 0,	/* MTOT_IPI */
	HB_P_PUSHSYMNEAR, 93,	/* IAT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 31, 0,	/* MPR_FAT */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_POPMEMVAR, 80, 0,	/* MTOT_IPI */
/* 01914 */ HB_P_LINEOFFSET, 83,	/* 90 */
	HB_P_PUSHMEMVAR, 84, 0,	/* MTOT_QUANTD */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_POPMEMVAR, 84, 0,	/* MTOT_QUANTD */
/* 01933 */ HB_P_LINEOFFSET, 84,	/* 91 */
	HB_P_PUSHVARIABLE, 5, 0,	/* F */
	HB_P_INC,
	HB_P_POPVARIABLE, 5, 0,	/* F */
	HB_P_JUMP, 98, 254,	/* -414 (abs: 01528) */
/* 01945 */ HB_P_LINEOFFSET, 86,	/* 93 */
	HB_P_PUSHSYMNEAR, 89,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 20, 0,	/* M_ALTERA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ZERO,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 89,	/* 89 (abs: 02046) */
/* 01959 */ HB_P_LINEOFFSET, 87,	/* 94 */
	HB_P_PUSHSYMNEAR, 97,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 66,	/* 66 */
	'N', 'a', 'o', ' ', 'p', 'o', 'd', 'e', ' ', 'e', 'm', 'i', 't', 'i', 'r', ' ', 'e', 's', 't', 'a', ' ', 'n', 'o', 't', 'a', ' ', 'p', 'o', 'i', 's', ' ', 'n', 'a', 'o', ' ', 'f', 'o', 'i', ' ', 'i', 'n', 'c', 'l', 'u', 'i', 'd', 'o', ' ', 'n', 'e', 'n', 'h', 'u', 'm', ' ', 'P', 'r', 'o', 'd', 'u', 't', 'o', '.', '.', '.', 0, 
	HB_P_DOSHORT, 1,
/* 02034 */ HB_P_LINEOFFSET, 88,	/* 95 */
	HB_P_PUSHSYMNEAR, 98,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02041 */ HB_P_LINEOFFSET, 89,	/* 96 */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 02046 */ HB_P_LINEOFFSET, 91,	/* 98 */
	HB_P_ZERO,
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 5, 0,	/* F */
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 61, 0,	/* MPERCENT */
	HB_P_POPLOCALNEAR, 8,	/* MPERC_QTD */
/* 02059 */ HB_P_LINEOFFSET, 92,	/* 99 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 3, 0,	/* I */
/* 02065 */ HB_P_LINEOFFSET, 94,	/* 101 */
	HB_P_PUSHSYMNEAR, 99,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 50,	/* 50 */
	'P', 'A', 'R', 'A', ' ', 'A', 'L', 'T', 'E', 'R', 'A', 'R', ' ', 'O', ' ', 'P', 'R', 'O', 'D', 'U', 'T', 'O', ' ', '<', 'E', 'N', 'T', 'E', 'R', '>', ' ', '-', ' ', '<', 'E', 'S', 'C', '>', 'p', '/', 'p', 'r', 'o', 's', 'e', 'g', 'u', 'i', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 02124 */ HB_P_LINEOFFSET, 95,	/* 102 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'P', 'r', 'o', 'd', 'u', 't', 'o', 0, 
	HB_P_DOSHORT, 1,
/* 02148 */ HB_P_LINEOFFSET, 96,	/* 103 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 49,	/* 49 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'Q', 'u', 'a', 'n', 't', 'd', '.', 0, 
	HB_P_DOSHORT, 1,
/* 02173 */ HB_P_LINEOFFSET, 97,	/* 104 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 58,	/* 58 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'V', 'a', 'l', 'o', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 02196 */ HB_P_LINEOFFSET, 98,	/* 105 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 69,	/* 69 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'I', 'C', 'M', 39, 'S', 0, 
	HB_P_DOSHORT, 1,
/* 02219 */ HB_P_LINEOFFSET, 99,	/* 106 */
	HB_P_PUSHSYMNEAR, 102,	/* DISPBOX */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 77,	/* 77 */
	HB_P_ONE,
	HB_P_DOSHORT, 5,
/* 02234 */ HB_P_LINEOFFSET, 100,	/* 107 */
	HB_P_PUSHSYMNEAR, 102,	/* DISPBOX */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHBYTE, 77,	/* 77 */
	HB_P_ONE,
	HB_P_DOSHORT, 5,
/* 02249 */ HB_P_LINEOFFSET, 101,	/* 108 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'S', 'u', 'b', ' ', 'T', 'o', 't', 'a', 'l', '_', ':', 0, 
	HB_P_DOSHORT, 1,
/* 02278 */ HB_P_LINEOFFSET, 102,	/* 109 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_PUSHBYTE, 49,	/* 49 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'V', 'l', 'r', '.', 'T', 'o', 't', 'a', 'l', '_', ':', 0, 
	HB_P_DOSHORT, 1,
/* 02308 */ HB_P_LINEOFFSET, 103,	/* 110 */
	HB_P_PUSHSYMNEAR, 102,	/* DISPBOX */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 22,	/* 22 */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_PUSHBYTE, 22,	/* 22 */
	HB_P_PUSHBYTE, 77,	/* 77 */
	HB_P_ONE,
	HB_P_DOSHORT, 5,
/* 02324 */ HB_P_LINEOFFSET, 104,	/* 111 */
	HB_P_PUSHSYMNEAR, 103,	/* JANELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 22,	/* 22 */
	HB_P_ONE,
	HB_P_PUSHSTRSHORT, 37,	/* 37 */
	' ', 'D', 'A', 'D', 'O', 'S', ' ', 'P', 'A', 'R', 'A', ' ', 'N', 'O', 'T', 'A', ' ', 'F', 'I', 'S', 'C', 'A', 'L', ' ', 'D', 'E', ' ', 'C', 'O', 'R', 'R', 'E', 'C', 'A', 'O', ' ', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'D', 0, 
	HB_P_DOSHORT, 5,
/* 02381 */ HB_P_LINEOFFSET, 105,	/* 112 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 23,	/* 23 */
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 31,	/* 31 */
	'B', 'a', 's', 'e', ' ', 'I', 'C', 'M', 'S', '.', '.', '.', '.', '.', '.', '.', ':', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 0, 
	HB_P_DOSHORT, 1,
/* 02429 */ HB_P_LINEOFFSET, 106,	/* 113 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 23,	/* 23 */
	HB_P_PUSHBYTE, 31,	/* 31 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 30,	/* 30 */
	'V', 'l', 'r', '.', 'I', 'C', 'M', 'S', '.', '.', '.', '.', '.', '.', '.', ':', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 0, 
	HB_P_DOSHORT, 1,
/* 02477 */ HB_P_LINEOFFSET, 107,	/* 114 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 31,	/* 31 */
	'B', 'a', 's', 'e', ' ', 'I', 'C', 'M', 'S', ' ', 'S', 'U', 'B', 'S', 'T', '.', ':', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 0, 
	HB_P_DOSHORT, 1,
/* 02525 */ HB_P_LINEOFFSET, 108,	/* 115 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 31,	/* 31 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 30,	/* 30 */
	'V', 'l', 'r', '.', 'I', 'C', 'M', 'S', ' ', 'S', 'U', 'B', 'S', 'T', '.', ':', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 0, 
	HB_P_DOSHORT, 1,
/* 02573 */ HB_P_LINEOFFSET, 109,	/* 116 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 31,	/* 31 */
	'V', 'l', 'r', '.', 'T', 'o', 't', 'a', 'l', ' ', 'I', 'P', 'I', '.', '.', '.', ':', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 0, 
	HB_P_DOSHORT, 1,
/* 02621 */ HB_P_LINEOFFSET, 110,	/* 117 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 26,	/* 26 */
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 31,	/* 31 */
	'V', 'l', 'r', '.', 'T', 'o', 't', 'a', 'l', ' ', 'P', 'r', 'o', 'd', '.', '.', ':', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 0, 
	HB_P_DOSHORT, 1,
/* 02669 */ HB_P_LINEOFFSET, 111,	/* 118 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 26,	/* 26 */
	HB_P_PUSHBYTE, 31,	/* 31 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 30,	/* 30 */
	'V', 'l', 'r', '.', 'T', 'o', 't', 'a', 'l', ' ', 'N', 'O', 'T', 'A', '.', ':', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 0, 
	HB_P_DOSHORT, 1,
/* 02717 */ HB_P_LINEOFFSET, 112,	/* 119 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 76,	/* 76 */
	'Q', 'u', 'a', 'n', 't', 'i', 'd', 'a', 'd', 'e', ' ', 'T', 'O', 'T', 'A', 'L', ':', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'P', 'e', 's', 'o', ' ', 'B', 'r', 'u', 't', 'o', ':', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'L', 'i', 'q', 'u', 'i', 'd', 'o', ':', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 0, 
	HB_P_DOSHORT, 1,
/* 02810 */ HB_P_LINEOFFSET, 113,	/* 120 */
	HB_P_PUSHSYMNEAR, 104,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 02819 */ HB_P_LINEOFFSET, 114,	/* 121 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 105,	/* DEVOUTPICT */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 85, 0,	/* MTOT_NOTA */
	HB_P_PUSHVARIABLE, 36, 0,	/* MTOT_DESC */
	HB_P_PLUS,
	HB_P_PUSHMEMVAR, 106, 0,	/* MFRETE */
	HB_P_PLUS,
	HB_P_PUSHMEMVAR, 107, 0,	/* MSEGURO */
	HB_P_PLUS,
	HB_P_PUSHMEMVAR, 108, 0,	/* MENCARGO */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'9', ',', '9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_DOSHORT, 2,
/* 02869 */ HB_P_LINEOFFSET, 115,	/* 122 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_PUSHBYTE, 61,	/* 61 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 105,	/* DEVOUTPICT */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 85, 0,	/* MTOT_NOTA */
	HB_P_PUSHVARIABLE, 32, 0,	/* MDIF_ICMS */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'9', ',', '9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_DOSHORT, 2,
/* 02907 */ HB_P_LINEOFFSET, 116,	/* 123 */
	HB_P_PUSHSYMNEAR, 104,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 02915 */ HB_P_LINEOFFSET, 118,	/* 125 */
	HB_P_PUSHSYMNEAR, 109,	/* BOTAO1 */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 29,	/* 29 */
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 31,	/* 31 */
	HB_P_PUSHBYTE, 29,	/* 29 */
	HB_P_DOSHORT, 4,
/* 02930 */ HB_P_LINEOFFSET, 119,	/* 126 */
	HB_P_PUSHSYMNEAR, 109,	/* BOTAO1 */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 29,	/* 29 */
	HB_P_PUSHBYTE, 35,	/* 35 */
	HB_P_PUSHBYTE, 31,	/* 31 */
	HB_P_PUSHBYTE, 52,	/* 52 */
	HB_P_DOSHORT, 4,
/* 02945 */ HB_P_LINEOFFSET, 120,	/* 127 */
	HB_P_PUSHSYMNEAR, 104,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_DOSHORT, 1,
/* 02954 */ HB_P_LINEOFFSET, 121,	/* 128 */
	HB_P_PUSHSYMNEAR, 110,	/* __ATPROMPT */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	' ', '1', '-', '>', ' ', 'P', 'r', 'o', 's', 's', 'e', 'g', 'u', 'i', 'r', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 5,
/* 02986 */ HB_P_LINEOFFSET, 122,	/* 129 */
	HB_P_PUSHSYMNEAR, 110,	/* __ATPROMPT */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHBYTE, 36,	/* 36 */
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	' ', ' ', '2', '-', '>', ' ', 'A', 'l', 't', 'e', 'r', 'a', 'r', ' ', ' ', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 5,
/* 03018 */ HB_P_LINEOFFSET, 123,	/* 130 */
	HB_P_PUSHSYMNEAR, 111,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 31,	/* 31 */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'O', 'N', 0, 
	HB_P_DOSHORT, 2,
/* 03032 */ HB_P_LINEOFFSET, 124,	/* 131 */
	HB_P_PUSHSYMNEAR, 112,	/* __MENUTO */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 113,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 03058) */
	HB_P_PUSHVARIABLE, 114, 0,	/* MOP_NOTA */
	HB_P_JUMPNEAR, 8,	/* 8 (abs: 03064) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 114, 0,	/* MOP_NOTA */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 'o', 'p', '_', 'n', 'o', 't', 'a', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 114, 0,	/* MOP_NOTA */
/* 03081 */ HB_P_LINEOFFSET, 125,	/* 132 */
	HB_P_PUSHSYMNEAR, 104,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 03089 */ HB_P_LINEOFFSET, 126,	/* 133 */
	HB_P_PUSHSYMNEAR, 115,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 03104) */
	HB_P_JUMP, 152, 5,	/* 1432 (abs: 04533) */
/* 03104 */ HB_P_LINEOFFSET, 129,	/* 136 */
	HB_P_PUSHVARIABLE, 114, 0,	/* MOP_NOTA */
	HB_P_ONE,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 03116) */
	HB_P_JUMP, 140, 5,	/* 1420 (abs: 04533) */
/* 03116 */ HB_P_LINEOFFSET, 132,	/* 139 */
	HB_P_PUSHSYMNEAR, 104,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 116,	/* ACHOICE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 19,	/* 19 */
	HB_P_PUSHBYTE, 77,	/* 77 */
	HB_P_PUSHVARIABLE, 20, 0,	/* M_ALTERA */
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPVARIABLE, 37, 0,	/* POINT */
	HB_P_PUSHSYMNEAR, 104,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 03149 */ HB_P_LINEOFFSET, 133,	/* 140 */
	HB_P_PUSHSYMNEAR, 115,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 03164) */
	HB_P_JUMP, 184, 251,	/* -1096 (abs: 02065) */
/* 03164 */ HB_P_LINEOFFSET, 136,	/* 143 */
	HB_P_PUSHSYMNEAR, 115,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 11,	/* 11 (abs: 03186) */
	HB_P_PUSHSYMNEAR, 115,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 19,	/* 19 */
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSE, 103, 1,	/* 359 (abs: 03545) */
/* 03189 */ HB_P_LINEOFFSET, 137,	/* 144 */
	HB_P_PUSHSYMNEAR, 117,	/* SAVESCREEN */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 6,	/* MTELA_PROD */
/* 03204 */ HB_P_LINEOFFSET, 138,	/* 145 */
	HB_P_PUSHSYMNEAR, 77,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHBYTE, 35,	/* 35 */
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	' ', 'C', 'o', 'n', 's', 'u', 'l', 't', 'a', ' ', 'P', 'r', 'o', 'd', 'u', 't', 'o', ' ', 0, 
	HB_P_DOSHORT, 5,
/* 03240 */ HB_P_LINEOFFSET, 139,	/* 146 */
	HB_P_LOCALNEARSETINT, 5, 0, 0,	/* MACHOU 0*/
	HB_P_PUSHLOCALNEAR, 5,	/* MACHOU */
	HB_P_POPLOCALNEAR, 4,	/* MCODIGO_AUX */
/* 03250 */ HB_P_LINEOFFSET, 140,	/* 147 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'D', 'i', 'g', 'i', 't', 'e', ' ', 'o', ' ', 'C', 'o', 'd', 'i', 'g', 'o', ':', 0, 
	HB_P_DOSHORT, 1,
/* 03283 */ HB_P_LINEOFFSET, 141,	/* 148 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 18,	/* 18 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 119,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	4, 0,	/* MCODIGO_AUX */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 03321) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 03326) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'm', 'c', 'o', 'd', 'i', 'g', 'o', '_', 'a', 'u', 'x', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'9', '9', '9', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 03367 */ HB_P_LINEOFFSET, 142,	/* 149 */
	HB_P_PUSHSYMNEAR, 121,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 74, 0,	/* GETLIST */
/* 03389 */ HB_P_LINEOFFSET, 143,	/* 150 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 3, 0,	/* I */
/* 03395 */ HB_P_LINEOFFSET, 144,	/* 151 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 3, 0,	/* I */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_PUSHSYMNEAR, 89,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 20, 0,	/* M_ALTERA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 58,	/* 58 (abs: 03471) */
/* 03415 */ HB_P_LINEOFFSET, 145,	/* 152 */
	HB_P_PUSHSYMNEAR, 122,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* MCODIGO_AUX */
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHSYMNEAR, 123,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 20, 0,	/* M_ALTERA */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 03460) */
/* 03444 */ HB_P_LINEOFFSET, 146,	/* 153 */
	HB_P_LOCALNEARSETINT, 5, 1, 0,	/* MACHOU 1*/
/* 03450 */ HB_P_LINEOFFSET, 147,	/* 154 */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_POPVARIABLE, 37, 0,	/* POINT */
	HB_P_JUMPNEAR, 13,	/* 13 (abs: 03471) */
/* 03460 */ HB_P_LINEOFFSET, 150,	/* 157 */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_INC,
	HB_P_POPVARIABLE, 3, 0,	/* I */
	HB_P_JUMPNEAR, 188,	/* -68 (abs: 03401) */
/* 03471 */ HB_P_LINEOFFSET, 151,	/* 158 */
	HB_P_PUSHLOCALNEAR, 5,	/* MACHOU */
	HB_P_ZERO,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 61,	/* 61 (abs: 03538) */
/* 03479 */ HB_P_LINEOFFSET, 152,	/* 159 */
	HB_P_PUSHSYMNEAR, 97,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 40,	/* 40 */
	'N', 'a', 'o', ' ', 'f', 'o', 'i', ' ', 'p', 'o', 's', 's', 'i', 'v', 'e', 'l', ' ', 'e', 'n', 'c', 'o', 'n', 't', 'r', 'a', 'r', ' ', 'e', 's', 't', 'e', ' ', 'P', 'r', 'o', 'd', 'u', 't', 'o', 0, 
	HB_P_DOSHORT, 1,
/* 03528 */ HB_P_LINEOFFSET, 153,	/* 160 */
	HB_P_PUSHSYMNEAR, 98,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMP, 66, 250,	/* -1470 (abs: 02065) */
/* 03538 */ HB_P_LINEOFFSET, 156,	/* 163 */
	HB_P_PUSHSYMNEAR, 98,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 03545 */ HB_P_LINEOFFSET, 158,	/* 165 */
	HB_P_PUSHSYMNEAR, 77,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 16,	/* 16 */
	HB_P_PUSHBYTE, 76,	/* 76 */
	HB_P_PUSHSTRSHORT, 23,	/* 23 */
	' ', 'A', 'l', 't', 'e', 'r', 'a', 'c', 'a', 'o', ' ', 'd', 'e', ' ', 'P', 'r', 'o', 'd', 'u', 't', 'o', ' ', 0, 
	HB_P_DOSHORT, 5,
/* 03585 */ HB_P_LINEOFFSET, 159,	/* 166 */
	HB_P_PUSHSYMNEAR, 104,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 03594 */ HB_P_LINEOFFSET, 160,	/* 167 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'C', 'o', 'd', 'i', 'g', 'o', '.', '.', '.', '.', ':', ' ', 0, 
	HB_P_DOSHORT, 1,
/* 03623 */ HB_P_LINEOFFSET, 161,	/* 168 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'D', 'e', 's', 'c', 'r', 'i', 'c', 'a', 'o', '.', ':', 0, 
	HB_P_DOSHORT, 1,
/* 03652 */ HB_P_LINEOFFSET, 162,	/* 169 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'Q', 'u', 'a', 'n', 't', 'i', 'd', 'a', 'd', 'e', ':', 0, 
	HB_P_DOSHORT, 1,
/* 03681 */ HB_P_LINEOFFSET, 163,	/* 170 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'V', 'a', 'l', 'o', 'r', '.', '.', '.', '.', '.', ':', 0, 
	HB_P_DOSHORT, 1,
/* 03710 */ HB_P_LINEOFFSET, 164,	/* 171 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'I', 'C', 'M', '.', '.', '.', '.', '.', '.', '.', ':', 0, 
	HB_P_DOSHORT, 1,
/* 03739 */ HB_P_LINEOFFSET, 165,	/* 172 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'U', 'n', 'i', 'd', 'a', 'd', 'e', '.', '.', '.', ':', 0, 
	HB_P_DOSHORT, 1,
/* 03768 */ HB_P_LINEOFFSET, 166,	/* 173 */
	HB_P_PUSHSYMNEAR, 104,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 03776 */ HB_P_LINEOFFSET, 167,	/* 174 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 124, 0,	/* CONS_MERC */
/* 03784 */ HB_P_LINEOFFSET, 168,	/* 175 */
	HB_P_MESSAGE, 125, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 126,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 40,	/* 40 */
	'S', 'E', 'L', 'E', 'C', 'T', ' ', '*', ' ', 'F', 'R', 'O', 'M', ' ', 's', 'a', 'c', 'm', 'e', 'r', 'c', ' ', 'W', 'H', 'E', 'R', 'E', ' ', 'c', 'o', 'd', '_', 'm', 'e', 'r', 'c', ' ', '=', ' ', 0, 
	HB_P_PUSHSYMNEAR, 127,	/* SR_CDBVALUE */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHMEMVAR, 27, 0,	/* M_POS */
	HB_P_PUSHVARIABLE, 37, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHMEMVARREF, 124, 0,	/* CONS_MERC */
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 03867 */ HB_P_LINEOFFSET, 169,	/* 176 */
	HB_P_MESSAGE, 125, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 126,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'O', 'M', 'M', 'I', 'T', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 03891 */ HB_P_LINEOFFSET, 170,	/* 177 */
	HB_P_PUSHSYMNEAR, 89,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 124, 0,	/* CONS_MERC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ZERO,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 50,	/* 50 (abs: 03953) */
/* 03905 */ HB_P_LINEOFFSET, 171,	/* 178 */
	HB_P_PUSHSYMNEAR, 97,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 36,	/* 36 */
	'C', 'o', 'd', 'i', 'g', 'o', ' ', 'd', 'a', ' ', 'm', 'e', 'r', 'c', 'a', 'd', 'o', 'r', 'i', 'a', ' ', 'n', 'a', 'o', ' ', 'c', 'a', 'd', 'a', 's', 't', 'r', 'a', 'd', 'o', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 163, 248,	/* -1885 (abs: 02065) */
/* 03953 */ HB_P_LINEOFFSET, 175,	/* 182 */
	HB_P_PUSHSYMNEAR, 100,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 101,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHMEMVAR, 27, 0,	/* M_POS */
	HB_P_PUSHVARIABLE, 37, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_ARRAYPUSH,
	HB_P_DOSHORT, 1,
/* 03985 */ HB_P_LINEOFFSET, 176,	/* 183 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 128,	/* __GETA */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', '_', 'n', 'o', 'r', 'm', 'a', 'l', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 16,	/* 16 */
	HB_P_PUSHMEMVAR, 124, 0,	/* CONS_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_EQUAL,
	HB_P_ENDBLOCK,
	HB_P_PUSHMEMVAR, 27, 0,	/* M_POS */
	HB_P_PUSHVARIABLE, 37, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_FUNCTIONSHORT, 6,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 04075 */ HB_P_LINEOFFSET, 177,	/* 184 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 128,	/* __GETA */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', '_', 'n', 'o', 'r', 'm', 'a', 'l', 0, 
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'9', '9', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 27, 0,	/* M_POS */
	HB_P_PUSHVARIABLE, 37, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_FUNCTIONSHORT, 6,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 04156 */ HB_P_LINEOFFSET, 178,	/* 185 */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHMEMVAR, 27, 0,	/* M_POS */
	HB_P_PUSHVARIABLE, 37, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_ZERO,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 23,	/* 23 (abs: 04200) */
	HB_P_ZERO,
	HB_P_DUPLICATE,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHMEMVAR, 27, 0,	/* M_POS */
	HB_P_PUSHVARIABLE, 37, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_ARRAYPOP,
	HB_P_JUMPNEAR, 19,	/* 19 (abs: 04217) */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHMEMVAR, 27, 0,	/* M_POS */
	HB_P_PUSHVARIABLE, 37, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_ARRAYPUSH,
	HB_P_POP,
/* 04218 */ HB_P_LINEOFFSET, 179,	/* 186 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 128,	/* __GETA */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', '_', 'n', 'o', 'r', 'm', 'a', 'l', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'9', '9', '9', '9', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 22,	/* 22 */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHMEMVAR, 27, 0,	/* M_POS */
	HB_P_PUSHVARIABLE, 37, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_ENDBLOCK,
	HB_P_PUSHMEMVAR, 27, 0,	/* M_POS */
	HB_P_PUSHVARIABLE, 37, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_FUNCTIONSHORT, 6,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 04322 */ HB_P_LINEOFFSET, 180,	/* 187 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 128,	/* __GETA */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', '_', 'n', 'o', 'r', 'm', 'a', 'l', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHBLOCKSHORT, 31,	/* 31 */
	HB_P_PUSHSYMNEAR, 91,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHMEMVAR, 27, 0,	/* M_POS */
	HB_P_PUSHVARIABLE, 37, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 14,	/* 14 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 04393) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 04394) */
	HB_P_TRUE,
	HB_P_ENDBLOCK,
	HB_P_PUSHBLOCKSHORT, 16,	/* 16 */
	HB_P_PUSHMEMVAR, 124, 0,	/* CONS_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_EQUAL,
	HB_P_ENDBLOCK,
	HB_P_PUSHMEMVAR, 27, 0,	/* M_POS */
	HB_P_PUSHVARIABLE, 37, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 14,	/* 14 */
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_FUNCTIONSHORT, 6,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 04442 */ HB_P_LINEOFFSET, 181,	/* 188 */
	HB_P_PUSHSYMNEAR, 121,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 74, 0,	/* GETLIST */
/* 04464 */ HB_P_LINEOFFSET, 182,	/* 189 */
	HB_P_PUSHSYMNEAR, 98,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 04471 */ HB_P_LINEOFFSET, 183,	/* 190 */
	HB_P_PUSHSYMNEAR, 115,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 04486) */
	HB_P_JUMP, 142, 246,	/* -2418 (abs: 02065) */
/* 04486 */ HB_P_LINEOFFSET, 186,	/* 193 */
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHMEMVAR, 27, 0,	/* M_POS */
	HB_P_PUSHVARIABLE, 37, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_ZERO,
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 118, 246,	/* -2442 (abs: 02065) */
/* 04510 */ HB_P_LINEOFFSET, 187,	/* 194 */
	HB_P_ZERO,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHMEMVAR, 27, 0,	/* M_POS */
	HB_P_PUSHVARIABLE, 37, 0,	/* POINT */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_ARRAYPOP,
	HB_P_JUMP, 95, 246,	/* -2465 (abs: 02065) */
/* 04533 */ HB_P_LINEOFFSET, 193,	/* 200 */
	HB_P_PUSHSYMNEAR, 115,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 14,	/* 14 (abs: 04557) */
/* 04545 */ HB_P_LINEOFFSET, 194,	/* 201 */
	HB_P_PUSHSYMNEAR, 98,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 04552 */ HB_P_LINEOFFSET, 195,	/* 202 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 04557 */ HB_P_LINEOFFSET, 200,	/* 207 */
	HB_P_PUSHMEMVAR, 88, 0,	/* MTIPO_NOTA */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'C', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 9, 3,	/* 777 (abs: 05344) */
/* 04570 */ HB_P_LINEOFFSET, 201,	/* 208 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 62, 0,	/* CTOT_QUANTD */
/* 04576 */ HB_P_LINEOFFSET, 202,	/* 209 */
	HB_P_PUSHLOCALNEAR, 1,	/* MV */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'2', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 83,	/* 83 (abs: 04668) */
/* 04587 */ HB_P_LINEOFFSET, 203,	/* 210 */
	HB_P_PUSHSYMNEAR, 129,	/* TOTNT */
	HB_P_PUSHALIASEDFIELDNEAR, 130,	/* VL_BASE */
	HB_P_POPVARIABLE, 63, 0,	/* CBASE_ICM */
/* 04596 */ HB_P_LINEOFFSET, 204,	/* 211 */
	HB_P_PUSHSYMNEAR, 129,	/* TOTNT */
	HB_P_PUSHALIASEDFIELDNEAR, 131,	/* VL_ICM */
	HB_P_POPVARIABLE, 64, 0,	/* CTOT_ICM */
/* 04605 */ HB_P_LINEOFFSET, 205,	/* 212 */
	HB_P_PUSHSYMNEAR, 129,	/* TOTNT */
	HB_P_PUSHALIASEDFIELDNEAR, 132,	/* BASE_ICMSU */
	HB_P_POPVARIABLE, 65, 0,	/* CBASE_ICMF */
/* 04614 */ HB_P_LINEOFFSET, 206,	/* 213 */
	HB_P_PUSHSYMNEAR, 129,	/* TOTNT */
	HB_P_PUSHALIASEDFIELDNEAR, 133,	/* VL_ICMSU */
	HB_P_POPVARIABLE, 66, 0,	/* CTOT_ICMF */
/* 04623 */ HB_P_LINEOFFSET, 207,	/* 214 */
	HB_P_PUSHSYMNEAR, 129,	/* TOTNT */
	HB_P_PUSHALIASEDFIELDNEAR, 134,	/* IPI */
	HB_P_POPVARIABLE, 67, 0,	/* CTOT_IPI */
/* 04632 */ HB_P_LINEOFFSET, 208,	/* 215 */
	HB_P_PUSHSYMNEAR, 129,	/* TOTNT */
	HB_P_PUSHALIASEDFIELDNEAR, 135,	/* VL_PROD */
	HB_P_POPVARIABLE, 68, 0,	/* CTOT_PROD */
/* 04641 */ HB_P_LINEOFFSET, 209,	/* 216 */
	HB_P_PUSHSYMNEAR, 129,	/* TOTNT */
	HB_P_PUSHALIASEDFIELDNEAR, 136,	/* VL_NOTA */
	HB_P_POPVARIABLE, 69, 0,	/* CTOT_NOTA */
/* 04650 */ HB_P_LINEOFFSET, 210,	/* 217 */
	HB_P_PUSHSYMNEAR, 129,	/* TOTNT */
	HB_P_PUSHALIASEDFIELDNEAR, 137,	/* PESO */
	HB_P_POPVARIABLE, 70, 0,	/* CTOT_PESO */
/* 04659 */ HB_P_LINEOFFSET, 211,	/* 218 */
	HB_P_PUSHSYMNEAR, 129,	/* TOTNT */
	HB_P_PUSHALIASEDFIELDNEAR, 138,	/* PESO_LIQ */
	HB_P_POPVARIABLE, 71, 0,	/* CTOT_LIQ */
/* 04668 */ HB_P_LINEOFFSET, 213,	/* 220 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 23,	/* 23 */
	HB_P_PUSHBYTE, 18,	/* 18 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 119,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'c', 'b', 'a', 's', 'e', '_', 'i', 'c', 'm', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'9', ',', '9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 04734 */ HB_P_LINEOFFSET, 214,	/* 221 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 23,	/* 23 */
	HB_P_PUSHBYTE, 48,	/* 48 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 119,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'c', 't', 'o', 't', '_', 'i', 'c', 'm', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'9', ',', '9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 04799 */ HB_P_LINEOFFSET, 215,	/* 222 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 18,	/* 18 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 119,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'c', 'b', 'a', 's', 'e', '_', 'i', 'c', 'm', 'f', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'9', ',', '9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 04866 */ HB_P_LINEOFFSET, 216,	/* 223 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 48,	/* 48 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 119,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'c', 't', 'o', 't', '_', 'i', 'c', 'm', 'f', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'9', ',', '9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 04932 */ HB_P_LINEOFFSET, 217,	/* 224 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 18,	/* 18 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 119,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'c', 't', 'o', 't', '_', 'i', 'p', 'i', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'9', ',', '9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 04997 */ HB_P_LINEOFFSET, 218,	/* 225 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 26,	/* 26 */
	HB_P_PUSHBYTE, 18,	/* 18 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 119,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'c', 't', 'o', 't', '_', 'p', 'r', 'o', 'd', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'9', ',', '9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 05063 */ HB_P_LINEOFFSET, 219,	/* 226 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 26,	/* 26 */
	HB_P_PUSHBYTE, 48,	/* 48 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 119,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'c', 't', 'o', 't', '_', 'n', 'o', 't', 'a', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'9', ',', '9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 05129 */ HB_P_LINEOFFSET, 220,	/* 227 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_PUSHBYTE, 18,	/* 18 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 119,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'c', 't', 'o', 't', '_', 'q', 'u', 'a', 'n', 't', 'd', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 05195 */ HB_P_LINEOFFSET, 221,	/* 228 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_PUSHBYTE, 42,	/* 42 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 119,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'c', 't', 'o', 't', '_', 'p', 'e', 's', 'o', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 05259 */ HB_P_LINEOFFSET, 222,	/* 229 */
	HB_P_PUSHSYMNEAR, 118,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_PUSHBYTE, 63,	/* 63 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 94,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 119,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'c', 't', 'o', 't', '_', 'l', 'i', 'q', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 120, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 05322 */ HB_P_LINEOFFSET, 223,	/* 230 */
	HB_P_PUSHSYMNEAR, 121,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 74, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 74, 0,	/* GETLIST */
/* 05344 */ HB_P_LINE, 187, 1,	/* 443 */
	HB_P_PUSHSYMNEAR, 73,	/* READKILL */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_DOSHORT, 1,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 74, 0,	/* GETLIST */
/* 05359 */ HB_P_LINE, 188, 1,	/* 444 */
	HB_P_PUSHSYMNEAR, 139,	/* SACNF_E */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 90, 0,	/* M_NORMAL */
	HB_P_PUSHLOCALNEAR, 1,	/* MV */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'I', 'C', 'M', ' ', 'N', 'O', 'R', 'M', 'A', 'L', 0, 
	HB_P_DOSHORT, 3,
/* 05385 */ HB_P_LINE, 192, 1,	/* 448 */
	HB_P_PUSHSYMNEAR, 140,	/* __MVXRELEASE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'm', 'o', 'p', 'c', 'a', 'o', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'o', 'p', 'c', 'a', 'o', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'i', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'p', 'o', 'd', 'e', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'f', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'm', 't', 'r', 'a', 'c', 'o', 0, 
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'm', 'c', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'm', 'd', 'e', 's', 'c', 'r', 'i', 'c', 'a', 'o', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'm', '_', 'a', 'c', 'u', 'c', 'a', 'r', ':', '=', '{', '}', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'm', 'b', 'a', 's', 'e', '_', 'i', 'c', 'm', 'f', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'm', 't', 'o', 't', '_', 'i', 'c', 'm', 'f', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'm', 'b', 'a', 's', 'e', '_', 'i', 'c', 'm', 0, 
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 't', 'o', 't', '_', 'i', 'c', 'm', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'm', 's', 'a', 'l', 'd', 'o', '_', 'a', 't', 'u', 0, 
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 'e', 'x', 't', 'e', 'n', 's', 'o', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'l', 'i', 'n', '1', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'l', 'i', 'n', '2', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'm', 'l', 'i', 'n', '1', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'm', 'l', 'i', 'n', '2', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'm', 'l', 'i', 'n', '3', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'm', 'l', 'i', 'n', '4', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'm', 'l', 'i', 'n', '5', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'm', 'l', 'i', 'n', '6', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'm', 't', 'o', 't', '_', 'p', 'e', 's', 'o', 0, 
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 't', 'o', 't', '_', 'l', 'i', 'q', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'm', '_', 'a', 'l', 't', 'e', 'r', 'a', ':', '=', '{', '}', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	't', 'e', 'l', 'a', '2', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'm', 'p', 'a', 'g', 0, 
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 'd', 'o', 'c', '_', 'a', 'u', 'x', 0, 
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 't', 'o', 't', '_', 'a', 'u', 'x', 0, 
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 'c', 'o', 'd', '_', 'f', 'a', 't', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'm', 'l', 'i', 'n', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'm', '_', 'p', 'o', 's', ':', '=', '{', '}', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'm', 'p', 'o', 's', 0, 
	HB_P_DOSHORT, 34,
/* 05718 */ HB_P_LINE, 193, 1,	/* 449 */
	HB_P_PUSHSYMNEAR, 98,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 05726 */ HB_P_LINE, 194, 1,	/* 450 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 05732 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

