INSERT INTO sacncmcest (CEST, CODIGO, DESCRI) VALUES ('0104300', '84254200', 'Macacos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0104400', '84311010', 'Partes para macacos do item 43.0');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0104500', '8431492', 'Partes reconheciveis como exclusiva ou principalmente destinadas as maquinas agricolas ou rodoviarias');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0104500', '84339090', 'Partes reconheciveis como exclusiva ou principalmente destinadas as maquinas agricolas ou rodoviarias');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0104600', '84811000', 'Valvulas redutoras de pressao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0104700', '84812', 'Valvulas para transmissao oleo-hidraulicas ou pneumaticas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0104800', '84818092', 'Valvulas solenoides');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0104900', '8482', 'Rolamentos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0105000', '8483', 'arvores de transmissao (incluidas as arvores de "cames" e virabrequins) e manivelas mancais e "bronzes"');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0105100', '8484', 'Juntas metaloplasticas jogos ou sortidos de juntas de composicoes diferentes, apresentados em bolsas, envelopes ou embalagens semelhantes juntas de vedacao mecanicas (selos mecanicos)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0105200', '850520', 'Acoplamentos, embreagens, variadores de velocidade e freios, eletromagneticos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0105300', '85071000', 'Acumuladores eletricos de chumbo, do tipo utilizado para o arranque dos motores de pistao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0105400', '8511', 'Aparelhos e dispositivos eletricos de ignicao ou de arranque para motores de ignicao por centelha ou por compressao (por exemplo, magnetos, dinamos-magnetos, bobinas de ignicao, velas de ignicao ou de aquecimento, motores de arranque geradores (dinamos e alternadores, por exemplo) e conjuntores-disjuntores utilizados com estes motores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0105500', '851220', 'Aparelhos eletricos de iluminacao ou de sinalizacao (exceto os da posicao 8539), limpadores de para-brisas, degeladores e desembacadores (desembaciadores) eletricos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0105500', '851240', 'Aparelhos eletricos de iluminacao ou de sinalizacao (exceto os da posicao 8539), limpadores de para-brisas, degeladores e desembacadores (desembaciadores) eletricos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0105500', '85129000', 'Aparelhos eletricos de iluminacao ou de sinalizacao (exceto os da posicao 8539), limpadores de para-brisas, degeladores e desembacadores (desembaciadores) eletricos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0105600', '85171213', 'Telefones moveis');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0105700', '8518', 'Alto-falantes, amplificadores eletricos de audiofrequencia e partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0105800', '85185000', 'Aparelhos eletricos de amplificacao de som para veiculos automotores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0105900', '851981', 'Aparelhos de reproducao de som');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0106000', '8525501', 'Aparelhos transmissores (emissores) de radiotelefonia ou radiotelegrafia (radio receptor/transmissor)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0106000', '85256010', 'Aparelhos transmissores (emissores) de radiotelefonia ou radiotelegrafia (radio receptor/transmissor)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0106100', '85272', 'Aparelhos receptores de radiodifusao que so funcionam com fonte externa de energia, exceto os classificados na posicao 8527.21.90');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0106200', '85272190', 'Outros aparelhos receptores de radiodifusao que funcionem com fonte externa de energia outros aparelhos videofônicos de gravacao ou de reproducao, mesmo incorporando um receptor de sinais videofônicos, dos tipos utilizados exclusivamente em veiculos automotores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0106200', '85219090', 'Outros aparelhos receptores de radiodifusao que funcionem com fonte externa de energia outros aparelhos videofônicos de gravacao ou de reproducao, mesmo incorporando um receptor de sinais videofônicos, dos tipos utilizados exclusivamente em veiculos automotores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0106300', '85291090', 'Antenas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0106400', '85340000', 'Circuitos impressos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0106500', '853530', 'Interruptores e seccionadores e comutadores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0106500', '853650', 'Interruptores e seccionadores e comutadores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0106600', '85361000', 'Fusiveis e corta-circuitos de fusiveis');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0106700', '85362000', 'Disjuntores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0106800', '85364', 'Reles');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0106900', '8538', 'Partes reconheciveis como exclusivas ou principalmente destinados aos aparelhos dos itens 65.0, 66.0, 67.0 e 68.0');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0107000', '85365090', 'Interruptores, seccionadores e comutadores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0107100', '853910', 'Farois e projetores, em unidades seladas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0107200', '85392', 'Lampadas e tubos de incandescencia, exceto de raios ultravioleta ou infravermelhos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0107300', '85442000', 'Cabos coaxiais e outros condutores eletricos coaxiais');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0107400', '85443000', 'Jogos de fios para velas de ignicao e outros jogos de fios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0107500', '8707', 'Carrocarias para os veiculos automoveis das posicoes 8701 a 8705, incluidas as cabinas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0107600', '8708', 'Partes e acessorios dos veiculos automoveis das posicoes 8701 a 8705');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0107700', '87141', 'Parte e acessorios de motocicletas (incluidos os ciclomotores)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0107800', '87169090', 'Engates para reboques e semi-reboques');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0107900', '902610', 'Medidores de nivel Medidores de vazao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0108000', '902620', 'Aparelhos para medida ou controle da pressao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0108100', '9029', 'Contadores, indicadores de velocidade e tacômetros, suas partes e acessorios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0108200', '90303321', 'Amperimetros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0108300', '90318040', 'Aparelhos digitais, de uso em veiculos automoveis, para medida e indicacao de multiplas grandezas tais como: velocidade media, consumos instantaneo e medio e autonomia (computador de bordo)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0108400', '9032892', 'Controladores eletrônicos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0108500', '91040000', 'Relogios para paineis de instrumentos e relogios semelhantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0108600', '94012000', 'Assentos e partes de assentos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0108600', '94019090', 'Assentos e partes de assentos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0108700', '96138000', 'Acendedores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0108800', '4009', 'Tubos de borracha vulcanizada nao endurecida, mesmo providos de seus acessorios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0108900', '45049000', 'Juntas de vedacao de cortica natural e de amianto');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0108900', '68129910', 'Juntas de vedacao de cortica natural e de amianto');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109000', '48234000', 'Papel-diagrama para tacografo, em disco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109100', '39191000', 'Fitas, tiras, adesivos, auto-colantes, de plastico, refletores, mesmo em rolos placas metalicas com pelicula de plastico refletora, proprias para colocacao em carrocerias, para-choques de veiculos de carga, motocicletas, ciclomotores, capacetes, bones de agentes de transito e de condutores de veiculos, atuando como dispositivos refletivos de seguranca rodoviarios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109100', '39199000', 'Fitas, tiras, adesivos, auto-colantes, de plastico, refletores, mesmo em rolos placas metalicas com pelicula de plastico refletora, proprias para colocacao em carrocerias, para-choques de veiculos de carga, motocicletas, ciclomotores, capacetes, bones de agentes de transito e de condutores de veiculos, atuando como dispositivos refletivos de seguranca rodoviarios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109100', '87082999', 'Fitas, tiras, adesivos, auto-colantes, de plastico, refletores, mesmo em rolos placas metalicas com pelicula de plastico refletora, proprias para colocacao em carrocerias, para-choques de veiculos de carga, motocicletas, ciclomotores, capacetes, bones de agentes de transito e de condutores de veiculos, atuando como dispositivos refletivos de seguranca rodoviarios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109200', '84123110', 'Cilindros pneumaticos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109300', '84131900', 'Bomba eletrica de lavador de para-brisa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109300', '84135090', 'Bomba eletrica de lavador de para-brisa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109300', '84138100', 'Bomba eletrica de lavador de para-brisa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109400', '84136019', 'Bomba de assistencia de direcao hidraulica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109400', '84137010', 'Bomba de assistencia de direcao hidraulica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109500', '84145910', 'Motoventiladores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109500', '84145990', 'Motoventiladores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109600', '84213990', 'Filtros de polen do ar-condicionado');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109700', '85011019', '"Maquina" de vidro eletrico de porta');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109800', '85013110', 'Motor de limpador de para-brisa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0109900', '85045000', 'Bobinas de reatancia e de auto-inducao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0110000', '850720', 'Baterias de chumbo e de niquel-cadmio');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0110000', '850730', 'Baterias de chumbo e de niquel-cadmio');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0110100', '85123000', 'Aparelhos de sinalizacao acustica (buzina)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0110200', '9032898', 'Instrumentos para regulacao de grandezas nao eletricas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0110200', '9032899', 'Instrumentos para regulacao de grandezas nao eletricas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0110300', '90271000', 'Analisadores de gases ou de fumaca (sonda lambda)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0110400', '40081100', 'Perfilados de borracha vulcanizada nao endurecida');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0110500', '56012219', 'Artefatos de pasta de fibra de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0110600', '57032000', 'Tapetes/carpetes - nailon');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0110700', '57033000', 'Tapetes de materias texteis sinteticas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0110800', '59119000', 'Forracao interior capacete');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0110900', '69039099', 'Outros para-brisas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0111000', '70072900', 'Moldura com espelho');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0111100', '73145000', 'Corrente de transmissao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0111200', '73151100', 'Corrente transmissao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0111300', '73151210', 'Outras correntes de transmissao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0111400', '84189900', 'Condensador tubular metalico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0111500', '841950', 'Trocadores de calor');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0111600', '84249090', 'Partes de aparelhos mecanicos de pulverizar ou dispersar');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0111700', '84254910', 'Macacos manuais para veiculos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0111800', '84314100', 'Cacambas, pas, ganchos e tenazes para maquinas rodoviarias');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0111900', '85016100', 'Geradores de corrente alternada de potencia nao superior a 75 kva');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0112000', '85311090', 'Aparelhos eletricos para alarme de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0112100', '90141000', 'Bussolas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0112200', '90251990', 'Indicadores de temperatura');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0112300', '90259010', 'Partes de indicadores de temperatura');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0112400', '902690', 'Partes de aparelhos de medida ou controle');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0112500', '90321010', 'Termostatos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0112600', '90321090', 'Instrumentos e aparelhos para regulacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0112700', '90322000', 'Pressostatos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0112800', '871690', 'Pecas para reboques e semi-reboques');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0112900', '', 'Outras pecas, partes e acessorios para veiculos automotores nao relacionados nos demais itens deste anexo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200100', '2205', 'Aperitivos, amargos, bitter e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200100', '22089000', 'Aperitivos, amargos, bitter e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200200', '22089000', 'Batida e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200300', '22089000', 'Bebida ice');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200400', '220720', 'Cachaca e aguardentes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200400', '22084000', 'Cachaca e aguardentes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200500', '2205', 'Catuaba e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200500', '22060090', 'Catuaba e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200500', '22089000', 'Catuaba e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200600', '22082000', 'Conhaque, brandy e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200700', '22060090', 'Cooler');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200700', '22089000', 'Cooler');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200800', '22085000', 'Gim (gin) e genebra');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200900', '2205', 'Jurubeba e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200900', '22060090', 'Jurubeba e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0200900', '22089000', 'Jurubeba e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0201000', '22087000', 'Licores e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0201100', '22082000', 'Pisco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0201200', '22084000', 'Rum');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0201300', '22060090', 'Saque');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0201400', '22089000', 'Steinhaeger');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0201500', '22089000', 'Tequila');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0201600', '220830', 'Uisque');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0201700', '2205', 'Vermute e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0201800', '22086000', 'Vodka');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0201900', '22089000', 'Derivados de vodka');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0202000', '22089000', 'Arak');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0202100', '22082000', 'Aguardente vinica / grappa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0202200', '22060010', 'Sidra e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0202300', '2205', 'Sangrias e coqueteis');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0202300', '22060090', 'Sangrias e coqueteis');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0202300', '22089000', 'Sangrias e coqueteis');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0202400', '2204', 'Vinhos e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0202500', '2204', 'Outras bebidas alcoolicas nao especificadas nos itens anteriores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0202500', '2205', 'Outras bebidas alcoolicas nao especificadas nos itens anteriores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0202500', '2206', 'Outras bebidas alcoolicas nao especificadas nos itens anteriores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0202500', '2207', 'Outras bebidas alcoolicas nao especificadas nos itens anteriores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0202500', '2208', 'Outras bebidas alcoolicas nao especificadas nos itens anteriores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0300100', '2201', 'agua mineral, gasosa ou nao, ou potavel, naturais, em garrafa de vidro, retornavel ou nao, com capacidade de ate 500 ml');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0300200', '2201', 'agua mineral, gasosa ou nao, ou potavel, naturais, em embalagem com capacidade igual ou superior a 5.000 ml');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0300300', '2201', 'agua mineral, gasosa ou nao, ou potavel, naturais, em embalagem de vidro, nao retornavel, com capacidade de ate 300 ml');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0300400', '2201', 'agua mineral, gasosa ou nao, ou potavel, naturais, em garrafa plastica de 1.500 ml');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0300500', '2201', 'agua mineral, gasosa ou nao, ou potavel, naturais, em copos plasticos e embalagem plastica com capacidade de ate 500 ml');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0300600', '2201', 'Outras aguas minerais, gasosa ou nao, ou potavel, naturais, inclusive gaseificada ou aromatizada artificialmente');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0300600', '2202', 'Outras aguas minerais, gasosa ou nao, ou potavel, naturais, inclusive gaseificada ou aromatizada artificialmente');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0300700', '2202', 'Refrigerante em garrafa com capacidade igual ou superior a 600 ml');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0300800', '2202', 'Demais refrigerantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0300900', '21069010', 'Xarope ou extrato concentrado destinados ao preparo de refrigerante em maquina "pre-mix"ou "post-mix"');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0301000', '22029000', 'Bebidas energeticas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0301100', '210690', 'Bebidas hidroeletroliticas (isotônicas)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0301200', '22030000', 'Cerveja');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0301300', '22029000', 'Cerveja sem alcool');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0301400', '22030000', 'Chope');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0400100', '2402', 'Charutos, cigarrilhas e cigarros, de tabaco ou dos seus sucedaneos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0400200', '24031', 'Tabaco para fumar, mesmo contendo sucedaneos de tabaco em qualquer proporcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0500100', '2523', 'Cimento');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0600100', '220710', 'alcool etilico nao desnaturado, com um teor alcoolico em volume igual ou superior a 80% vol (alcool etilico anidro combustivel e alcool etilico hidratado combustivel)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0600200', '2710125', 'Gasolinas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0600300', '2710191', 'Querosenes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0600400', '2710192', 'oleos combustiveis');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0600500', '2710193', 'oleos lubrificantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0600600', '2710199', 'Outros oleos de petroleo ou de minerais betuminosos (exceto oleos brutos) e preparacoes nao especificadas nem compreendidas noutras posicoes, que contenham, como constituintes basicos, 70% ou mais, em peso, de oleos de petroleo ou de inerais betuminosos, exceto os que contenham biodiesel e exceto os residuos de oleos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0600700', '27109', 'Residuos de oleos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0600800', '2711', 'Gas de petroleo e outros hidrocarbonetos gasosos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0600900', '2713', 'Coque de petroleo e outros residuos de oleo de petroleo ou de minerais betuminosos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0601000', '38260000', 'Biodiesel e suas misturas, que nao contenham ou que contenham menos de 70%, em peso, de oleos de petroleo ou de oleos minerais betuminosos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0601100', '3403', 'Preparacoes lubrificantes, exceto as contendo, como constituintes de base, 70% ou mais, em peso, de oleos de petroleo ou de minerais betuminosos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0601200', '27102000', 'oleos de petroleo ou de minerais betuminosos (exceto oleos brutos) e preparacoes nao especificadas nem compreendidas noutras posicoes, que contenham, como constituintes basicos, 70% ou mais, em peso, de oleos de petroleo ou de minerais betuminosos, que contenham biodiesel, exceto os residuos de oleos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0700100', '27160000', 'Energia eletrica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0800100', '40169990', 'Ferramentas de borracha vulcanizada nao endurecida');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0800200', '44170010', 'Ferramentas, armacoes e cabos de ferramentas, de madeira');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0800200', '44170090', 'Ferramentas, armacoes e cabos de ferramentas, de madeira');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0800300', '6804', 'Mos e artefatos semelhantes, sem armacao, para moer, desfibrar, triturar, amolar, polir, retificar ou cortar pedras para amolar ou para polir, manualmente, e suas partes, de pedras naturais, de abrasivos naturais ou artificiais aglomerados ou de ceramica, mesmo com partes de outras materias');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0800400', '8201', 'Pas, alvioes, picaretas, enxadas, sachos, forcados e forquilhas, ancinhos e raspadeiras machados, podoes e ferramentas semelhantes com gume tesouras de podarde todos os tipos foices e foicinhas, facas para feno ou para palha, tesouras para sebes, cunhas e outras ferramentas manuais para agricultura, horticultura ou silvicultura');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0800500', '82022000', 'Folhas de serras de fita');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0800600', '82029100', 'Laminas de serras maquinas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0800700', '8202', 'Serras manuais e outras folhas de serras (incluidas as fresas-serras e as folhas nao dentadas para serrar), exceto as classificadas nas posicoes 8202.20.00 e 8202.91.00');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0800800', '8203', 'Limas, grosas, alicates (mesmo cortantes), tenazes, pincas, cisalhas para metais, corta-tubos, corta-pinos, saca-bocados e ferramentas semelhantes, manuais, exceto as pincas para sobrancelhas classificadas na posicao 8203.20.90');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0800900', '8204', 'Chaves de porcas, manuais (incluidas as chaves dinamometricas, chaves de caixa intercambiaveis, mesmo com cabos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0801000', '8205', 'Ferramentas manuais (incluidos os diamantes de vidraceiro) nao especificadas nem compreendidas em outras posicoes, lamparinas ou lampadas de soldar (macaricos) e semelhantes tornos de apertar, sargentos e semelhantes, exceto os acessorios ou partes de maquinas- ferramentas bigornas forjas-portateis mos com armacao, manuais ou de pedal');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0801100', '8206', 'Ferramentas de pelo menos duas das posicoes 8202 a 8205, acondicionadas em sortidos para venda a retalho');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0801200', '820740', 'Ferramentas de roscar interior ou exteriormente de mandrilar ou de brochar e de fresar');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0801200', '820760', 'Ferramentas de roscar interior ou exteriormente de mandrilar ou de brochar e de fresar');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0801200', '820770', 'Ferramentas de roscar interior ou exteriormente de mandrilar ou de brochar e de fresar');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0801300', '8207', 'Outras ferramentas intercambiaveis para ferramentas manuais, mesmo mecanicas, ou para maquinas-ferramentas (por exemplo, de embutir, estampar, puncionar, furar, tornear, aparafusar), incluidas as fieiras de estiragem ou de extrusao, para metais, e as ferramentas de perfuracao ou de sondagem, exceto forma ou gabarito de produtos em epoxy, exceto as classificadas nas posicoes 8207.40, 8207.60 e 8207.70');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0801400', '8208', 'Facas e laminas cortantes, para maquinas ou para aparelhos mecanicos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0801500', '82090011', 'Plaquetas ou pastilhas intercambiaveis');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0801600', '8209', 'Outras plaquetas, varetas, pontas e objetos semelhantes para ferramentas, nao montados, de ceramais ("cermets"), exceto as classificadas na posicao 8209.00.11');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0801700', '8211', 'Facas (exceto as da posicao 8208) de lamina cortante ou serrilhada, incluidas as podadeiras de lamina movel, e suas laminas, exceto as de uso domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0801800', '8213', 'Tesouras e suas laminas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0801900', '8467', 'Ferramentas pneumaticas, hidraulicas ou com motor (eletrico ou nao eletrico) incorporado, de uso manual');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0802000', '9015', 'Instrumentos e aparelhos de geodesia, topografia, agrimensura, nivelamento, fotogrametria, hidrografia, oceanografia, hidrologia, meteorologia ou de geofisica, exceto bussolas telemetros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0802100', '90172000', 'Instrumentos de desenho, de tracado ou de calculo metros, micrômetros, paquimetros, calibres e semelhantes partes e acessorios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0802100', '901730', 'Instrumentos de desenho, de tracado ou de calculo metros, micrômetros, paquimetros, calibres e semelhantes partes e acessorios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0802100', '901780', 'Instrumentos de desenho, de tracado ou de calculo metros, micrômetros, paquimetros, calibres e semelhantes partes e acessorios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0802100', '90179090', 'Instrumentos de desenho, de tracado ou de calculo metros, micrômetros, paquimetros, calibres e semelhantes partes e acessorios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0802200', '90251190', 'Termômetros, suas partes e acessorios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0802200', '90259010', 'Termômetros, suas partes e acessorios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0802300', '902519', 'Pirômetros, suas partes e acessorios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0802300', '90259090', 'Pirômetros, suas partes e acessorios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0900100', '8539', 'Lampadas eletricas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0900200', '8540', 'Lampadas eletrônicas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0900300', '85041000', 'Reatores para lampadas ou tubos de descargas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0900400', '853650', '“Starter”');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0900500', '85437099', 'Lampadas de LED (Diodos Emissores de Luz)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1000100', '2522', 'Cal');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1000200', '3816001', 'Argamassas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1000200', '38245000', 'Argamassas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1000300', '32149000', 'Outras argamassas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1000400', '391000', 'Silicones em formas primarias, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1000500', '3916', 'Revestimentos de PVC e outros plasticos forro, sancas e afins de PVC, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1000600', '3917', 'Tubos, e seus acessorios (por exemplo, juntas, cotovelos, flanges, unioes), de plasticos, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1000700', '3918', 'Revestimento de pavimento de PVC e outros plasticos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1000800', '3919', 'Chapas, folhas, tiras, fitas, peliculas e outras formas planas, auto- adesivas, de plasticos, mesmo em rolos, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1000900', '3919', 'Veda rosca, lona plastica para uso na construcao, fitas isolantes e afins');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1000900', '3920', 'Veda rosca, lona plastica para uso na construcao, fitas isolantes e afins');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1000900', '3921', 'Veda rosca, lona plastica para uso na construcao, fitas isolantes e afins');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1001000', '3921', 'Telha de plastico, mesmo reforcada com fibra de vidro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1001100', '3921', 'Cumeeira de plastico, mesmo reforcada com fibra de vidro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1001200', '3921', 'Chapas, laminados plasticos em bobina, para uso na construcao, exceto os descritos nos itens 10.0 e 11.0');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1001300', '3922', 'Banheiras, boxes para chuveiros, pias, lavatorios, bides, sanitarios e seus assentos e tampas, caixas de descarga e artigos semelhantes para usos sanitarios ou higienicos, de plasticos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1001400', '3924', 'Artefatos de higiene/toucador de plastico, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1001500', '39251000', 'Caixa d’agua, inclusive sua tampa, de plastico, mesmo reforcadas com fibra de vidro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1001600', '392590', 'Outras telhas, cumeeira e caixa d’agua, inclusive sua tampa, de plastico, mesmo reforcadas com fibra de vidro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1001700', '39251000', 'Artefatos para apetrechamento de construcoes, de plasticos, nao especificados nem compreendidos em outras posicoes, incluindo persianas, sancas, molduras, apliques e rosetas, caixilhos de polietileno e outros plasticos, exceto os descritos nos itens 15.0 e 16.0');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1001700', '392590', 'Artefatos para apetrechamento de construcoes, de plasticos, nao especificados nem compreendidos em outras posicoes, incluindo persianas, sancas, molduras, apliques e rosetas, caixilhos de polietileno e outros plasticos, exceto os descritos nos itens 15.0 e 16.0');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1001800', '39252000', 'Portas, janelas e seus caixilhos, alizares e soleiras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1001900', '39253000', 'Postigos, estores (incluidas as venezianas) e artefatos semelhantes e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1002000', '392690', 'Outras obras de plastico, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1002100', '4814', 'Papel de parede e revestimentos de parede semelhantes papel para vitrais');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1002200', '68101900', 'Telhas de concreto');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1002300', '6811', 'Telha, cumeeira e caixa d’agua, inclusive sua tampa, de fibrocimento, cimento-celulose');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1002400', '6811', 'Caixas d''agua, tanques e reservatorios e suas tampas, telhas, calhas, cumeeiras e afins, de fibrocimento, cimento-celulose ou semelhantes, contendo ou nao amianto, exceto os descritos no item 23.0');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1002500', '69010000', 'Tijolos, placas (lajes), ladrilhos e outras pecas ceramicas de farinhas siliciosas fosseis ("kieselghur", tripolita, diatomita, por exemplo) ou de terras siliciosas semelhantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1002600', '6902', 'Tijolos, placas (lajes), ladrilhos e pecas ceramicas semelhantes, para uso na construcao, refratarios, que nao sejam de farinhas siliciosas fosseis nem de terras siliciosas semelhantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1002700', '6904', 'Tijolos para construcao, tijoleiras, tapa-vigas e produtos semelhantes, de ceramica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1002800', '6905', 'Telhas, elementos de chamines, condutores de fumaca, ornamentos arquitetônicos, de ceramica, e outros produtos ceramicos para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1002900', '69060000', 'Tubos, calhas ou algerozes e acessorios para canalizacoes, de ceramica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1003000', '6907', 'Ladrilhos e placas de ceramica, exclusivamente para pavimentacao ou revestimento');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1003000', '6908', 'Ladrilhos e placas de ceramica, exclusivamente para pavimentacao ou revestimento');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1003001', '6907', 'Cubos, pastilhas e artigos semelhantes de ceramica, mesmo com suporte.');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1003001', '6908', 'Cubos, pastilhas e artigos semelhantes de ceramica, mesmo com suporte.');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1003100', '6910', 'Pias, lavatorios, colunas para lavatorios, banheiras, bides, sanitarios, caixas de descarga, mictorios e aparelhos fixos semelhantes para usos sanitarios, de ceramica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1003200', '69120000', 'Artefatos de higiene/toucador de ceramica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1003300', '7003', 'Vidro vazado ou laminado, em chapas, folhas ou perfis, mesmo com camada absorvente, refletora ou nao, mas sem qualquer outro trabalho');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1003400', '7004', 'Vidro estirado ou soprado, em folhas, mesmo com camada absorvente, refletora ou nao, mas sem qualquer outro trabalho');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1003500', '7005', 'Vidro flotado e vidro desbastado ou polido em uma ou em ambas as faces, em chapas ou em folhas, mesmo com camada absorvente, refletora ou nao, mas sem qualquer outro trabalho');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1003600', '70071900', 'Vidros temperados');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1003700', '70072900', 'Vidros laminados');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1003800', '7008', 'Vidros isolantes de paredes multiplas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1003900', '7016', 'Blocos, placas, tijolos, ladrilhos, telhas e outros artefatos, de vidro prensado ou moldado, mesmo armado, para uso na construcao cubos, pastilhas e outros artigos semelhantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1004000', '72142000', 'Barras proprias para construcoes, exceto vergalhoes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1004100', '73089010', 'Outras barras proprias para construcoes, exceto vergalhoes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1004200', '72142000', 'Vergalhoes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1004300', '7213', 'Outros vergalhoes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1004300', '73089010', 'Outros vergalhoes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1004400', '72171090', 'Fios de ferro ou aco nao ligados, nao revestidos, mesmo polidos cordas, cabos, trancas (entrancados), lingas e artefatos semelhantes, de ferro ou aco, nao isolados para usos eletricos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1004400', '7312', 'Fios de ferro ou aco nao ligados, nao revestidos, mesmo polidos cordas, cabos, trancas (entrancados), lingas e artefatos semelhantes, de ferro ou aco, nao isolados para usos eletricos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1004500', '721720', 'Outros fios de ferro ou aco, nao ligados, galvanizados');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1004600', '7307', 'Acessorios para tubos (inclusive unioes, cotovelos, luvas ou mangas), de ferro fundido, ferro ou aco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1004700', '73083000', 'Portas e janelas, e seus caixilhos, alizares e soleiras de ferro fundido, ferro ou aco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1004800', '73084000', 'Material para andaimes, para armacoes (cofragens) e para escoramentos, (inclusive armacoes prontas, para estruturas de concreto armado ou argamassa armada), eletrocalhas e perfilados de ferro fundido, ferro ou aco, proprios para construcao, exceto trelicas de aco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1004800', '730890', 'Material para andaimes, para armacoes (cofragens) e para escoramentos, (inclusive armacoes prontas, para estruturas de concreto armado ou argamassa armada), eletrocalhas e perfilados de ferro fundido, ferro ou aco, proprios para construcao, exceto trelicas de aco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1004900', '73084000', 'Trelicas de aco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1005000', '73089090', 'Telhas metalicas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1005100', '7310', 'Caixas diversas (tais como caixa de correio, de entrada de agua, de energia, de instalacao) de ferro, ferro fundido ou aco proprias para a construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1005200', '73130000', 'Arame farpado, de ferro ou aco arames ou tiras, retorcidos, mesmo farpados, de ferro ou aco, dos tipos utilizados em cercas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1005300', '7314', 'Telas metalicas, grades e redes, de fios de ferro ou aco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1005400', '73151100', 'Correntes de rolos, de ferro fundido, ferro ou aco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1005500', '73151290', 'Outras correntes de elos articulados, de ferro fundido, ferro ou aco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1005600', '73158200', 'Correntes de elos soldados, de ferro fundido, de ferro ou aco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1005700', '731700', 'Tachas, pregos, percevejos, escapulas, grampos ondulados ou biselados e artefatos semelhantes, de ferro fundido, ferro ou aco, mesmo com a cabeca de outra materia, exceto cobre');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1005800', '7318', 'Parafusos, pinos ou pernos, roscados, porcas, tira-fundos, ganchos roscados, rebites, chavetas, cavilhas, contrapinos, arruelas (incluidas as de pressao) e artefatos semelhantes, de ferro fundido, ferro ou aco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1005900', '7323', 'Palha de ferro ou aco esponjas, esfregoes, luvas e artefatos semelhantes para limpeza, polimento e usos semelhantes, de ferro ou aco, exceto os classificados na posicao 7323.10.00 de uso domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1006000', '7324', 'Artefatos de higiene ou de toucador, e suas partes, de ferro fundido, ferro ou aco, incluidas as pias, banheiras, lavatorios, cubas, mictorios, tanques e afins de ferro fundido, ferro ou aco, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1006100', '7325', 'Outras obras moldadas, de ferro fundido, ferro ou aco, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1006200', '7326', 'Abracadeiras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1006300', '7407', 'Barras de cobre');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1006400', '74111010', 'Tubos de cobre e suas ligas, para instalacoes de agua quente e gas, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1006500', '7412', 'Acessorios para tubos (por exemplo, unioes, cotovelos, luvas ou mangas) de cobre e suas ligas, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1006600', '7415', 'Tachas, pregos, percevejos, escapulas e artefatos semelhantes, de cobre, ou de ferro ou aco com cabeca de cobre, parafusos, pinos ou pernos, roscados, porcas, ganchos roscados, rebites, chavetas, cavilhas, contrapinos, arruelas (incluidas as de pressao), e artefatos semelhantes, de cobre');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1006700', '74182000', 'Artefatos de higiene/toucador de cobre, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1006800', '76071990', 'Manta de subcobertura aluminizada');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1006900', '7608', 'Tubos de aluminio e suas ligas, para refrigeracao e ar condicionado, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1007000', '76090000', 'Acessorios para tubos (por exemplo, unioes, cotovelos, luvas ou mangas), de aluminio, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1007100', '7610', 'Construcoes e suas partes (por exemplo, pontes e elementos de pontes, torres, porticos ou pilones, pilares, colunas, armacoes, estruturas para telhados, portas e janelas, e seus caixilhos, alizares e soleiras, balaustradas), de aluminio, exceto as construcoes pre-fabricadas da posicao 9406 chapas, barras, perfis, tubos e semelhantes, de aluminio, proprios para construcoes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1007200', '76152000', 'Artefatos de higiene/toucador de aluminio, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1007300', '7616', 'Outras obras de aluminio, proprias para construcoes, incluidas as persianas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1007400', '83024100', 'Outras guarnicoes, ferragens e artigos semelhantes de metais comuns, para construcoes, inclusive puxadores.');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1007500', '8301', 'Fechaduras e ferrolhos (de chave, de segredo ou eletricos), de metais comuns, incluidas as suas partes fechos e armacoes com fecho, com fechadura, de metais comuns chaves para estes artigos, de metais comuns, exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1007600', '83021000', 'Dobradicas de metais comuns, de qualquer tipo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1007700', '8307', 'Tubos flexiveis de metais comuns, mesmo com acessorios, para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1007800', '8311', 'Fios, varetas, tubos, chapas, eletrodos e artefatos semelhantes, de metais comuns ou de carbonetos metalicos, revestidos exterior ou interiormente de decapantes ou de fundentes, para soldagem (soldadura) ou deposito de metal ou de carbonetos metalicos fios e varetas de pos de metais comuns aglomerados, para metalizacao por projecao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1007900', '8481', 'Torneiras, valvulas (incluidas as redutoras de pressao e as termostaticas) e dispositivos semelhantes, para canalizacoes, caldeiras, reservatorios, cubas e outros recipientes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100100', '28289011', 'agua sanitaria, branqueador e outros alvejantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100100', '28289019', 'agua sanitaria, branqueador e outros alvejantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100100', '32064100', 'agua sanitaria, branqueador e outros alvejantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100100', '38089419', 'agua sanitaria, branqueador e outros alvejantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100200', '34012090', 'Saboes em po, flocos, palhetas, granulos ou outras formas semelhantes, para lavar roupas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100300', '34012090', 'Saboes liquidos para lavar roupas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100400', '34022000', 'Detergentes em po, flocos, palhetas, granulos ou outras formas semelhantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100500', '34022000', 'Detergentes liquidos, exceto para lavar roupa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100600', '34022000', 'Detergente liquido para lavar roupa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100700', '3402', 'Outros agentes organicos de superficie (exceto saboes) preparacoes tensoativas, preparacoes para lavagem (incluidas as preparacoes auxiliares para lavagem) e preparacoes para limpeza (inclusive multiuso e limpadores), mesmo contendo sabao, exceto as da posicao 3401 e os produtos descritos nos itens 3 a 5 em embalagem de conteudo inferior ou igual a 50 litros ou 50 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100800', '38099190', 'Amaciante/suavizante');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100900', '39241000', 'Esponjas para limpeza');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100900', '39249000', 'Esponjas para limpeza');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100900', '68053010', 'Esponjas para limpeza');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1100900', '68053090', 'Esponjas para limpeza');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1101000', '2207', 'alcool etilico para limpeza');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1101100', '73231000', 'Palhas de ferro ou aco esponjas, esfregoes, luvas e artefatos semelhantes para limpeza, polimento ou uso semelhantes todos de uso domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1200100', '8504', 'Transformadores, bobinas de reatancia e de auto inducao, inclusive os transformadores de potencia superior a 16 KVA, classificados nas posicoes 8504.33.00 e 8504.34.00 exceto os demais transformadores da subposicao 8504.3, os reatores para lampadas eletricas de descarga classificados no codigo 8504.10.00, os carregadores de acumuladores do codigo 8504.40.10, os equipamentos de alimentacao ininterrupta de energia (UPS ou “no break”), no codigo 8504.40.40 e os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1200200', '8516', 'Aquecedores eletricos de agua, incluidos os de imersao, chuveiros ou duchas eletricos, torneiras eletricas, resistencias de aquecimento, inclusive as de duchas e chuveiros eletricos e suas partes exceto outros fornos, fogareiros (incluidas as chapas de coccao), grelhas e assadeiras, classificados na posicao 8516.60.00');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1200300', '8535', 'Aparelhos para interrupcao, seccionamento, protecao, derivacao, ligacao ou conexao de circuitos eletricos (por exemplo, interruptores, comutadores, corta-circuitos, para-raios, limitadores de tensao, eliminadores de onda, tomadas de corrente e outros conectores, caixas de juncao), para tensao superior a 1.000V, exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1200400', '8536', 'Aparelhos para interrupcao, seccionamento, protecao, derivacao, ligacao ou conexao de circuitos eletricos (por exemplo, interruptores, comutadores, reles, corta-circuitos, eliminadores de onda, plugues e tomadas de corrente, suportes para lampadas e outros conectores, caixas de juncao), para uma tensao nao superior a 1.000V conectores para fibras opticas, feixes ou cabos de fibras opticas exceto "starter" classificado na subposicao 8536.50 e os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1200500', '8538', 'Partes reconheciveis como exclusiva ou principalmente destinadas aos aparelhos das posicoes 8535 e 8536');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1200600', '74130000', 'Cabos, trancas e semelhantes, de cobre, nao isolados para usos eletricos, exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1200700', '8544', 'Fios, cabos (incluidos os cabos coaxiais) e outros condutores, isolados ou nao, para usos eletricos (incluidos os de cobre ou aluminio, envernizados ou oxidados anodicamente), mesmo com pecas de conexao, inclusive fios e cabos eletricos, para tensao nao superior a 1000V, para uso na construcao fios e cabos telefônicos e para transmissao de dados cabos de fibras opticas, constituidos de fibras embainhadas individualmente, mesmo com condutores eletricos ou munidos de pecas de conexao cordas, cabos, tranca');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1200700', '7605', 'Fios, cabos (incluidos os cabos coaxiais) e outros condutores, isolados ou nao, para usos eletricos (incluidos os de cobre ou aluminio, envernizados ou oxidados anodicamente), mesmo com pecas de conexao, inclusive fios e cabos eletricos, para tensao nao superior a 1000V, para uso na construcao fios e cabos telefônicos e para transmissao de dados cabos de fibras opticas, constituidos de fibras embainhadas individualmente, mesmo com condutores eletricos ou munidos de pecas de conexao cordas, cabos, tranca');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1200700', '7614', 'Fios, cabos (incluidos os cabos coaxiais) e outros condutores, isolados ou nao, para usos eletricos (incluidos os de cobre ou aluminio, envernizados ou oxidados anodicamente), mesmo com pecas de conexao, inclusive fios e cabos eletricos, para tensao nao superior a 1000V, para uso na construcao fios e cabos telefônicos e para transmissao de dados cabos de fibras opticas, constituidos de fibras embainhadas individualmente, mesmo com condutores eletricos ou munidos de pecas de conexao cordas, cabos, tranca');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1200800', '8546', 'Isoladores de qualquer materia, para usos eletricos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1200900', '8547', 'Pecas isolantes inteiramente de materias isolantes, ou com simples pecas metalicas de montagem (suportes roscados, por exemplo) incorporadas na massa, para maquinas, aparelhos e instalacoes eletricas tubos isoladores e suas pecas de ligacao, de metais comuns, isolados interiormente');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300100', '3003', 'Medicamentos de referencia – positiva');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300100', '3004', 'Medicamentos de referencia – positiva');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300101', '3003', 'Medicamentos de referencia – negativa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300101', '3004', 'Medicamentos de referencia – negativa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300102', '3003', 'Medicamentos de referencia – neutra');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300102', '3004', 'Medicamentos de referencia – neutra');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300200', '3003', 'Medicamentos generico – positiva');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300200', '3004', 'Medicamentos generico – positiva');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300201', '3003', 'Medicamentos generico – negativa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300201', '3004', 'Medicamentos generico – negativa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300202', '3003', 'Medicamentos generico – neutra');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300202', '3004', 'Medicamentos generico – neutra');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300300', '3003', 'Medicamentos similar – positiva');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300300', '3004', 'Medicamentos similar – positiva');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300301', '3003', 'Medicamentos similar – negativa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300301', '3004', 'Medicamentos similar – negativa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300302', '3003', 'Medicamentos similar – neutra');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300302', '3004', 'Medicamentos similar – neutra');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300400', '3003', 'Outros tipos de medicamentos – positiva');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300400', '3004', 'Outros tipos de medicamentos – positiva');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300401', '3003', 'Outros tipos de medicamentos - negativa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300401', '3004', 'Outros tipos de medicamentos - negativa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300402', '3003', 'Outros tipos de medicamentos – neutra');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300402', '3004', 'Outros tipos de medicamentos – neutra');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300500', '300660', 'Preparacoes quimicas contraceptivas a base de hormônios, de outros produtos da posicao 29.37 ou de espermicidas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300600', '2936', 'Provitaminas e vitaminas, naturais ou reproduzidas por sintese (incluidos os concentrados naturais), bem como os seus derivados utilizados principalmente como vitaminas, misturados ou nao entre si, mesmo em quaisquer solucoes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300700', '300630', 'Preparacoes opacificantes (contrastantes) para exames radiograficos e reagentes de diagnostico concebidos para serem administrados ao paciente');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300800', '3002', 'Antissoro, outras fracoes do sangue, produtos imunologicos modificados, mesmo obtidos por via biotecnologica vacinas para medicina humana e produtos semelhantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1300900', '3005', 'Algodao, atadura, esparadrapo, haste flexivel ou nao, com uma ou ambas extremidades de algodao, gazes, pensos, sinapismos, e outros, impregnados ou recobertos de substancias farmaceuticas ou acondicionados para venda a retalho para usos medicinais, cirurgicos ou dentarios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1301000', '40151100', 'Luvas cirurgicas e luvas de procedimento');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1301000', '40151900', 'Luvas cirurgicas e luvas de procedimento');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1301100', '40141000', 'Preservativo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1301200', '901831', 'Seringas, mesmo com agulhas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1301300', '9018321', 'Agulhas para seringas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1301400', '39269090', 'Contraceptivos (dispositivos intra-uterinos - DIU)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1301400', '90189099', 'Contraceptivos (dispositivos intra-uterinos - DIU)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1400100', '4823209', 'Filtros descartaveis para coar cafe ou cha');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1400200', '48236', 'Bandejas, travessas, pratos, xicaras ou chavenas, tacas, copos e artigos semelhantes, de papel ou cartao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1400300', '48131000', 'Papel para cigarro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1500100', '3919', 'Lonas plasticas, exceto as para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1500100', '3920', 'Lonas plasticas, exceto as para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1500100', '3921', 'Lonas plasticas, exceto as para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1500200', '3924', 'Artefatos de higiene/toucador de plastico, exceto os para uso na construcao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1500300', '39241000', 'Servicos de mesa e outros utensilios de mesa ou de cozinha, de');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1600100', '4011', 'Pneus novos, dos tipos utilizados em automoveis de passageiros (incluidos os veiculos de uso misto - camionetas e os automoveis de corrida)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1600200', '4011', 'Pneus novos, dos tipos utilizados em caminhoes (inclusive para os fora-de-estrada), ônibus, avioes, maquinas de terraplenagem, de construcao e conservacao de estradas, maquinas e tratores agricolas, pa-carregadeira');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1600300', '4011', 'Pneus novos para motocicletas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1600400', '4011', 'Outros tipos de pneus novos, exceto para bicicletas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1600500', '40115000', 'Pneus novos de borracha dos tipos utilizados em bicicletas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1600600', '40121', 'Pneus recauchutados');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1600700', '401290', 'Protetores de borracha, exceto para bicicletas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1600701', '401290', 'Protetores de borracha para bicicletas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1600800', '4013', 'Camaras de ar de borracha, exceto para bicicletas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1600900', '40132000', 'Camaras de ar de borracha dos tipos utilizados em bicicletas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1700100', '17049010', 'Chocolate branco, em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1700200', '18063110', 'Chocolates contendo cacau, em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1700200', '18063120', 'Chocolates contendo cacau, em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1700300', '18063210', 'Chocolate em barras, tabletes ou blocos ou no estado liquido, em pasta, em po, granulos ou formas semelhantes, em recipientes ou embalagens imediatas de conteudo inferior ou igual a 2 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1700300', '18063220', 'Chocolate em barras, tabletes ou blocos ou no estado liquido, em pasta, em po, granulos ou formas semelhantes, em recipientes ou embalagens imediatas de conteudo inferior ou igual a 2 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1700400', '18069000', 'Chocolates e outras preparacoes alimenticias contendo cacau, em embalagens de conteudo inferior ou igual a 1 kg, excluidos os achocolatados em po');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1700500', '18069000', 'Achocolatados em po, em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1700600', '18069000', 'Caixas de bombons contendo cacau, em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1700700', '17049090', 'Bombons, inclusive a base de chocolate branco sem cacau');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1700800', '18069000', 'Bombons, balas, caramelos, confeitos, pastilhas e outros produtos de confeitaria, contendo cacau');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1700900', '210120', 'Bebidas prontas a base de mate ou cha');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1700900', '22029000', 'Bebidas prontas a base de mate ou cha');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1701000', '22021000', 'Refrescos e outras bebidas nao alcoolicas, exceto os refrigerantes e as demais bebidas de que trata o Anexo IV');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1701100', '22029000', 'Bebidas prontas a base de cafe');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1701200', '2009', 'Sucos de frutas ou de produtos horticolas mistura de sucos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1701300', '20098', 'agua de coco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1701400', '22029000', 'Nectares de frutas e outras bebidas nao alcoolicas prontas para beber, exceto isotônicos e energeticos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1701500', '22029000', 'Bebidas alimentares prontas a base de soja, leite ou cacau, inclusive os produtos denominados bebidas lacteas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1701600', '22021000', 'Refrescos e outras bebidas prontas para beber a base de cha e mate');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1701700', '4021', 'Leite em po, blocos ou granulos, exceto creme de leite');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1701700', '4022', 'Leite em po, blocos ou granulos, exceto creme de leite');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1701700', '4029', 'Leite em po, blocos ou granulos, exceto creme de leite');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1701800', '19011020', 'Farinha lactea');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1701900', '19011010', 'Leite modificado para alimentacao de criancas.');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702000', '19011090', 'Preparacoes para alimentacao infantil a base de farinhas, grumos, semolas ou amidos e outros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702000', '19011030', 'Preparacoes para alimentacao infantil a base de farinhas, grumos, semolas ou amidos e outros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702100', '4011010', 'Leite “longa vida” (UHT - “Ultra High Temperature”), em recipiente de conteudo inferior ou igual a 2 litros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702100', '4012010', 'Leite “longa vida” (UHT - “Ultra High Temperature”), em recipiente de conteudo inferior ou igual a 2 litros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702101', '4011010', 'Leite “longa vida” (UHT - “Ultra High Temperature”), em recipiente de conteudo superior a 2 litros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702101', '4012010', 'Leite “longa vida” (UHT - “Ultra High Temperature”), em recipiente de conteudo superior a 2 litros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702200', '4014010', 'Leite em recipiente de conteudo inferior ou igual a 1 litro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702200', '4015010', 'Leite em recipiente de conteudo inferior ou igual a 1 litro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702201', '4014010', 'Leite em recipiente de conteudo superior a 1 litro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702201', '4015010', 'Leite em recipiente de conteudo superior a 1 litro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702300', '4011090', 'Leite do tipo pasteurizado em recipiente de conteudo inferior ou igual a 1 litro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702300', '4012090', 'Leite do tipo pasteurizado em recipiente de conteudo inferior ou igual a 1 litro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702301', '4011090', 'Leite do tipo pasteurizado em recipiente de conteudo superior a 1 litro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702301', '4012090', 'Leite do tipo pasteurizado em recipiente de conteudo superior a 1 litro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702400', '401402', 'Creme de leite, em recipiente de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702400', '4022130', 'Creme de leite, em recipiente de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702400', '4022930', 'Creme de leite, em recipiente de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702400', '4029', 'Creme de leite, em recipiente de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702401', '401402', 'Creme de leite, em recipiente de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702401', '4022130', 'Creme de leite, em recipiente de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702401', '4022930', 'Creme de leite, em recipiente de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702401', '4029', 'Creme de leite, em recipiente de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702402', '40110', 'Outros cremes de leite, em recipiente de conteudo inferior ou igual a 1kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702402', '40120', 'Outros cremes de leite, em recipiente de conteudo inferior ou igual a 1kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702402', '40150', 'Outros cremes de leite, em recipiente de conteudo inferior ou igual a 1kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702402', '40210', 'Outros cremes de leite, em recipiente de conteudo inferior ou igual a 1kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702402', '4022920', 'Outros cremes de leite, em recipiente de conteudo inferior ou igual a 1kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702500', '4029', 'Leite condensado, em recipiente de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702501', '4029', 'Leite condensado, em recipiente de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702600', '403', 'Iogurte e leite fermentado em recipiente de conteudo inferior ou igual a 2 litros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702601', '403', 'Iogurte e leite fermentado em recipiente de conteudo superior a 2 litros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702700', '4039000', 'Coalhada');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702800', '406', 'Requeijao e similares, em recipiente de conteudo inferior ou igual a 1 kg, exceto as embalagens individuais de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702801', '406', 'Requeijao e similares, em recipiente de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1702900', '406', 'Queijos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703000', '4051000', 'Manteiga, em embalagem de conteudo inferior ou igual a 1 kg, exceto as embalagens individuais de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703001', '4051000', 'Manteiga, em embalagem de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703100', '15171000', 'Margarina em recipiente de conteudo inferior ou igual a 500 g, exceto as embalagens individuais de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703200', '15171000', 'Margarina, em recipiente de conteudo superior a 500 g e inferior a 1 kg, creme vegetal em recipiente de conteudo inferior a 1 kg, exceto as embalagens individuais de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703201', '15171000', 'Margarina e creme vegetal, em recipiente de conteudo de 1 kg.');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703202', '151790', 'Outras margarinas e cremes vegetais em recipiente de conteudo inferior a 1 kg, exceto as embalagens individuais de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703300', '15162000', 'Gorduras e oleos vegetais e respectivas fracoes, parcial ou totalmente hidrogenados, interesterificados, reesterificados ou elaidinizados, mesmo refinados, mas nao preparados de outro modo, em recipiente de conteudo inferior ou igual a 1 kg, exceto as embalagens individuais de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703301', '15162000', 'Gorduras e oleos vegetais e respectivas fracoes, parcial ou totalmente hidrogenados, interesterificados, reesterificados ou elaidinizados, mesmo refinados, mas nao preparados de outro modo, em recipiente de conteudo superior a 1 kg, exceto as embalagens individuais de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703400', '19019020', 'Doces de leite');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703500', '19041000', 'Produtos a base de cereais, obtidos por expansao ou torrefacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703500', '19049000', 'Produtos a base de cereais, obtidos por expansao ou torrefacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703600', '19059090', 'Salgadinhos diversos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703700', '20052000', 'Batata frita, inhame e mandioca fritos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703700', '20059', 'Batata frita, inhame e mandioca fritos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703800', '20081', 'Amendoim e castanhas tipo aperitivo, em embalagem de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703801', '20081', 'Amendoim e castanhas tipo aperitivo, em embalagem de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1703900', '21032010', 'Catchup em embalagens imediatas de conteudo inferior ou igual a 650 g, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704000', '21039021', 'Condimentos e temperos compostos, incluindo molho de pimenta e outros molhos, em embalagens imediatas de conteudo inferior ou igual a 1 kg, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 3 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704000', '21039091', 'Condimentos e temperos compostos, incluindo molho de pimenta e outros molhos, em embalagens imediatas de conteudo inferior ou igual a 1 kg, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 3 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704100', '21031010', 'Molhos de soja preparados em embalagens imediatas de conteudo inferior ou igual a 650 g, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704200', '21033010', 'Farinha de mostarda em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704300', '21033021', 'Mostarda preparada em embalagens imediatas de conteudo inferior ou igual a 650 g, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704400', '21039011', 'Maionese em embalagens imediatas de conteudo inferior ou igual a 650 g, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704500', '2002', 'Tomates preparados ou conservados, exceto em vinagre ou em acido acetico, em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704600', '21032010', 'Molhos de tomate em embalagens imediatas de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704700', '17049090', 'Barra de cereais');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704700', '19042000', 'Barra de cereais');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704700', '19049000', 'Barra de cereais');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704800', '18063120', 'Barra de cereais contendo cacau');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704800', '18063220', 'Barra de cereais contendo cacau');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704800', '18069000', 'Barra de cereais contendo cacau');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704900', '11010010', 'Farinha de trigo, em embalagem inferior ou igual a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1704901', '11010010', 'Farinha de trigo, em embalagem superior a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1705000', '11010020', 'Mistura de farinha de trigo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1705100', '19012000', 'Misturas e preparacoes para bolos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1705100', '19019090', 'Misturas e preparacoes para bolos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1705200', '19023000', 'Massas alimenticias tipo instantanea');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1705300', '1902', 'Massas alimenticias, cozidas ou recheadas (de carne ou de outras substancias) ou preparadas de outro modo, exceto as massas alimenticias tipo instantanea');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1705301', '19024000', 'Cuscuz');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1705400', '19021', 'Massas alimenticias nao cozidas, nem recheadas, nem preparadas de outro modo:');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1705500', '190520', 'Paes industrializados, inclusive de especiarias, exceto panetones e bolo de forma');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1705600', '19052090', 'Bolo de forma, inclusive de especiarias');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1705700', '19052010', 'Panetones');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1705800', '190531', 'Biscoitos e bolachas derivados de farinha de trigo exceto dos tipos "cream cracker", "agua e sal", "maisena", "maria" e outros de consumo popular, nao adicionados de cacau, nem recheados, cobertos ou amanteigados, independentemente de sua denominacao comercial');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1705900', '190531', 'Biscoitos e bolachas nao derivados de farinha de trigo exceto dos tipos "cream cracker", "agua e sal", "maisena" e "maria" e outros de consumo popular, nao adicionados de cacau, nem recheados, cobertos ou amanteigados, independentemente de sua denominacao comercial');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1706000', '190531', 'Biscoitos e bolachas dos tipos "cream cracker", "agua e sal", "maisena" e "maria" e outros de consumo popular, adicionados de edulcorantes e nao adicionados de cacau, nem recheados, cobertos ou amanteigados, independentemente de sua denominacao comercial');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1706100', '19059020', 'Biscoitos e bolachas dos tipos "cream cracker", "agua e sal", "maisena" e "maria" e outros de consumo popular, nao adicionados de cacau, nem recheados, cobertos ou amanteigados, independentemente de sua denominacao comercial');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1706200', '190532', '“Waffles” e “wafers” - sem cobertura');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1706300', '190532', '“Waffles” e “wafers”- com cobertura');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1706400', '190540', 'Torradas, pao torrado e produtos semelhantes torrados');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1706500', '19059010', 'Outros paes de forma');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1706600', '19059020', 'Outras bolachas, exceto casquinhas para sorvete');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1706700', '19059090', 'Outros paes e bolos industrializados e produtos de panificacao nao especificados anteriormente exceto casquinhas para sorvete e pao frances de ate 200 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1706800', '19051000', 'Pao denominado knackebrot');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1706900', '19059090', 'Pao frances de ate 200 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707000', '190590', 'Demais paes industrializados');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707100', '15079011', 'oleo de soja refinado, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteudo inferior ou igual a 15 mililitros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707200', '1508', 'oleo de amendoim refinado, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteudo inferior ou igual a 15 mililitros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707300', '1509', 'Azeites de oliva, em recipientes com capacidade inferior ou igual a 2 litros, exceto as embalagens individuais de conteudo inferior ou igual a 15 mililitros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707301', '1509', 'Azeites de oliva, em recipientes com capacidade superior a 2 litros e inferior ou igual a 5 litros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707302', '1509', 'Azeites de oliva, em recipientes com capacidade superior a 5 litros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707400', '15100000', 'Outros oleos e respectivas fracoes, obtidos exclusivamente a partir de azeitonas, mesmo refinados, mas nao quimicamente modificados, e misturas desses oleos ou fracoes com oleos ou fracoes da posicao 15.09, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteudo inferior ou igual a 15 mililitros');
COMMIT WORK;
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707500', '15121911', 'oleo de girassol ou de algodao refinado, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteudo inferior ou igual a 15 mililitros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707500', '15122910', 'oleo de girassol ou de algodao refinado, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteudo inferior ou igual a 15 mililitros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707600', '15141', 'oleo de canola, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteudo inferior ou igual a 15 mililitros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707700', '', 'oleo de linhaca refinado, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteudo inferior ou igual a 15 mililitros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707700', '15151900', 'oleo de linhaca refinado, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteudo inferior ou igual a 15 mililitros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707800', '15152910', 'oleo de milho refinado, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteudo inferior ou igual a 15 mililitros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1707900', '15122990', 'Outros oleos refinados, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteudo inferior ou igual a 15 mililitros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708000', '15179010', 'Misturas de oleos refinados, para consumo humano, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteudo inferior ou igual a 15 mililitros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708100', '1511', 'Outros oleos vegetais comestiveis nao especificados anteriormente');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708100', '1513', 'Outros oleos vegetais comestiveis nao especificados anteriormente');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708100', '1514', 'Outros oleos vegetais comestiveis nao especificados anteriormente');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708100', '1515', 'Outros oleos vegetais comestiveis nao especificados anteriormente');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708100', '1516', 'Outros oleos vegetais comestiveis nao especificados anteriormente');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708100', '1518', 'Outros oleos vegetais comestiveis nao especificados anteriormente');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708200', '16010000', 'Enchidos (embutidos) e produtos semelhantes, de carne, miudezas ou sangue exceto salsicha, linguica e mortadela');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708300', '16010000', 'Salsicha e linguica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708400', '16010000', 'Mortadela');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708500', '1602', 'Outras preparacoes e conservas de carne, miudezas ou de sangue');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708600', '1604', 'Preparacoes e conservas de peixes caviar e seus sucedaneos preparados a partir de ovas de peixe exceto sardinha em conserva');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708700', '1604', 'Sardinha em conserva');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708800', '1605', 'Crustaceos, moluscos e outros invertebrados aquaticos, preparados ou em conservas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708900', '0201', 'Carne de gado bovino, ovino e bufalino e produtos comestiveis resultantes da matanca desse gado submetidos a salga, secagem ou desidratacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708900', '202', 'Carne de gado bovino, ovino e bufalino e produtos comestiveis resultantes da matanca desse gado submetidos a salga, secagem ou desidratacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708900', '204', 'Carne de gado bovino, ovino e bufalino e produtos comestiveis resultantes da matanca desse gado submetidos a salga, secagem ou desidratacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708900', '206', 'Carne de gado bovino, ovino e bufalino e produtos comestiveis resultantes da matanca desse gado submetidos a salga, secagem ou desidratacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708900', '2102000', 'Carne de gado bovino, ovino e bufalino e produtos comestiveis resultantes da matanca desse gado submetidos a salga, secagem ou desidratacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708900', '2109900', 'Carne de gado bovino, ovino e bufalino e produtos comestiveis resultantes da matanca desse gado submetidos a salga, secagem ou desidratacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1708900', '1502', 'Carne de gado bovino, ovino e bufalino e produtos comestiveis resultantes da matanca desse gado submetidos a salga, secagem ou desidratacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709000', '204', 'Carnes de animais das especies caprina, frescas, refrigeradas ou congeladas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709100', '0203', 'Carnes e demais produtos comestiveis frescos, resfriados, congelados, salgados, em salmoura, simplesmente temperados, secos ou defumados, resultantes do abate de aves e de suinos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709100', '206', 'Carnes e demais produtos comestiveis frescos, resfriados, congelados, salgados, em salmoura, simplesmente temperados, secos ou defumados, resultantes do abate de aves e de suinos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709100', '207', 'Carnes e demais produtos comestiveis frescos, resfriados, congelados, salgados, em salmoura, simplesmente temperados, secos ou defumados, resultantes do abate de aves e de suinos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709100', '209', 'Carnes e demais produtos comestiveis frescos, resfriados, congelados, salgados, em salmoura, simplesmente temperados, secos ou defumados, resultantes do abate de aves e de suinos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709100', '2101', 'Carnes e demais produtos comestiveis frescos, resfriados, congelados, salgados, em salmoura, simplesmente temperados, secos ou defumados, resultantes do abate de aves e de suinos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709100', '2109900', 'Carnes e demais produtos comestiveis frescos, resfriados, congelados, salgados, em salmoura, simplesmente temperados, secos ou defumados, resultantes do abate de aves e de suinos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709100', '1501', 'Carnes e demais produtos comestiveis frescos, resfriados, congelados, salgados, em salmoura, simplesmente temperados, secos ou defumados, resultantes do abate de aves e de suinos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709200', '710', 'Produtos horticolas, cozidos em agua ou vapor, congelados, em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709201', '710', 'Produtos horticolas, cozidos em agua ou vapor, congelados, em embalagens de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709300', '811', 'Frutas, nao cozidas ou cozidas em agua ou vapor, congeladas, mesmo adicionadas de acucar ou de outros edulcorantes, em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709301', '811', 'Frutas, nao cozidas ou cozidas em agua ou vapor, congeladas, mesmo adicionadas de acucar ou de outros edulcorantes, em embalagens de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709400', '2001', 'Produtos horticolas, frutas e outras partes comestiveis de plantas, preparados ou conservados em vinagre ou em acido acetico, em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709401', '2001', 'Produtos horticolas, frutas e outras partes comestiveis de plantas, preparados ou conservados em vinagre ou em acido acetico, em embalagens de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709500', '2004', 'Outros produtos horticolas preparados ou conservados, exceto em vinagre ou em acido acetico, congelados, com excecao dos produtos da posicao 20.06, em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709501', '2004', 'Outros produtos horticolas preparados ou conservados, exceto em vinagre ou em acido acetico, congelados, com excecao dos produtos da posicao 20.06, em embalagens de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709600', '2005', 'Outros produtos horticolas preparados ou conservados, exceto em vinagre ou em acido acetico, nao congelados, com excecao dos produtos da posicao 20.06, excluidos batata, inhame e mandioca fritos, em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709601', '2005', 'Outros produtos horticolas preparados ou conservados, exceto em vinagre ou em acido acetico, nao congelados, com excecao dos produtos da posicao 20.06, excluidos batata, inhame e mandioca fritos, em embalagens de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709700', '20060000', 'Produtos horticolas, frutas, cascas de frutas e outras partes de plantas, conservados com acucar (passados por calda, glaceados ou cristalizados), em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709701', '20060000', 'Produtos horticolas, frutas, cascas de frutas e outras partes de plantas, conservados com acucar (passados por calda, glaceados ou cristalizados), em embalagens de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709800', '2007', 'Doces, geleias, “marmelades”, pures e pastas de frutas, obtidos por cozimento, com ou sem adicao de acucar ou de outros edulcorantes, em embalagens de conteudo inferior ou igual a 1 kg, exceto as embalagens individuais de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709801', '2007', 'Doces, geleias, “marmelades”, pures e pastas de frutas, obtidos por cozimento, com ou sem adicao de acucar ou de outros edulcorantes, em embalagens de conteudo superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709900', '2008', 'Frutas e outras partes comestiveis de plantas, preparadas ou conservadas de outro modo, com ou sem adicao de acucar ou de outros edulcorantes ou de alcool, nao especificadas nem compreendidas em outras posicoes, excluidos os amendoins e castanhas tipo aperitivo, da posicao 2008.1, em embalagens de conteudo inferior ou igual a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1709901', '2008', 'Frutas e outras partes comestiveis de plantas, preparadas ou conservadas de outro modo, com ou sem adicao de acucar ou de outros edulcorantes ou de alcool, nao especificadas nem compreendidas em outras posicoes, excluidos os amendoins e castanhas tipo aperitivo, da posicao 2008.1, em embalagens superior a 1 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710000', '901', 'Cafe torrado e moido, em embalagens de conteudo inferior ou igual a 2 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710001', '901', 'Cafe torrado e moido, em embalagens de conteudo superior a 2 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710100', '0902', 'Cha, mesmo aromatizado');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710100', '12119090', 'Cha, mesmo aromatizado');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710100', '21069090', 'Cha, mesmo aromatizado');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710200', '90300', 'Mate');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710300', '17011', 'Acucar refinado, em embalagens de conteudo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710300', '17019900', 'Acucar refinado, em embalagens de conteudo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710301', '17011', 'Acucar refinado, em embalagens de conteudo superior a 2 kg e inferior ou igual a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710301', '17019900', 'Acucar refinado, em embalagens de conteudo superior a 2 kg e inferior ou igual a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710302', '17011', 'Acucar refinado, em embalagens de conteudo superior a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710302', '17019900', 'Acucar refinado, em embalagens de conteudo superior a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710400', '17019100', 'Acucar refinado adicionado de aromatizante ou de corante em embalagens de conteudo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710401', '17019100', 'Acucar refinado adicionado de aromatizante ou de corante em embalagens de conteudo superior a 2 kg e inferior ou igual a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710402', '17019100', 'Acucar refinado adicionado de aromatizante ou de corante em embalagens de conteudo superior a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710500', '17011', 'Acucar cristal, em embalagens de conteudo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710500', '17019900', 'Acucar cristal, em embalagens de conteudo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710501', '17011', 'Acucar cristal, em embalagens de conteudo superior a 2 kg e inferior ou igual a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710501', '17019900', 'Acucar cristal, em embalagens de conteudo superior a 2 kg e inferior ou igual a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710502', '17011', 'Acucar cristal, em embalagens de conteudo superior a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710502', '17019900', 'Acucar cristal, em embalagens de conteudo superior a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710600', '17019100', 'Acucar cristal adicionado de aromatizante ou de corante, em embalagens de conteudo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710601', '17019100', 'Acucar cristal adicionado de aromatizante ou de corante, em embalagens de conteudo superior a 2 kg e inferior ou igual a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710602', '170191', 'Acucar cristal adicionado de aromatizante ou de corante, em embalagens de conteudo superior a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710700', '17011', 'Outros tipos de acucar, em embalagens de conteudo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710700', '17019900', 'Outros tipos de acucar, em embalagens de conteudo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710701', '17011', 'Outros tipos de acucar, em embalagens de conteudo superior a 2 kg e inferior ou igual a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710701', '17019900', 'Outros tipos de acucar, em embalagens de conteudo superior a 2 kg e inferior ou igual a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710702', '17011', 'Outros tipos de acucar, em embalagens de conteudo superior a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710702', '17019900', 'Outros tipos de acucar, em embalagens de conteudo superior a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710800', '17019100', 'Outros tipos de acucar adicionado de aromatizante ou de corante, em embalagens de conteudo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710801', '17019100', 'Outros tipos de acucar adicionado de aromatizante ou de corante, em embalagens de conteudo superior a 2 kg e inferior ou igual a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710802', '17019100', 'Outros tipos de acucar adicionado de aromatizante ou de corante, em embalagens de conteudo superior a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710900', '1702', 'Outros acucares em embalagens de conteudo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (saches) de conteudo inferior ou igual a 10 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710901', '1702', 'Outros acucares, em embalagens de conteudo superior a 2 kg e inferior ou igual a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1710902', '1702', 'Outros acucares, em embalagens de conteudo superior a 5 kg');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1711000', '20081900', 'Milho para pipoca (micro-ondas)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1711100', '21011', 'Extratos, essencias e concentrados de cafe e preparacoes a base destes extratos, essencias ou concentrados ou a base de cafe, em embalagens de conteudo inferior ou igual a 500 g, exceto as preparacoes indicadas no item 112.0');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1711200', '210120', 'Extratos, essencias e concentrados de cha ou de mate e preparacoes a base destes extratos, essencias ou concentrados ou a base de cha ou de mate, em embalagens de conteudo inferior ou igual a 500 g, exceto as bebidas prontas a base de mate ou cha');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1711300', '19019090', 'Preparacoes em po para cappuccino e similares, em embalagens de conteudo inferior ou igual a 500 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1711300', '21011190', 'Preparacoes em po para cappuccino e similares, em embalagens de conteudo inferior ou igual a 500 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1711300', '21011200', 'Preparacoes em po para cappuccino e similares, em embalagens de conteudo inferior ou igual a 500 g');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1800100', '69111010', 'Artigos para servico de mesa ou de cozinha, de porcelana, inclusive os descartaveis – estojos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1800200', '69111090', 'Artigos para servico de mesa ou de cozinha, de porcelana, inclusive os descartaveis – avulsos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1800300', '69120000', 'Artigos para servico de mesa ou de cozinha, de ceramica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1800400', '69120000', 'Velas para filtros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900100', '32131000', 'Tinta guache');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900200', '39162000', 'Espiral - perfil para encadernacao, de plastico e outros materiais classificados nas posicoes 3901 a 3914');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900300', '39261000', 'Artigos de escritorio e artigos escolares de plastico e outros materiais classificados nas posicoes 3901 a 3914, exceto estojos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900400', '42021', 'Maletas e pastas para documentos e de estudante, e artefatos semelhantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900400', '42029', 'Maletas e pastas para documentos e de estudante, e artefatos semelhantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900500', '39269090', 'Prancheta de plastico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900600', '48022090', 'Bobina para fax');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900600', '48119090', 'Bobina para fax');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900700', '4802549', 'Papel seda');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900800', '48025499', 'Bobina branca para maquina de calcular ou PDV');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900800', '48025799', 'Bobina branca para maquina de calcular ou PDV');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900800', '48162000', 'Bobina branca para maquina de calcular ou PDV');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900900', '4802569', 'Cartolina escolar e papel cartao, brancos e coloridos recados auto adesivos (LP note) papeis de presente, todos cortados em tamanho pronto para uso escolar e domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900900', '4802579', 'Cartolina escolar e papel cartao, brancos e coloridos recados auto adesivos (LP note) papeis de presente, todos cortados em tamanho pronto para uso escolar e domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1900900', '4802589', 'Cartolina escolar e papel cartao, brancos e coloridos recados auto adesivos (LP note) papeis de presente, todos cortados em tamanho pronto para uso escolar e domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901000', '37031010', 'Papel fotografico, exceto: (i) os papeis fotograficos emulsionados com haleto de prata tipo brilhante, matte ou lustre, em rolo e, com largura igual ou superior a 102 mm e comprimento inferior ou igual a 350 m, (ii) os papeis fotograficos emulsionados com haleto de prata tipo brilhante ou fosco, em folha e com largura igual ou superior a 152 mm e comprimento inferior ou igual a 307 mm, (iii) papel de qualidade fotografica com tecnologia “Thermo-autochrome”, que submetido a um processo de aquecimento seja ca');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901000', '37031029', 'Papel fotografico, exceto: (i) os papeis fotograficos emulsionados com haleto de prata tipo brilhante, matte ou lustre, em rolo e, com largura igual ou superior a 102 mm e comprimento inferior ou igual a 350 m, (ii) os papeis fotograficos emulsionados com haleto de prata tipo brilhante ou fosco, em folha e com largura igual ou superior a 152 mm e comprimento inferior ou igual a 307 mm, (iii) papel de qualidade fotografica com tecnologia “Thermo-autochrome”, que submetido a um processo de aquecimento seja ca');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901000', '37032000', 'Papel fotografico, exceto: (i) os papeis fotograficos emulsionados com haleto de prata tipo brilhante, matte ou lustre, em rolo e, com largura igual ou superior a 102 mm e comprimento inferior ou igual a 350 m, (ii) os papeis fotograficos emulsionados com haleto de prata tipo brilhante ou fosco, em folha e com largura igual ou superior a 152 mm e comprimento inferior ou igual a 307 mm, (iii) papel de qualidade fotografica com tecnologia “Thermo-autochrome”, que submetido a um processo de aquecimento seja ca');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901000', '37039010', 'Papel fotografico, exceto: (i) os papeis fotograficos emulsionados com haleto de prata tipo brilhante, matte ou lustre, em rolo e, com largura igual ou superior a 102 mm e comprimento inferior ou igual a 350 m, (ii) os papeis fotograficos emulsionados com haleto de prata tipo brilhante ou fosco, em folha e com largura igual ou superior a 152 mm e comprimento inferior ou igual a 307 mm, (iii) papel de qualidade fotografica com tecnologia “Thermo-autochrome”, que submetido a um processo de aquecimento seja ca');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901000', '37040000', 'Papel fotografico, exceto: (i) os papeis fotograficos emulsionados com haleto de prata tipo brilhante, matte ou lustre, em rolo e, com largura igual ou superior a 102 mm e comprimento inferior ou igual a 350 m, (ii) os papeis fotograficos emulsionados com haleto de prata tipo brilhante ou fosco, em folha e com largura igual ou superior a 152 mm e comprimento inferior ou igual a 307 mm, (iii) papel de qualidade fotografica com tecnologia “Thermo-autochrome”, que submetido a um processo de aquecimento seja ca');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901000', '48022000', 'Papel fotografico, exceto: (i) os papeis fotograficos emulsionados com haleto de prata tipo brilhante, matte ou lustre, em rolo e, com largura igual ou superior a 102 mm e comprimento inferior ou igual a 350 m, (ii) os papeis fotograficos emulsionados com haleto de prata tipo brilhante ou fosco, em folha e com largura igual ou superior a 152 mm e comprimento inferior ou igual a 307 mm, (iii) papel de qualidade fotografica com tecnologia “Thermo-autochrome”, que submetido a um processo de aquecimento seja ca');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901100', '48101390', 'Papel almaco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901200', '48161000', 'Papel hectografico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901300', '39202019', 'Papel celofane e tipo celofane');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901400', '48062000', 'Papel impermeavel');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901500', '48081000', 'Papel crepon');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901600', '48102290', 'Papel fantasia');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901700', '4809', 'Papel-carbono, papel autocopiativo (exceto os vendidos em rolos de diametro igual ou superior a 60 cm e os vendidos em folhas de formato igual ou superior a 60 cm de altura e igual ou superior a 90 cm de largura) e outros papeis para copia ou duplicacao (incluidos os papeis para estenceis ou para chapas ofsete), estenceis completos e chapas ofsete, de papel, em folhas, mesmo acondicionados em caixas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901700', '4816', 'Papel-carbono, papel autocopiativo (exceto os vendidos em rolos de diametro igual ou superior a 60 cm e os vendidos em folhas de formato igual ou superior a 60 cm de altura e igual ou superior a 90 cm de largura) e outros papeis para copia ou duplicacao (incluidos os papeis para estenceis ou para chapas ofsete), estenceis completos e chapas ofsete, de papel, em folhas, mesmo acondicionados em caixas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901800', '4817', 'Envelopes, aerogramas, bilhetes-postais nao ilustrados e cartoes para correspondencia, de papel ou cartao, caixas, sacos e semelhantes, de papel ou cartao, contendo um sortido de artigos para correspondencia');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1901900', '48201000', 'Livros de registro e de contabilidade, blocos de notas,de encomendas, de recibos, de apontamentos, de papel para cartas, agendas e artigos semelhantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1902000', '48202000', 'Cadernos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1902100', '48203000', 'Classificadores, capas para encadernacao (exceto as capas para livros) e capas de processos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1902200', '48204000', 'Formularios em blocos tipo "manifold", mesmo com folhas intercaladas de papel-carbono');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1902300', '48205000', 'albuns para amostras ou para colecoes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1902400', '48209000', 'Pastas para documentos, outros artigos escolares, de escritorio ou de papelaria, de papel ou cartao e capas para livros, de papel ou cartao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1902500', '49090000', 'Cartoes postais impressos ou ilustrados, cartoes impressos com votos ou mensagens pessoais, mesmo ilustrados, com ou sem envelopes, guarnicoes ou aplicacoes (conhecidos como cartoes de expressao social - de epoca/sentimento)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1902600', '96081000', 'Canetas esferograficas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1902700', '96082000', 'Canetas e marcadores, com ponta de feltro ou com outras pontas porosas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1902800', '96083000', 'Canetas tinteiro');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1902900', '9608', 'Outras canetas sortidos de canetas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('1903000', '480256', 'Papel cortado "cutsize" (tipo A3, A4, oficio I e II, carta e outros)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2000100', '12119090', 'Henna (embalagens de conteudo inferior ou igual a 200 g)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2000101', '12119090', 'Henna (embalagens de conteudo superior a 200 g)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2000200', '27121000', 'Vaselina');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2000300', '28142000', 'Amoniaco em solucao aquosa (amônia)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2000400', '28470000', 'Peroxido de hidrogenio, em embalagens de conteudo inferior ou igual a 500 ml');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2000500', '30067000', 'Lubrificacao intima');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2000600', '3301', 'oleos essenciais (desterpenados ou nao), incluidos os chamados "concretos" ou "absolutos" resinoides oleorresinas de extracao solucoes concentradas de oleos essenciais em gorduras, em oleos fixos, em ceras ou em materias analogas, obtidas portratamento de flores atraves de substancias gordas ou por maceracao subprodutos terpenicos residuais da desterpenacao dos oleos essenciais aguas destiladas aromaticas e solucoes aquosas de oleos essenciais, em embalagens de conteudo inferior ou igual a 500 ml');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2000700', '33030010', 'Perfumes (extratos)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2000800', '33030020', 'aguas-de-colônia');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2000900', '33041000', 'Produtos de maquilagem para os labios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2001000', '33042010', 'Sombra, delineador, lapis para sobrancelhas e rimel');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2001100', '33042090', 'Outros produtos de maquilagem para os olhos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2001200', '33043000', 'Preparacoes para manicuros e pedicuros, incluindo removedores de esmalte a base de acetona');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2001300', '33049100', 'Pos, incluidos os compactos, para maquilagem');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2001400', '33049910', 'Cremes de beleza, cremes nutritivos e locoes tônicas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2001500', '33049990', 'Outros produtos de beleza ou de maquilagem preparados e preparacoes para conservacao ou cuidados da pele, exceto as preparacoes solares e antisolares.');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2001600', '33049990', 'Preparacoes solares e antisolares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2001700', '33051000', 'Xampus para o cabelo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2001800', '33052000', 'Preparacoes para ondulacao ou alisamento, permanentes, dos cabelos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2001900', '33053000', 'Laques para o cabelo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2002000', '33059000', 'Outras preparacoes capilares, incluindo mascaras e finalizadores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2002100', '33059000', 'Condicionadores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2002200', '33059000', 'Tintura para o cabelo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2002300', '33061000', 'Dentifricios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2002400', '33062000', 'Fios utilizados para limpar os espacos interdentais (fios dentais)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2002500', '33069000', 'Outras preparacoes para higiene bucal ou dentaria');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2002600', '33071000', 'Preparacoes para barbear (antes, durante ou apos)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2002700', '33072010', 'Desodorantes (desodorizantes) corporais liquidos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2002800', '33072010', 'Antiperspirantes liquidos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2002900', '33072090', 'Outros desodorantes (desodorizantes) corporais');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2003000', '33072090', 'Outros antiperspirantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2003100', '33073000', 'Sais perfumados e outras preparacoes para banhos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2003200', '33079000', 'Outros produtos de perfumaria ou de toucador preparados');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2003300', '33079000', 'Solucoes para lentes de contato ou para olhos artificiais');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2003400', '34011190', 'Saboes de toucador em barras, pedacos ou figuras moldados');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2003500', '34011900', 'Outros saboes, produtos e preparacoes, em barras, pedacos ou figuras moldados, inclusive lencos umedecidos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2003600', '34012010', 'Saboes de toucador sob outras formas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2003700', '34013000', 'Produtos e preparacoes organicos tensoativos para lavagem da pele, na forma de liquido ou de creme, acondicionados para venda a retalho, mesmo contendo sabao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2003800', '40149010', 'Bolsa para gelo ou para agua quente');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2003900', '40149090', 'Chupetas e bicos para mamadeiras e para chupetas, de borracha');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2003901', '39269040', 'Chupetas e bicos para mamadeiras e para chupetas, de silicone');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2004000', '42021', 'Malas e maletas de toucador');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2004100', '48181000', 'Papel higienico - folha simples');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2004200', '48181000', 'Papel higienico - folha dupla e tripla');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2004300', '48182000', 'Lencos (incluidos os de maquilagem) e toalhas de mao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2004400', '48182000', 'Papel toalha de uso institucional do tipo comercializado em rolos igual ou superior a 80 metros e do tipo comercializado em folhas intercaladas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2004500', '48183000', 'Toalhas e guardanapos de mesa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2004600', '48189090', 'Toalhas de cozinha (papel toalha de uso domestico)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2004700', '96190000', 'Fraldas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2004800', '96190000', 'Tampoes higienicos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2004900', '96190000', 'Absorventes higienicos externos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2005000', '56012190', 'Hastes flexiveis (uso nao medicinal)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2005100', '56039290', 'Sutia descartavel, assemelhados e papel para depilacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2005200', '82032090', 'Pincas para sobrancelhas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2005300', '82141000', 'Espatulas (artigos de cutelaria)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2005400', '82142000', 'Utensilios e sortidos de utensilios de manicuros ou de pedicuros (incluidas as limas para unhas)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2005500', '90251110', 'Termômetros, inclusive o digital');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2005500', '90251990', 'Termômetros, inclusive o digital');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2005600', '96032', 'Escovas e pinceis de barba, escovas para cabelos, para cilios ou para unhas e outras escovas de toucador de pessoas, incluidas as que sejam partes de aparelhos, exceto escovas de dentes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2005700', '96032100', 'Escovas de dentes, incluidas as escovas para dentaduras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2005800', '96033000', 'Pinceis para aplicacao de produtos cosmeticos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2005900', '96050000', 'Sortidos de viagem, para toucador de pessoas para costura ou para limpeza de calcado ou de roupas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2006000', '9615', 'Pentes, travessas para cabelo e artigos semelhantes grampos (alfinetes) para cabelo pincas (pinceguiches), onduladores, bobes (rolos) e artefatos semelhantes para penteados, e suas partes, exceto os classificados na posicao 8516 e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2006100', '96162000', 'Borlas ou esponjas para pos ou para aplicacao de outros cosmeticos ou de produtos de toucador');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2006200', '39233000', 'Mamadeiras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2006200', '39249000', 'Mamadeiras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2006200', '39241000', 'Mamadeiras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2006200', '40149090', 'Mamadeiras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2006200', '70102000', 'Mamadeiras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2006300', '82121020', 'Aparelhos e laminas de barbear');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2006300', '82122010', 'Aparelhos e laminas de barbear');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2100100', '73211100', 'Fogoes de cozinha de uso domestico e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2100100', '73218100', 'Fogoes de cozinha de uso domestico e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2100100', '73219000', 'Fogoes de cozinha de uso domestico e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2100200', '84181000', 'Combinacoes de refrigeradores e congeladores ("freezers"), munidos de portas exteriores separadas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2100300', '84182100', 'Refrigeradores do tipo domestico, de compressao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2100400', '84182900', 'Outros refrigeradores do tipo domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2100500', '84183000', 'Congeladores ("freezers") horizontais tipo arca, de capacidade nao superior a 800 litros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2100600', '84184000', 'Congeladores ("freezers") verticais tipo armario, de capacidade nao superior a 900 litros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2100700', '841850', 'Outros moveis (arcas, armarios, vitrines, balcoes e moveis semelhantes) para a conservacao e exposicao de produtos, que incorporem um equipamento para a producao de frio');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2100800', '8418699', 'Mini adega e similares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2100900', '84186999', 'Maquinas para producao de gelo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2101000', '84189900', 'Partes dos refrigeradores, congeladores, mini adegas e similares, maquinas para producao de gelo e bebedouros descritos nos itens 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0 e 13.0.');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2101100', '842112', 'Secadoras de roupa de uso domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2101200', '84211990', 'Outras secadoras de roupas e centrifugas de uso domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2101300', '84186931', 'Bebedouros refrigerados para agua');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2101400', '84219', 'Partes das secadoras de roupas e centrifugas de uso domestico e dos aparelhos para filtrar ou depurar agua, descritos nos itens 11.0 e 12.0');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2101500', '84221100', 'Maquinas de lavar louca do tipo domestico e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2101500', '84229010', 'Maquinas de lavar louca do tipo domestico e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2101600', '844331', 'Maquinas que executem pelo menos duas das seguintes funcoes: impressao, copia ou transmissao de telecopia (fax), capazes de ser conectadas a uma maquina');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2101700', '844332', 'Outras impressoras, maquinas copiadoras e telecopiadores (fax), mesmo combinados entre si, capazes de ser conectados a uma maquina automatica para processamento de dados ou a uma rede');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2101800', '844399', 'Partes e acessorios de maquinas e aparelhos de impressao por meio de blocos, cilindros e outros elementos de impressao da posicao 8442 e de outras impressoras, maquinas copiadoras e telecopiadores (fax), mesmo combinados entre si');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2101900', '84501100', 'Maquinas de lavar roupa, mesmo com dispositivos de secagem, de uso domestico, de capacidade nao superior a 10 kg, em peso de roupa seca, inteiramente automaticas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2102000', '84501200', 'Outras maquinas de lavar roupa, mesmo com dispositivos de secagem, de uso domestico, com secador centrifugo incorporado');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2102100', '84501900', 'Outras maquinas de lavar roupa, mesmo com dispositivos de secagem, de uso domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2102200', '845020', 'Maquinas de lavar roupa, mesmo com dispositivos de secagem, de uso domestico, de capacidade superior a 10 kg, em peso de roupa seca');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2102300', '845090', 'Partes de maquinas de lavar roupa, mesmo com dispositivos de secagem, de uso domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2102400', '84512100', 'Maquinas de secar de uso domestico de capacidade nao superior a 10 kg, em peso de roupa seca');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2102500', '84512990', 'Outras maquinas de secar de uso domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2102600', '845190', 'Partes de maquinas de secar de uso domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2102700', '84521000', 'Maquinas de costura de uso domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2102800', '847130', 'Maquinas automaticas para processamento de dados, portateis, de peso nao superior a 10 kg, contendo pelo menos uma unidade central de processamento, um teclado e uma tela');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2102900', '84714', 'Outras maquinas automaticas para processamento de dados');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2103000', '84715010', 'Unidades de processamento, de pequena capacidade, exceto as das subposicoes 8471.41 ou 8471.49, podendo conter, no mesmo corpo, um ou dois dos seguintes tipos de unidades: unidade de memoria, unidade de entrada e unidade de saida baseadas em microprocessadores, com capacidade de instalacao, dentro do mesmo gabinete, de unidades de memoria da subposicao 8471.70, podendo conter multiplos conectores de expansao, e valor FOB inferior ou igual a US$ 12.500,00, por unidade');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2103100', '8471605', 'Unidades de entrada, exceto as classificadas na posicao 8471.60.54');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2103200', '84716090', 'Outras unidades de entrada ou de saida, podendo conter, no mesmo corpo, unidades de memoria');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2103300', '847170', 'Unidades de memoria');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2103400', '847190', 'Outras maquinas automaticas para processamento de dados e suas unidades leitores magneticos ou opticos, maquinas para registrar dados em suporte sob forma codificada, e maquinas para processamento desses dados, nao especificadas nem compreendidas em outras posicoes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2103500', '847330', 'Partes e acessorios das maquinas da posicao 84.71');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2103600', '85043', 'Outros transformadores, exceto os classificados nas posicoes 8504.33.00 e 8504.34.00');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2103700', '85044010', 'Carregadores de acumuladores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2103800', '85044040', 'Equipamentos de alimentacao ininterrupta de energia (UPS ou "no break")');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2103900', '85078000', 'Outros acumuladores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2104000', '8508', 'Aspiradores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2104100', '8509', 'Aparelhos eletromecanicos de motor eletrico incorporado, de uso domestico e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2104200', '85098010', 'Enceradeiras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2104300', '85161000', 'Chaleiras eletricas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2104400', '85164000', 'Ferros eletricos de passar');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2104500', '85165000', 'Fornos de microondas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2104600', '85166000', 'Outros fornos fogareiros (incluidas as chapas de coccao), grelhas e assadeiras, exceto os portateis');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2104700', '85166000', 'Outros fornos fogareiros (incluidas as chapas de coccao), grelhas e assadeiras, portateis');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2104800', '85167100', 'Outros aparelhos eletrotermicos de uso domestico – Cafeteiras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2104900', '85167200', 'Outros aparelhos eletrotermicos de uso domestico - Torradeiras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2105000', '851679', 'Outros aparelhos eletrotermicos de uso domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2105100', '85169000', 'Partes das chaleiras, ferros, fornos e outros aparelhos eletrotermicos da posicao 85.16, descritos nos itens 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0 e 50.0');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2105200', '85171100', 'Aparelhos telefônicos por fio com unidade auscultador- microfone sem fio');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2105300', '851712', 'Telefones para redes celulares e para outras redes sem fio, exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2105400', '8517189', 'Outros aparelhos telefônicos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2105500', '8517625', 'Aparelhos para transmissao ou recepcao de voz, imagem ou outros dados em rede com fio, exceto os classificados nas posicoes 8517.62.51, 8517.62.52 e 8517.62.53');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2105600', '8518', 'Microfones e seus suportes altofalantes, mesmo montados nos seus receptaculos, fones de ouvido (auscultadores), mesmo combinados com microfone e conj untos ou sortidos constituidos por um microfone e um ou mais alto-falantes, amplificadores eletricos de audiofreqüencia, aparelhos eletricos de amplificacao de som suas partes e acessorios exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2105700', '8519', 'Aparelhos de radiodifusao suscetiveis de funcionarem sem fonte externa de energia. Aparelhos de gravacao de som aparelhos de reproducao de som aparelhos de gravacao e de reproducao de som partes e acessorios exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2105700', '8522', 'Aparelhos de radiodifusao suscetiveis de funcionarem sem fonte externa de energia. Aparelhos de gravacao de som aparelhos de reproducao de som aparelhos de gravacao e de reproducao de som partes e acessorios exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2105700', '85271', 'Aparelhos de radiodifusao suscetiveis de funcionarem sem fonte externa de energia. Aparelhos de gravacao de som aparelhos de reproducao de som aparelhos de gravacao e de reproducao de som partes e acessorios exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2105800', '85198190', 'Outros aparelhos de gravacao de som aparelhos de reproducao de som aparelhos de gravacao e de reproducao de som partes e acessorios exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2105900', '85219010', 'Gravador-reprodutor e editor de imagem e som, em discos, por meio magnetico, optico ou optomagnetico, exceto de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2106000', '85219090', 'Outros aparelhos videofônicos de gravacao ou reproducao, mesmo incorporando um receptor de sinais videofônicos, exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2106100', '85235110', 'Cartoes de memoria ("memory cards")');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2106200', '85235200', 'Cartoes inteligentes ("smart cards")');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2106300', '8525802', 'Cameras fotograficas digitais e cameras de video e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2106400', '85279', 'Outros aparelhos receptores para radiodifusao, mesmo combinados num involucro, com um aparelho de gravacao ou de reproducao de som, ou com um relogio, inclusive caixa acustica para Home Theaters classificados na posicao 8518');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2106500', '85284929', 'Monitores e projetores que nao incorporem aparelhos receptores de televisao, policromaticos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2106500', '85285920', 'Monitores e projetores que nao incorporem aparelhos receptores de televisao, policromaticos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2106500', '852869', 'Monitores e projetores que nao incorporem aparelhos receptores de televisao, policromaticos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2106600', '85285120', 'Outros monitores dos tipos utilizados exclusiva ou principalmente com uma maquina automatica para processamento de dados da posicao 84.71, policromaticos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2106700', '85287', 'Aparelhos receptores de televisao, mesmo que incorporem um aparelho receptor de radiodifusao ou um aparelho de gravacao ou reproducao de som ou de imagens - Televisores de CRT (tubo de raios catodicos).');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2106800', '85287', 'Aparelhos receptores de televisao, mesmo que incorporem um aparelho receptor de radiodifusao ou um aparelho de gravacao ou reproducao de som ou de imagens - Televisores de LCD (Display de Cristal Liquido)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2106900', '85287', 'Aparelhos receptores de televisao, mesmo que incorporem um aparelho receptor de radiodifusao ou um aparelho de gravacao ou reproducao de som ou de imagens - Televisores de Plasma');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2107000', '85287', 'Outros aparelhos receptores de televisao nao dotados de monitores ou display de video');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2107100', '85287', 'Outros aparelhos receptores de televisao nao relacionados em outros itens deste anexo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2107200', '900610', 'Cameras fotograficas dos tipos utilizadas para preparacao de cliches ou cilindros de impressao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2107300', '90064000', 'Cameras fotograficas para filmes de revelacao e copiagem instantaneas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2107400', '90189050', 'Aparelhos de diatermia');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2107500', '90191000', 'Aparelhos de massagem');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2107600', '90328911', 'Reguladores de voltagem eletrônicos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2107700', '95045000', 'Consoles e maquinas de jogos de video, exceto os classificados na subposicao 9504.30');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2107800', '8517621', 'Multiplexadores e concentradores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2107900', '85176222', 'Centrais automaticas privadas, de capacidade inferior ou igual a 25 ramais');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2108000', '85176239', 'Outros aparelhos para comutacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2108100', '8517624', 'Roteadores digitais, em redes com ou sem fio');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2108200', '85176262', 'Aparelhos emissores com receptor incorporado de sistema troncalizado ("trunking"), de tecnologia celular');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2108300', '8517629', 'Outros aparelhos de recepcao, conversao e transmissao ou regeneracao de voz, imagens ou outros dados, incluindo os aparelhos de comutacao e roteamento');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2108400', '85177021', 'Antenas proprias para telefones celulares portateis, exceto as telescopicas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2108500', '821490', 'Aparelhos ou maquinas de barbear, maquinas de cortar o cabelo ou de tosquiar e aparelhos de depilar, e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2108500', '8510', 'Aparelhos ou maquinas de barbear, maquinas de cortar o cabelo ou de tosquiar e aparelhos de depilar, e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2108600', '84145', 'Ventiladores, exceto os de uso agricola');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2108700', '84145990', 'Ventiladores de uso agricola');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2108800', '84146000', 'Coifas com dimensao horizontal maxima nao superior a 120 cm');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2108900', '84149020', 'Partes de ventiladores ou coifas aspirantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2109000', '841510', 'Maquinas e aparelhos de ar condicionado contendo um ventilador motorizado e dispositivos proprios para modificar a temperatura e a umidade, incluidos as maquinas e aparelhos em que a umidade nao seja regulavel separadamente e suas partes e pecas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2109000', '84158', 'Maquinas e aparelhos de ar condicionado contendo um ventilador motorizado e dispositivos proprios para modificar a temperatura e a umidade, incluidos as maquinas e aparelhos em que a umidade nao seja regulavel separadamente e suas partes e pecas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2109100', '84151011', 'Aparelhos de ar-condicionado tipo Split System (sistema com elementos separados) com unidade externa e interna');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2109200', '84151019', 'Aparelhos de ar-condicionado com capacidade inferior ou igual a 30.000 frigorias/hora');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2109300', '84151090', 'Aparelhos de ar-condicionado com capacidade acima de 30.000 frigorias/hora');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2109400', '84159010', 'Unidades evaporadoras (internas) de aparelho de ar-condicionado do tipo Split System (sistema com elementos separados), com capacidade inferior ou igual a 30.000 frigorias/hora');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2109500', '84159020', 'Unidades condensadoras (externas) de aparelho de ar-condicionado do tipo Split System (sistema com elementos separados), com capacidade inferior ou igual a 30.000 frigorias/hora');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2109600', '84212100', 'Aparelhos eletricos para filtrar ou depurar agua (purificadores de agua refrigerados)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2109700', '84243010', 'Lavadora de alta pressao e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2109700', '84243090', 'Lavadora de alta pressao e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2109700', '84249090', 'Lavadora de alta pressao e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2109800', '84672100', 'Furadeiras eletricas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2109900', '85162', 'Aparelhos eletricos para aquecimento de ambientes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2110000', '85163100', 'Secadores de cabelo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2110100', '85163200', 'Outros aparelhos para arranjos do cabelo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2110200', '8518', 'Microfones e seus suportes alto-falantes, mesmo montados nos seus receptaculos, fones de ouvido (auscultadores), mesmo combinados com microfone e conjuntos ou sortidos constituidos por um microfone e um ou mais alto-falantes, amplificadores eletricos de audiofreqüencia, aparelhos eletricos de amplificacao de som suas partes e acessorios exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2110300', '8527', 'Aparelhos receptores para radiodifusao, mesmo combinados num mesmo involucro, com um aparelho de gravacao ou de reproducao de som, ou com um relogio, exceto os classificados na posicao 8527.2 que sejam de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2110400', '85219090', 'Outros aparelhos videofônicos de gravacao ou de reproducao, mesmo incorporando um receptor de sinais videofônicos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2110500', '84796000', 'Climatizadores de ar');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2110600', '84159090', 'Outras partes para maquinas e aparelhos de arcondicionado que contenham um ventilador motorizado e dispositivos proprios para modificar a temperatura e a umidade, incluindo as maquinas e aparelhos em que a umidade nao seja regulavel separadamente');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2110700', '85258019', 'Cameras de televisao e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2110800', '84231000', 'Balancas de uso domestico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2110900', '8540', 'Tubos e valvulas, eletrônicos, de catodo quente, catodo frio ou fotocatodo (por exemplo, tubos e valvulas, de vacuo, de vapor ou de gas, ampolas retificadoras de vapor de mercurio, tubos catodicos, tubos e valvulas para cameras de televisao)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2111000', '8517', 'Aparelhos eletricos para telefonia outros aparelhos para transmissao ou recepcao de voz, imagens ou outros dados, incluidos os aparelhos para comunicacao em redes por fio ou redes sem fio (tal como uma rede local (LAN) ou uma rede de area estendida (WAN), incluidas suas partes, exceto os de uso automotivo e os classificados nas posicoes 8517.62.51, 8517.62.52 e 8517.62.53');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2111100', '8517', 'Interfones, seus acessorios, tomadas e "plugs"');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2111200', '8529', 'Partes reconheciveis como exclusiva ou principalmente destinadas aos aparelhos das posicoes 8525 a 8528 exceto as de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2111300', '8531', 'Aparelhos eletricos de sinalizacao acustica ou visual (por exemplo, campainhas, sirenes, quadros indicadores, aparelhos de alarme para protecao contra roubo ou incendio, exceto os de uso automotivo e os classificados nas posicoes 8531.10 e 8531.80.00.');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2111400', '853110', 'Aparelhos eletricos de alarme, para protecao contra roubo ou incendio e aparelhos semelhantes, exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2111500', '85318000', 'Outros aparelhos de sinalizacao acustica ou visual, exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2111600', '853400', 'Circuitos impressos, exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2111700', '85414011', 'Diodos emissores de luz (LED), exceto diodos "laser"');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2111700', '85414021', 'Diodos emissores de luz (LED), exceto diodos "laser"');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2111700', '85414022', 'Diodos emissores de luz (LED), exceto diodos "laser"');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2111800', '85437092', 'Eletrificadores de cercas eletrônicos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2111900', '90303', 'Aparelhos e instrumentos para medida ou controle da tensao, intensidade, resistencia ou da potencia, sem dispositivo registrador exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2112000', '903089', 'Analisadores logicos de circuitos digitais, de espectro de frequencia, frequencimetros, fasimetros, e outros instrumentos e aparelhos de controle de grandezas eletricas e deteccao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2112100', '910700', 'Interruptores horarios e outros aparelhos que permitam acionar um mecanismo em tempo determinado, munidos de maquinismo de aparelhos de relojoaria ou de motor sincrono');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2112200', '9405', 'Aparelhos de iluminacao (incluidos os projetores) e suas partes, nao especificados nem compreendidos em outras posicoes anuncios, cartazes ou tabuletas e placas indicadoras luminosos, e artigos semelhantes, contendo uma fonte luminosa fixa permanente, e suas partes nao especificadas nem compreendidas em outras posicoes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2200100', '2309', 'Racao tipo “pet” para animais domesticos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2300100', '210500', 'Sorvetes de qualquer especie');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2300200', '1806', 'Preparados para fabricacao de sorvete em maquina');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2300200', '1901', 'Preparados para fabricacao de sorvete em maquina');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2300200', '2106', 'Preparados para fabricacao de sorvete em maquina');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2400100', '3208', 'Tintas, vernizes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2400100', '3209', 'Tintas, vernizes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2400100', '3210', 'Tintas, vernizes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2400200', '2821', 'Xadrez e pos assemelhados, exceto pigmentos a base de dioxido de titanio classificados na posicao 3206.11.19');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2400200', '32041700', 'Xadrez e pos assemelhados, exceto pigmentos a base de dioxido de titanio classificados na posicao 3206.11.19');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2400200', '3206', 'Xadrez e pos assemelhados, exceto pigmentos a base de dioxido de titanio classificados na posicao 3206.11.19');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2500100', '87021000', 'Veiculos automoveis para transporte de 10 pessoas ou mais, incluindo o motorista, com motor de pistao, de ignicao por compressao (diesel ou semidiesel), com volume interno de habitaculo, destinado a passageiros e motorista, superior a 6 m³, mas inferior a 9 m³');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2500200', '87029090', 'Outros veiculos automoveis para transporte de 10 pessoas ou mais, incluindo o motorista, com volume interno de habitaculo, destinado a passageiros e motorista, superior a 6 m³, mas inferior a 9 m');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2500300', '87032100', 'Automoveis com motor explosao, de cilindrada nao superior a 1000 cm³');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2500400', '87032210', 'Automoveis com motor explosao, de cilindrada superior a 1000 cm³, mas nao superior a 1500 cm³, com capacidade de transporte de pessoas sentadas inferior ou igual a 6, incluido o condutor, exceto carro celular');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2500500', '87032290', 'Outros automoveis com motor explosao, de cilindrada superior a 1000 cm³, mas nao superior a 1500 cm³, exceto carro celular');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2500600', '87032310', 'Automoveis com motor explosao, de cilindrada superior a 1500 cm³, mas nao superior a 3000 cm³, com capacidade de transporte de pessoas sentadas inferior ou igual a 6, incluido o condutor, exceto carro celular, carro funerario e automoveis de corrida');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2500700', '87032390', 'Outros automoveis com motor explosao, de cilindrada superior a 1500 cm³, mas nao superior a 3000 cm³, exceto carro celular, carro funerario e automoveis de corrida');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2500800', '87032410', 'Automoveis com motor explosao, de cilindrada superior a 3000 cm³, com capacidade de transporte de pessoas sentadas inferior ou igual a 6, incluido o condutor, exceto carro celular, carro funerario e automoveis de corrida');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2500900', '87032490', 'Outros automoveis com motor explosao, de cilindrada superior a 3000 cm³, exceto carro celular, carro funerario e automoveis de corrida');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2501000', '87033210', 'Automoveis com motor diesel ou semidiesel, de cilindrada superior a 1500 cm³, mas nao superior a 2500 cm³, com capacidade de transporte de pessoas sentadas inferior ou igual a 6, incluido o condutor, exceto ambulancia, carro celular e carro funerario');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2501100', '87033290', 'Outros automoveis com motor diesel ou semidiesel, de cilindrada superior a 1500 cm³, mas nao superior a 2500 cm³, exceto ambulancia, carro celular e carro funerario');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2501200', '87033310', 'Automoveis com motor diesel ou semidiesel, de cilindrada superior a 2500 cm³, com capacidade de transporte de pessoas sentadas inferior ou igual a 6, incluido o condutor, exceto carro celular e carro funerario');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2501300', '87033390', 'Outros automoveis com motor diesel ou semidiesel, de cilindrada superior a 2500 cm³, exceto carro celular e carro funerario');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2501400', '87042110', 'Veiculos automoveis para transporte de mercadorias, de peso em carga maxima nao superior a 5 toneladas, chassis com motor diesel ou semidiesel e cabina, exceto caminhao de peso em carga maxima superior a 3,9 toneladas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2501500', '87042120', 'Veiculos automoveis para transporte de mercadorias, de peso em carga maxima nao superior a 5 toneladas, com motor diesel ou semidiesel, com caixa basculante, exceto caminhao de peso em carga maxima superior a 3,9 toneladas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2501600', '87042130', 'Veiculos automoveis para transporte de mercadorias, de peso em carga maxima nao superior a 5 toneladas, frigorificos ou isotermicos, com motor diesel ou semidiesel, exceto caminhao de peso em carga maxima superior a 3,9 toneladas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2501700', '87042190', 'Outros veiculos automoveis para transporte de mercadorias, de peso em carga maxima nao superior a 5 toneladas, com motor diesel ou semidiesel, exceto carro-forte para transporte de valores e caminhao de peso em carga maxima superior a 3,9 toneladas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2501800', '87043110', 'Veiculos automoveis para transporte de mercadorias, de peso em carga maxima nao superior a 5 toneladas, com motor a explosao, chassis e cabina, exceto caminhao de peso em carga maxima superior a 3,9 toneladas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2501900', '87043120', 'Veiculos automoveis para transporte de mercadorias, de peso em carga maxima nao superior a 5, exceto caminhao de peso em carga toneladas, com motor explosao, caixa basculante');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2502000', '87043130', 'Veiculos automoveis para transporte de mercadorias, de peso em carga maxima nao superior a 5 toneladas, frigorificos ou isotermicos com motor explosao, exceto caminhao de peso em carga maxima superior a 3,9 toneladas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2502100', '87043190', 'Outros veiculos automoveis para transporte de mercadorias, de peso em carga maxima nao superior a 5 toneladas, com motor a explosao, exceto carro-forte para transporte de valores e caminhao de peso em carga maxima superior a 3,9 toneladas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2600100', '8711', 'Motocicletas (incluidos os ciclomotores) e outros ciclos equipados com motor auxiliar, mesmo com carro lateral carros laterais');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2700100', '7009', 'Espelhos de vidro, mesmo emoldurados, exceto os de uso automotivo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2700200', '7013', 'Objetos de vidro para servico de mesa ou de cozinha');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2700300', '70133700', 'Outros copos, exceto de vitroceramica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2700400', '70134290', 'Objetos para servico de mesa (exceto copos) ou de cozinha, exceto de vitroceramica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2800100', '33030010', 'Perfumes (extratos)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2800200', '33030020', 'aguas-de-colônia');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2800300', '33041000', 'Produtos de maquiagem para os labios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2800400', '33042010', 'Sombra, delineador, lapis para sobrancelhas e rimel');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2800500', '33042090', 'Outros produtos de maquiagem para os olhos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2800600', '33043000', 'Preparacoes para manicuros e pedicuros');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2800700', '33049100', 'Pos para maquiagem, incluindo os compactos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2800800', '33049910', 'Cremes de beleza, cremes nutritivos e locoes tônicas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2800900', '33049990', 'Outros produtos de beleza ou de maquiagem preparados e preparacoes para conservacao ou cuidados da pele, exceto as preparacoes antisolares e os bronzeadores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2801000', '33049990', 'Preparacoes antisolares e os bronzeadores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2801100', '33051000', 'Xampus para o cabelo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2801200', '33052000', 'Preparacoes para ondulacao ou alisamento, permanentes, dos cabelos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2801300', '33059000', 'Outras preparacoes capilares');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2801400', '33059000', 'Tintura para o cabelo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2801500', '33071000', 'Preparacoes para barbear (antes, durante ou apos)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2801600', '33072010', 'Desodorantes corporais e antiperspirantes, liquidos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2801700', '33072090', 'Outros desodorantes corporais e antiperspirantes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2801800', '33079000', 'Outros produtos de perfumaria ou de toucador preparados');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2801900', '33079000', 'Outras preparacoes cosmeticas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2802000', '34011190', 'Saboes de toucador, em barras, pedacos ou figuras moldadas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2802100', '34011900', 'Outros saboes, produtos e preparacoes organicos tensoativos, inclusive papel, pastas (ouates), feltros e falsos tecidos, impregnados, revestidos ou recobertos de sabao ou de detergentes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2802200', '34012010', 'Saboes de toucador sob outras formas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2802300', '34013000', 'Produtos e preparacoes organicos tensoativos para lavagem da pele, em forma de liquido ou de creme, acondicionados para venda a retalho, mesmo contendo sabao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2802400', '48182000', 'Lencos de papel, incluindo os de desmaquiar');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2802500', '82141000', 'Apontadores de lapis para maquiagem');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2802600', '82142000', 'Utensilios e sortidos de utensilios de manicuros ou de pedicuros (incluindo as limas para unhas)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2802700', '96032900', 'Escovas e pinceis de barba, escovas para cabelos, para cilios ou para unhas e outras escovas de toucador de pessoas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2802800', '96033000', 'Pinceis para aplicacao de produtos cosmeticos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2802900', '96161000', 'Vaporizadores de toucador, suas armacoes e cabecas de armacoes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803000', '96162000', 'Borlas ou esponjas para pos ou para aplicacao de outros cosmeticos ou de produtos de toucador');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803100', '42021', 'Malas e maletas de toucador');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803200', '9615', 'Pentes, travessas para cabelo e artigos semelhantes grampos (alfinetes) para cabelo pincas (“pinceguiches”), onduladores, bobs (rolos) e artefatos semelhantes para penteados, e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803300', '39241000', 'Mamadeiras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803300', '39249000', 'Mamadeiras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803300', '40149090', 'Mamadeiras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803400', '40149090', 'Chupetas e bicos para mamadeiras e para chupetas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803500', '33', 'Outros produtos cosmeticos e de higiene pessoal nao relacionados em outros itens deste anexo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803500', '34', 'Outros produtos cosmeticos e de higiene pessoal nao relacionados em outros itens deste anexo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803600', '44', 'Outros artigos destinados a cuidados pessoais nao relacionados em outros itens deste anexo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803600', '64', 'Outros artigos destinados a cuidados pessoais nao relacionados em outros itens deste anexo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803600', '65', 'Outros artigos destinados a cuidados pessoais nao relacionados em outros itens deste anexo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803600', '82', 'Outros artigos destinados a cuidados pessoais nao relacionados em outros itens deste anexo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803600', '90', 'Outros artigos destinados a cuidados pessoais nao relacionados em outros itens deste anexo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803600', '96', 'Outros artigos destinados a cuidados pessoais nao relacionados em outros itens deste anexo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803700', '39', 'Acessorios (por exemplo, bijuterias, relogios, oculos de sol, bolsas, mochilas, frasqueiras, carteiras, porta-cartoes, porta-documentos, porta-celulares e embalagens presenteaveis (por exemplo, caixinhas de papel), entre outros itens assemelhados)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803700', '48', 'Acessorios (por exemplo, bijuterias, relogios, oculos de sol, bolsas, mochilas, frasqueiras, carteiras, porta-cartoes, porta-documentos, porta-celulares e embalagens presenteaveis (por exemplo, caixinhas de papel), entre outros itens assemelhados)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803700', '91', 'Acessorios (por exemplo, bijuterias, relogios, oculos de sol, bolsas, mochilas, frasqueiras, carteiras, porta-cartoes, porta-documentos, porta-celulares e embalagens presenteaveis (por exemplo, caixinhas de papel), entre outros itens assemelhados)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803700', '42', 'Acessorios (por exemplo, bijuterias, relogios, oculos de sol, bolsas, mochilas, frasqueiras, carteiras, porta-cartoes, porta-documentos, porta-celulares e embalagens presenteaveis (por exemplo, caixinhas de papel), entre outros itens assemelhados)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803700', '71', 'Acessorios (por exemplo, bijuterias, relogios, oculos de sol, bolsas, mochilas, frasqueiras, carteiras, porta-cartoes, porta-documentos, porta-celulares e embalagens presenteaveis (por exemplo, caixinhas de papel), entre outros itens assemelhados)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803700', '83', 'Acessorios (por exemplo, bijuterias, relogios, oculos de sol, bolsas, mochilas, frasqueiras, carteiras, porta-cartoes, porta-documentos, porta-celulares e embalagens presenteaveis (por exemplo, caixinhas de papel), entre outros itens assemelhados)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803700', '90', 'Acessorios (por exemplo, bijuterias, relogios, oculos de sol, bolsas, mochilas, frasqueiras, carteiras, porta-cartoes, porta-documentos, porta-celulares e embalagens presenteaveis (por exemplo, caixinhas de papel), entre outros itens assemelhados)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803800', '61', 'Vestuario e seus acessorios calcados, polainas e artefatos semelhantes, e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803800', '62', 'Vestuario e seus acessorios calcados, polainas e artefatos semelhantes, e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803800', '64', 'Vestuario e seus acessorios calcados, polainas e artefatos semelhantes, e suas partes');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803900', '42', 'Outros artigos de vestuario em geral, exceto os relacionados no item anterior');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803900', '52', 'Outros artigos de vestuario em geral, exceto os relacionados no item anterior');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803900', '55', 'Outros artigos de vestuario em geral, exceto os relacionados no item anterior');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803900', '58', 'Outros artigos de vestuario em geral, exceto os relacionados no item anterior');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803900', '63', 'Outros artigos de vestuario em geral, exceto os relacionados no item anterior');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2803900', '65', 'Outros artigos de vestuario em geral, exceto os relacionados no item anterior');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '39', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '40', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '56', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '63', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '66', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '69', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '70', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '73', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '82', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '83', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '84', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '91', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '94', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804000', '96', 'Artigos de casa');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804100', '13', 'Produtos das industrias alimentares e bebidas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804100', '15', 'Produtos das industrias alimentares e bebidas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804100', '23', 'Produtos das industrias alimentares e bebidas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804200', '33', 'Produtos destinados a higiene bucal');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '22', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '27', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '28', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '29', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '33', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '34', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '35', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '38', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '39', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '63', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '68', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '73', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '84', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '85', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804300', '86', 'Produtos de limpeza e conservacao domestica');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('2804400', '', 'Outros produtos comercializados pelo sistema de marketing direto porta-a-porta a consumidor final nao relacionados em outros itens deste anexo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0100100', '38151210', 'Catalisadores em colmeia ceramica ou metalica para conversao catalitica de gases de escape de veiculos e outros catalizadores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0100100', '38151290', 'Catalisadores em colmeia ceramica ou metalica para conversao catalitica de gases de escape de veiculos e outros catalizadores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0100200', '3917', 'Tubos e seus acessorios (por exemplo, juntas, cotovelos, flanges, unioes), de plasticos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0100300', '39181000', 'Protetores de cacamba');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0100400', '39233000', 'Reservatorios de oleo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0100500', '39263000', 'Frisos, decalques, molduras e acabamentos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0100600', '40103', 'Correias de transmissao de borracha vulcanizada, de materias texteis, mesmo impregnadas, revestidas ou recobertas, de plastico, ou estratificadas com plastico ou reforcadas com metal ou com outras materias');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0100600', '59100000', 'Correias de transmissao de borracha vulcanizada, de materias texteis, mesmo impregnadas, revestidas ou recobertas, de plastico, ou estratificadas com plastico ou reforcadas com metal ou com outras materias');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0100700', '40169300', 'Juntas, gaxetas e outros elementos com funcao semelhante de vedacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0100700', '4823909', 'Juntas, gaxetas e outros elementos com funcao semelhante de vedacao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0100800', '40161010', 'Partes de veiculos automoveis, tratores e maquinas autopropulsadas');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0100900', '40169990', 'Tapetes, revestimentos, mesmo confeccionados, batentes, buchas e coxins');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0100900', '57050000', 'Tapetes, revestimentos, mesmo confeccionados, batentes, buchas e coxins');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0101000', '59039000', 'Tecidos impregnados, revestidos, recobertos ou estratificados, com plastico');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0101100', '59090000', 'Mangueiras e tubos semelhantes, de materias texteis, mesmo com reforco ou acessorios de outras materias');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0101200', '63061', 'Encerados e toldos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0101300', '65061000', 'Capacetes e artefatos de uso semelhante, de protecao, para uso em motocicletas, incluidos ciclomotores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0101400', '6813', 'Guarnicoes de friccao (por exemplo, placas, rolos, tiras, segmentos, discos, aneis, pastilhas), nao montadas, para freios, embreagens ou qualquer outro mecanismo de friccao, a base de amianto, de outras substancias minerais ou de celulose, mesmo combinadas com texteis ou outras materias');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0101500', '70071100', 'Vidros de dimensoes e formatos que permitam aplicacao automotiva');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0101500', '70072100', 'Vidros de dimensoes e formatos que permitam aplicacao automotiva');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0101600', '70091000', 'Espelhos retrovisores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0101700', '70140000', 'Lentes de farois, lanternas e outros utensilios');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0101800', '73110000', 'Cilindro de aco para GNV (gas natural veicular)');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0101900', '73110000', 'Recipientes para gases comprimidos ou liquefeitos, de ferro fundido, ferro ou aco, exceto o descrito no item 18.0');
COMMIT WORK;
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0102000', '7320', 'Molas e folhas de molas, de ferro ou aco');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0102100', '7325', 'Obras moldadas, de ferro fundido, ferro ou aco, exceto as do codigo 7325.91.00');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0102200', '780600', 'Peso de chumbo para balanceamento de roda');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0102300', '80070090', 'Peso para balanceamento de roda e outros utensilios de estanho');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0102400', '830120', 'Fechaduras e partes de fechaduras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0102400', '830160', 'Fechaduras e partes de fechaduras');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0102500', '830170', 'Chaves apresentadas isoladamente');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0102600', '83021000', 'Dobradicas, guarnicoes, ferragens e artigos semelhantes de metais comuns');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0102600', '83023000', 'Dobradicas, guarnicoes, ferragens e artigos semelhantes de metais comuns');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0102700', '831000', 'Triangulo de seguranca');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0102800', '84073', 'Motores de pistao alternativo dos tipos utilizados para propulsao de veiculos do Capitulo 87');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0102900', '840820', 'Motores dos tipos utilizados para propulsao de veiculos automotores');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103000', '84099', 'Partes reconheciveis como exclusiva ou principalmente destinadas aos motores das posicoes 8407 ou 8408');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103100', '84122', 'Motores hidraulicos');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103200', '841330', 'Bombas para combustiveis, lubrificantes ou liquidos de arrefecimento, proprias para motores de ignicao por centelha ou por compressao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103300', '84141000', 'Bombas de vacuo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103400', '8414801', 'Compressores e turbocompressores de ar');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103400', '8414802', 'Compressores e turbocompressores de ar');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103500', '84139190', 'Partes das bombas, compressores e turbocompressores dos itens 32.0, 33.0 e 34.0');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103500', '84149010', 'Partes das bombas, compressores e turbocompressores dos itens 32.0, 33.0 e 34.0');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103500', '8414903', 'Partes das bombas, compressores e turbocompressores dos itens 32.0, 33.0 e 34.0');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103500', '84149039', 'Partes das bombas, compressores e turbocompressores dos itens 32.0, 33.0 e 34.0');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103600', '841520', 'Maquinas e aparelhos de ar condicionado');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103700', '84212300', 'Aparelhos para filtrar oleos minerais nos motores de ignicao por centelha ou por compressao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103800', '84212990', 'Filtros a vacuo');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0103900', '84219', 'Partes dos aparelhos para filtrar ou depurar liquidos ou gases');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0104000', '84241000', 'Extintores, mesmo carregados');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0104100', '84213100', 'Filtros de entrada de ar para motores de ignicao por centelha ou por compressao');
INSERT INTO sacncmcest (CEST, CODIGO, DESCRI)
VALUES ('0104200', '84213920', 'Depuradores por conversao catalitica de gases de escape');